Repository traefik/traefik, pull requests merged in 2018-08, with the labels that each got.

#3702 No need for npm progress=false
  webui/Dockerfile
Labels: area/provider/docker, area/webui, size/S, status/3-needs-merge

#3703 Move prometheusState.reset() to test file.
  metrics/prometheus.go
  metrics/prometheus_test.go
Labels: area/middleware/metrics, size/S, status/3-needs-merge

#3706 Fix missing tracing backend in documentation
  docs/configuration/tracing.md
  middlewares/tracing/entrypoint_test.go
Labels: area/documentation, area/middleware, area/middleware/tracing, kind/bug/fix, size/S, status/3-needs-merge

#3709 Prepare release 1.7.0-rc3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3708 Use official Pebble Image.
  integration/acme_test.go
  integration/resources/compose/pebble.yml
Labels: area/acme, kind/enhancement, size/S, status/3-needs-merge

#3707 Small code enhancements on providers
  provider/consulcatalog/config.go
  provider/docker/docker.go
  provider/dynamodb/dynamodb.go
  provider/ecs/ecs.go
  provider/kubernetes/client.go
  provider/marathon/config.go
Labels: area/provider, kind/enhancement, size/S, status/3-needs-merge

#3711 Improve Connection Limit Kubernetes Documentation
  docs/configuration/backends/kubernetes.md
Labels: area/documentation, area/provider/k8s, size/S, status/3-needs-merge

#3714 Migrate Compress from bool to struct
  anonymize/anonymize_config_test.go
  configuration/entrypoints.go
  configuration/entrypoints_test.go
  docs/configuration/entrypoints.md
  middlewares/compress.go
  server/server_middlewares.go
Labels: area/middleware, kind/enhancement, size/S, status/3-needs-merge

#3718 Merge current v1.7 into master
  CHANGELOG.md
  Gopkg.lock
  acme/acme.go
  cmd/configuration.go
  configuration/configuration.go
  docs/configuration/backends/kubernetes.md
  docs/configuration/tracing.md
  docs/index.md
  docs/user-guide/kubernetes.md
  examples/quickstart/docker-compose.yml
  h2c/h2c.go
  integration/acme_test.go
  integration/consul_test.go
  integration/etcd3_test.go
  integration/etcd_test.go
  integration/fixtures/file/dir/simple2.toml
  integration/fixtures/https/https_redirect.toml
  integration/https_test.go
  integration/resources/compose/pebble.yml
  integration/try/condition.go
  integration/try/try.go
  middlewares/addPrefix.go
  middlewares/redirect/redirect.go
  middlewares/stripPrefix.go
  middlewares/stripPrefixRegex.go
  middlewares/tracing/entrypoint.go
  middlewares/tracing/entrypoint_test.go
  middlewares/tracing/forwarder.go
  middlewares/tracing/forwarder_test.go
  middlewares/tracing/tracing.go
  middlewares/tracing/tracing_test.go
  provider/acme/provider.go
  provider/acme/provider_test.go
  provider/kubernetes/annotations.go
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
  types/types.go
  vendor/github.com/vulcand/oxy/forward/fwd.go
Labels: area/infrastructure, size/L

#3719 Update kubernetes.md
  docs/configuration/backends/kubernetes.md
Labels: area/documentation, area/provider/k8s, size/S, status/3-needs-merge

#3720 Simple documentation grammar update in tracing
  docs/configuration/tracing.md
Labels: area/documentation, area/middleware/tracing, size/S, status/3-needs-merge

#3717 Avoid a panic during Prometheus registering
  metrics/prometheus.go
  metrics/prometheus_test.go
  server/server.go
Labels: area/middleware/metrics, kind/bug/fix, size/M, status/3-needs-merge

#3724 Typo in docker-and-lets-encrypt.md
  docs/user-guide/docker-and-lets-encrypt.md
Labels: area/documentation, area/provider/docker, size/S, status/3-needs-merge

#3727 Freeze mkdocs version.
  requirements.txt
Labels: area/documentation, area/infrastructure, size/S, status/3-needs-merge

#3726 Change syntax in quick start guide
  docs/index.md
Labels: area/documentation, area/provider/docker, kind/bug/fix, size/L, status/3-needs-merge

#3734 Merge current v1.7 into master
  docs/configuration/backends/kubernetes.md
  docs/configuration/tracing.md
  docs/index.md
  docs/user-guide/docker-and-lets-encrypt.md
  metrics/prometheus.go
  metrics/prometheus_test.go
  requirements.txt
  server/server.go
Labels: area/infrastructure, bot/light-review, size/M, status/3-needs-merge

#3736 Freeze mkdocs version
  requirements.txt
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#3738 Freeze mkdocs version.
  requirements.txt
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#3712 Small code enhancements
  .golangci.toml
  cluster/datastore.go
  cmd/context.go
  cmd/traefik/traefik.go
  configuration/router/internal_router.go
  configuration/router/internal_router_test.go
  docs/configuration/acme.md
  docs/configuration/backends/ecs.md
  healthcheck/healthcheck.go
  healthcheck/healthcheck_test.go
  hostresolver/hostresolver.go
  integration/access_log_test.go
  integration/consul_catalog_test.go
  integration/etcd3_test.go
  integration/etcd_test.go
  integration/fake_dns_server.go
  integration/grpc_test.go
  integration/https_test.go
  middlewares/accesslog/logger.go
  middlewares/accesslog/logger_test.go
  middlewares/auth/forward.go
  middlewares/cbreaker.go
  middlewares/compress_test.go
  middlewares/errorpages/error_pages.go
  middlewares/errorpages/error_pages_test.go
  middlewares/headers_test.go
  middlewares/retry_test.go
  provider/acme/local_store.go
  provider/file/file.go
  provider/file/file_test.go
  provider/kubernetes/client.go
  provider/kv/kv_mock_test.go
  provider/kv/kv_test.go
  provider/marathon/builder_test.go
  provider/rancher/metadata.go
  server/server.go
  server/server_configuration.go
  server/server_loadbalancer.go
  server/server_middlewares.go
  server/server_test.go
  version/version.go
Labels: kind/enhancement, size/M, status/3-needs-merge

#3730 Typo in auth labels.
  docs/configuration/backends/docker.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/rancher.md
Labels: area/documentation, area/provider, kind/bug/fix, size/S, status/3-needs-merge

#3733 Set a keyType to ACME if the account is stored with no KeyType
  acme/acme.go
  provider/acme/provider.go
  provider/acme/provider_test.go
Labels: area/acme, kind/bug/fix, size/M, status/3-needs-merge

#3740 Set keepalive on TCP socket so idleTimeout works
  server/server.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#3747 Merge current v1.6 into v1.7
  server/server.go
Labels: area/infrastructure, size/S

#3729 Add ppc64le platform support
  script/crossbinary-others
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#3756 Update ACME documentation about TLS-ALPN challenge
  docs/configuration/acme.md
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3753 Prevent unparsable strings from being rendered in the Kubernetes template
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#3743 Don't merge kubernetes ingresses when priority is set
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#3742 Extend https redirection tests, and fix incorrect behavior
  integration/fixtures/https/https_redirect.toml
  integration/https_test.go
  middlewares/redirect/redirect.go
  middlewares/replace_path.go
  middlewares/replace_path_regex.go
  middlewares/stripPrefix.go
  middlewares/stripPrefixRegex.go
Labels: area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#3751 Avoid duplicated ACME resolution
  acme/acme.go
  acme/acme_test.go
  examples/acme/manage_acme_docker_environment.sh
  provider/acme/provider.go
  provider/acme/provider_test.go
Labels: area/acme, kind/bug/fix, size/M, status/3-needs-merge

#3788 Remove TLS in API
  integration/consul_test.go
  integration/etcd3_test.go
  integration/etcd_test.go
  integration/fixtures/file/dir/simple2.toml
  integration/try/condition.go
  integration/try/try.go
  types/types.go
Labels: area/api, kind/bug/fix, size/S, status/3-needs-merge

#3790 Docs: Adding warnings and solution about the configuration exposure
  docs/configuration/api.md
  docs/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3794 A tiny rewording on the documentation API's page
  docs/configuration/api.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3793 Prepare Release v1.6.6
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3797 Improve the wording in the documentation for Docker and fix title for Docker User Guide
  docs/configuration/backends/docker.md
  docs/user-guide/docker-and-lets-encrypt.md
Labels: area/documentation, area/provider/docker, kind/enhancement, size/S

#3798 Add vulnerability form
  docs/index.md
  mkdocs.yml
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3795 Mention docker-compose as a requirement in the let's encrypt guide
  docs/user-guide/docker-and-lets-encrypt.md
Labels: area/provider/docker, size/S, status/3-needs-merge

#3800 Fixes bad palette in doc
  mkdocs.yml
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#3802 Merge v1.6.6 into v1.7
  CHANGELOG.md
  Gopkg.lock
  acme/acme.go
  acme/acme_test.go
  docs/configuration/api.md
  docs/index.md
  docs/user-guide/docker-and-lets-encrypt.md
  examples/acme/manage_acme_docker_environment.sh
  mkdocs.yml
  provider/acme/provider.go
  provider/acme/provider_test.go
  vendor/github.com/vulcand/oxy/forward/fwd.go
  vendor/github.com/vulcand/oxy/utils/handler.go
Labels: size/M

#3804 Auth Forward with certificates in templates.
  autogen/gentemplates/gen.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/kubernetes.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
Labels: area/authentication, area/provider/consulcatalog, area/provider/docker, area/provider/ecs, area/provider/k8s, area/provider/kv, area/provider/marathon, area/provider/mesos, area/provider/rancher, kind/bug/fix, size/S

#3805 Add security mailinglist
  README.md
  docs/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3779 Include missing key in error message for KV store
  cluster/datastore.go
Labels: area/provider/kv, kind/bug/fix, size/S

#3807 Update kubernetes docs to reflect https options
  docs/configuration/backends/kubernetes.md
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#3799 Remove unnecessary loop
  provider/kubernetes/kubernetes.go
Labels: area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#3815 Rename traefikproxy twitter account into traefik
  README.md
  docs/index.md
  mkdocs.yml
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3816 Merge v1.6 into v1.7
  README.md
  docs/index.md
  mkdocs.yml
Labels: size/S

#3811 Fix documentation for route53 acme provider
  docs/configuration/acme.md
Labels: area/acme, area/documentation, size/S, status/3-needs-merge

#3817 Add segment support for ECS
  autogen/gentemplates/gen.go
  docs/configuration/backends/ecs.md
  provider/ecs/builder_test.go
  provider/ecs/config.go
  provider/ecs/config_segment_test.go
  provider/ecs/config_test.go
  provider/ecs/deprecated_config.go
  provider/ecs/ecs.go
  templates/ecs.tmpl
Labels: area/provider/ecs, kind/enhancement, size/L, status/3-needs-merge

#3796 multiple frontends for consulcatalog
  docs/configuration/backends/consulcatalog.md
  integration/consul_catalog_test.go
  provider/consulcatalog/config.go
  provider/consulcatalog/config_test.go
  provider/consulcatalog/consul_catalog.go
Labels: area/provider/consulcatalog, kind/enhancement, size/M, status/3-needs-merge

#3824 Handle Te header when http2
  Gopkg.lock
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_read.go
  vendor/github.com/gorilla/websocket/conn_read_legacy.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/vulcand/oxy/forward/fwd.go
  vendor/github.com/vulcand/oxy/forward/post_config.go
  vendor/github.com/vulcand/oxy/forward/post_config_18.go
  vendor/github.com/vulcand/oxy/forward/rewrite.go
Labels: area/oxy, bot/light-review, size/S, status/3-needs-merge

#3826 Pass the TLS Cert infos in headers
  anonymize/anonymize_config_test.go
  autogen/gentemplates/gen.go
  cmd/bug/bug_test.go
  cmd/traefik/traefik.go
  configuration/configuration.go
  configuration/entrypoints.go
  configuration/entrypoints_test.go
  docs/basics.md
  docs/configuration/backends/consulcatalog.md
  docs/configuration/backends/docker.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/file.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/mesos.md
  docs/configuration/backends/rancher.md
  docs/user-guide/examples.md
  integration/fixtures/tlsclientheaders/root.pem
  integration/fixtures/tlsclientheaders/server.key
  integration/fixtures/tlsclientheaders/server.pem
  integration/fixtures/tlsclientheaders/simple.toml
  integration/integration_test.go
  integration/resources/compose/tlsclientheaders.yml
  integration/tls_client_headers_test.go
  middlewares/tlsClientHeaders.go
  middlewares/tlsClientHeaders_test.go
  provider/consulcatalog/config.go
  provider/consulcatalog/config_test.go
  provider/docker/config.go
  provider/docker/config_container_docker_test.go
  provider/docker/config_container_swarm_test.go
  provider/docker/config_segment_test.go
  provider/ecs/config.go
  provider/ecs/config_segment_test.go
  provider/ecs/config_test.go
  provider/kv/keynames.go
  provider/kv/kv_config.go
  provider/kv/kv_config_test.go
  provider/label/names.go
  provider/label/partial.go
  provider/label/partial_test.go
  provider/marathon/config.go
  provider/marathon/config_test.go
  provider/mesos/config.go
  provider/mesos/config_test.go
  provider/rancher/config.go
  provider/rancher/config_test.go
  server/server.go
  server/server_loadbalancer.go
  server/server_middlewares.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
  tls/tls.go
  types/types.go
Labels: area/middleware, area/provider/consulcatalog, area/provider/docker, area/provider/ecs, area/provider/kv, area/provider/marathon, area/provider/mesos, area/provider/rancher, size/L, status/3-needs-merge

#3825 Enable retry on websocket
  integration/retry_test.go
  middlewares/retry.go
  middlewares/retry_test.go
Labels: area/middleware, area/websocket, size/S, status/3-needs-merge
