Repository traefik/traefik, pull requests merged in 2018-09, with the labels that each got.

#3844 StoreConfig always initializes the account if it is missing
  cmd/storeconfig/storeconfig.go
Labels: area/acme, area/cluster, kind/bug/fix, size/S, status/3-needs-merge

#3850 Remove a dead link.
  docs/configuration/api.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#3848 Allow Træfik to know if a Host rule is malformed
  provider/acme/provider.go
  rules/rules.go
  rules/rules_test.go
  server/server.go
Labels: area/rules, kind/bug/fix, size/S, status/3-needs-merge

#3856 Update go version
  CONTRIBUTING.md
  Gopkg.lock
  anonymize/anonymize_config_test.go
  build.Dockerfile
  cmd/bug/bug.go
  cmd/healthcheck/healthcheck.go
  configuration/entrypoints_test.go
  healthcheck/healthcheck.go
  middlewares/accesslog/logger_test.go
  middlewares/ip_whitelister.go
  middlewares/retry.go
  provider/ecs/ecs.go
  provider/kubernetes/kubernetes_test.go
  provider/mesos/mesos.go
  provider/rancher/config_test.go
  provider/rancher/deprecated_config_test.go
  provider/rancher/metadata.go
  vendor/github.com/vulcand/oxy/buffer/buffer.go
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#3863 Merge current v1.6 into v1.7
  provider/acme/provider.go
  rules/rules.go
  rules/rules_test.go
  server/server_configuration.go
Labels: area/infrastructure, size/S

#3864 Prepare release v1.7.0-rc4
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3878 Fix tracing duplicated headers
  middlewares/tracing/carrier.go
  middlewares/tracing/entrypoint.go
  middlewares/tracing/tracing.go
Labels: area/middleware, area/middleware/tracing, kind/bug/fix, size/S, status/3-needs-merge

#3885 Add missing quotes around backendName in kv template
  autogen/gentemplates/gen.go
  templates/kv.tmpl
Labels: area/provider/kv, kind/bug/fix, size/S, status/3-needs-merge

#3889 Add interface to Træfik logger
  log/logger.go
Labels: area/logs, kind/bug/fix, size/S, status/3-needs-merge

#3895 Update lego
  Gopkg.lock
  docs/configuration/acme.md
  vendor/github.com/xenolf/lego/acme/dns_challenge.go
  vendor/github.com/xenolf/lego/platform/config/env/env.go
  vendor/github.com/xenolf/lego/providers/dns/alidns/alidns.go
  vendor/github.com/xenolf/lego/providers/dns/auroradns/auroradns.go
  vendor/github.com/xenolf/lego/providers/dns/azure/azure.go
  vendor/github.com/xenolf/lego/providers/dns/bluecat/bluecat.go
  vendor/github.com/xenolf/lego/providers/dns/bluecat/client.go
  vendor/github.com/xenolf/lego/providers/dns/cloudflare/client.go
  vendor/github.com/xenolf/lego/providers/dns/cloudflare/cloudflare.go
  vendor/github.com/xenolf/lego/providers/dns/cloudxns/client.go
  vendor/github.com/xenolf/lego/providers/dns/cloudxns/cloudxns.go
  vendor/github.com/xenolf/lego/providers/dns/digitalocean/client.go
  vendor/github.com/xenolf/lego/providers/dns/digitalocean/digitalocean.go
  vendor/github.com/xenolf/lego/providers/dns/dns_providers.go
  vendor/github.com/xenolf/lego/providers/dns/dnsimple/dnsimple.go
  vendor/github.com/xenolf/lego/providers/dns/dnsmadeeasy/client.go
  vendor/github.com/xenolf/lego/providers/dns/dnsmadeeasy/dnsmadeeasy.go
  vendor/github.com/xenolf/lego/providers/dns/dnspod/dnspod.go
  vendor/github.com/xenolf/lego/providers/dns/duckdns/duckdns.go
  vendor/github.com/xenolf/lego/providers/dns/dyn/client.go
  vendor/github.com/xenolf/lego/providers/dns/dyn/dyn.go
  vendor/github.com/xenolf/lego/providers/dns/exoscale/exoscale.go
  vendor/github.com/xenolf/lego/providers/dns/fastdns/fastdns.go
  vendor/github.com/xenolf/lego/providers/dns/gandi/client.go
  vendor/github.com/xenolf/lego/providers/dns/gandi/gandi.go
  vendor/github.com/xenolf/lego/providers/dns/gandiv5/client.go
  vendor/github.com/xenolf/lego/providers/dns/gandiv5/gandiv5.go
  vendor/github.com/xenolf/lego/providers/dns/gcloud/googlecloud.go
  vendor/github.com/xenolf/lego/providers/dns/glesys/client.go
  vendor/github.com/xenolf/lego/providers/dns/glesys/glesys.go
  vendor/github.com/xenolf/lego/providers/dns/godaddy/godaddy.go
  vendor/github.com/xenolf/lego/providers/dns/hostingde/client.go
  vendor/github.com/xenolf/lego/providers/dns/hostingde/hostingde.go
  vendor/github.com/xenolf/lego/providers/dns/iij/iij.go
  vendor/github.com/xenolf/lego/providers/dns/lightsail/lightsail.go
  vendor/github.com/xenolf/lego/providers/dns/linode/linode.go
  vendor/github.com/xenolf/lego/providers/dns/namecheap/client.go
  vendor/github.com/xenolf/lego/providers/dns/namecheap/namecheap.go
  vendor/github.com/xenolf/lego/providers/dns/namedotcom/namedotcom.go
  vendor/github.com/xenolf/lego/providers/dns/netcup/client.go
  vendor/github.com/xenolf/lego/providers/dns/netcup/netcup.go
  vendor/github.com/xenolf/lego/providers/dns/nifcloud/client.go
  vendor/github.com/xenolf/lego/providers/dns/nifcloud/nifcloud.go
  vendor/github.com/xenolf/lego/providers/dns/ns1/ns1.go
  vendor/github.com/xenolf/lego/providers/dns/otc/client.go
  vendor/github.com/xenolf/lego/providers/dns/otc/otc.go
  vendor/github.com/xenolf/lego/providers/dns/ovh/ovh.go
  vendor/github.com/xenolf/lego/providers/dns/pdns/pdns.go
  vendor/github.com/xenolf/lego/providers/dns/rackspace/client.go
  vendor/github.com/xenolf/lego/providers/dns/rackspace/rackspace.go
  vendor/github.com/xenolf/lego/providers/dns/rfc2136/rfc2136.go
  vendor/github.com/xenolf/lego/providers/dns/route53/route53.go
  vendor/github.com/xenolf/lego/providers/dns/sakuracloud/sakuracloud.go
  vendor/github.com/xenolf/lego/providers/dns/vegadns/vegadns.go
  vendor/github.com/xenolf/lego/providers/dns/vultr/vultr.go
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#3894 Fix error pages
  server/server_configuration.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#3902 Prepare release 1.7.0-rc5
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3908 Removed non-applicable default tests and fixed custom tests
  webui/src/app/app.component.spec.ts
  webui/src/app/charts/bar-chart/bar-chart.component.spec.ts
Labels: area/webui, size/S, status/3-needs-merge

#3915 Fix some DNS providers issues
  Gopkg.lock
  vendor/github.com/xenolf/lego/acme/client.go
  vendor/github.com/xenolf/lego/acme/dns_challenge.go
  vendor/github.com/xenolf/lego/log/logger.go
  vendor/github.com/xenolf/lego/providers/dns/azure/azure.go
  vendor/github.com/xenolf/lego/providers/dns/gcloud/googlecloud.go
  vendor/github.com/xenolf/lego/providers/dns/iij/iij.go
  vendor/github.com/xenolf/lego/providers/dns/ns1/ns1.go
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#3913 Fix logger in Oxy
  Gopkg.lock
  vendor/github.com/vulcand/oxy/buffer/buffer.go
  vendor/github.com/vulcand/oxy/cbreaker/fallback.go
  vendor/github.com/vulcand/oxy/forward/fwd.go
Labels: bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#3907 Do not copy hop-by-hop headers to forward auth request
  middlewares/auth/forward.go
  middlewares/auth/forward_test.go
Labels: area/authentication, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#3893 Added Dashboard table item for Rate Limits
  webui/src/app/app.module.ts
  webui/src/app/components/providers/providers.component.html
  webui/src/app/pipes/humanreadable.filter.pipe.spec.ts
  webui/src/app/pipes/humanreadable.filter.pipe.ts
  webui/src/app/services/api.service.ts
Labels: area/webui, kind/bug/fix, size/M, status/3-needs-merge

#3920 Prepare release v1.7.0
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/M, status/3-needs-merge

#3925 Merge v1.7.0 into master
  CHANGELOG.md
  Gopkg.lock
  middlewares/auth/forward.go
  middlewares/auth/forward_test.go
  vendor/github.com/vulcand/oxy/buffer/buffer.go
  vendor/github.com/vulcand/oxy/cbreaker/fallback.go
  vendor/github.com/vulcand/oxy/forward/fwd.go
  vendor/github.com/xenolf/lego/acme/client.go
  vendor/github.com/xenolf/lego/acme/dns_challenge.go
  vendor/github.com/xenolf/lego/log/logger.go
  vendor/github.com/xenolf/lego/providers/dns/azure/azure.go
  vendor/github.com/xenolf/lego/providers/dns/gcloud/googlecloud.go
  vendor/github.com/xenolf/lego/providers/dns/iij/iij.go
  vendor/github.com/xenolf/lego/providers/dns/ns1/ns1.go
  webui/src/app/app.component.spec.ts
  webui/src/app/app.module.ts
  webui/src/app/charts/bar-chart/bar-chart.component.spec.ts
  webui/src/app/components/providers/providers.component.html
  webui/src/app/pipes/humanreadable.filter.pipe.spec.ts
  webui/src/app/pipes/humanreadable.filter.pipe.ts
  webui/src/app/services/api.service.ts
Labels: bot/light-review, size/L, status/3-needs-merge

#3934 Fix TLS ALPN cluster mode.
  acme/acme.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#3923 Don't challenge ACME when host rule on another entry point
  provider/acme/provider.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#3813 Add health check timeout parameter
  autogen/gentemplates/gen.go
  cmd/configuration.go
  configuration/configuration.go
  docs/basics.md
  docs/configuration/backends/consulcatalog.md
  docs/configuration/backends/docker.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/file.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/mesos.md
  docs/configuration/backends/rancher.md
  docs/configuration/backends/servicefabric.md
  docs/configuration/commons.md
  docs/user-guide/marathon.md
  healthcheck/healthcheck.go
  healthcheck/healthcheck_test.go
  integration/consul_catalog_test.go
  integration/fixtures/healthcheck/multiple-entrypoints-drr.toml
  integration/fixtures/healthcheck/multiple-entrypoints-wrr.toml
  integration/fixtures/healthcheck/port_overload.toml
  integration/fixtures/healthcheck/simple.toml
  provider/consulcatalog/config_test.go
  provider/docker/config_container_docker_test.go
  provider/docker/config_container_swarm_test.go
  provider/ecs/config_test.go
  provider/kv/keynames.go
  provider/kv/kv_config.go
  provider/kv/kv_config_test.go
  provider/label/names.go
  provider/label/partial.go
  provider/label/partial_test.go
  provider/marathon/config_test.go
  provider/mesos/config_test.go
  provider/rancher/config_test.go
  server/server_configuration_test.go
  server/server_loadbalancer.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
  types/types.go
  webui/src/app/components/providers/providers.component.html
Labels: area/provider/consulcatalog, area/provider/docker, area/provider/ecs, area/provider/kv, area/provider/marathon, area/provider/mesos, area/provider/rancher, kind/enhancement, size/L, status/3-needs-merge

#3946 Don't remove static certs from config when cluster mode
  server/server.go
Labels: area/acme, area/cluster, kind/bug/fix, size/S, status/3-needs-merge

#3948 Use the first static certificate as a fallback when no default is given
  configuration/configuration.go
  integration/etcd_test.go
  server/server_configuration.go
Labels: area/tls, kind/bug/fix, size/S, status/3-needs-merge

#3952 Prepare release v1.7.1
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge
