Repository traefik/traefik, pull requests merged in 2018-03, with the labels that each got.

#2951 Separate command from the main package
  anonymize/anonymize.go
  anonymize/anonymize_config_test.go
  anonymize/anonymize_doOnJSON_test.go
  anonymize/anonymize_doOnStruct_test.go
  cmd/bug/bug.go
  cmd/bug/bug_test.go
  cmd/configuration.go
  cmd/healthcheck/healthcheck.go
  cmd/storeconfig/storeconfig.go
  cmd/traefik/traefik.go
  cmd/version/version.go
  collector/collector.go
Labels: kind/enhancement, size/S, status/3-needs-merge

#2950 Enhance API, REST, ping documentation.
  docs/configuration/api.md
  docs/configuration/backends/rest.md
  docs/configuration/backends/web.md
  docs/configuration/ping.md
  docs/user-guide/examples.md
Labels: area/api, area/documentation, kind/enhancement, size/M, status/3-needs-merge

#2946 Use responseModifier to override secure headers
  Gopkg.lock
  Gopkg.toml
  server/server.go
  server/server_test.go
  vendor/github.com/unrolled/secure/csp.go
  vendor/github.com/unrolled/secure/secure.go
Labels: area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#2960 fix: gh-pages drop edge.
  .travis.yml
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#2958 New option in secure middleware
  autogen/gentemplates/gen.go
  docs/configuration/backends/consulcatalog.md
  docs/configuration/backends/docker.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/kubernetes.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/mesos.md
  docs/configuration/backends/rancher.md
  middlewares/secure.go
  provider/consulcatalog/consul_catalog_config.go
  provider/consulcatalog/consul_catalog_config_test.go
  provider/docker/config_container.go
  provider/docker/config_container_docker_test.go
  provider/docker/config_container_swarm_test.go
  provider/docker/config_service.go
  provider/docker/config_service_test.go
  provider/ecs/config.go
  provider/ecs/config_test.go
  provider/kubernetes/annotations.go
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
  provider/kv/keynames.go
  provider/kv/kv_config.go
  provider/kv/kv_config_test.go
  provider/label/names.go
  provider/marathon/config.go
  provider/marathon/config_test.go
  provider/mesos/config.go
  provider/mesos/config_test.go
  provider/rancher/config.go
  provider/rancher/config_test.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/kubernetes.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
  types/types.go
Labels: area/middleware, area/provider/consul, area/provider/consulcatalog, area/provider/docker, area/provider/ecs, area/provider/k8s, area/provider/marathon, area/provider/mesos, area/provider/rancher, kind/enhancement, size/M, status/3-needs-merge

#2959 Clarify some deprecations.
  docs/configuration/acme.md
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#2970 Check all the C/N and SANs of provided certificates before generating ACME certificates in ACME provider
  acme/acme.go
  anonymize/anonymize_config_test.go
  cmd/traefik/traefik.go
  integration/https_test.go
  provider/acme/provider.go
  server/server.go
  tls/certificate.go
  tls/tls.go
  types/types.go
Labels: area/acme, kind/bug/fix, size/M, status/3-needs-merge

#2971 Delete TLS-SNI-01 challenge from ACME
  acme/acme.go
  acme/challenge_tls_provider.go
  docs/configuration/acme.md
  docs/user-guide/cluster-docker-consul.md
  integration/acme_test.go
  integration/fixtures/acme/no_challenge_acme.toml
  provider/acme/challenge.go
  provider/acme/provider.go
Labels: area/acme, kind/enhancement, size/M, status/3-needs-merge

#2975 capitalize Sec-WebSocket-Protocol Header
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
Labels: area/websocket, kind/bug/fix, size/S, status/3-needs-merge

#2972 Replace Delay by RefreshSecond in Eureka
  anonymize/anonymize_config_test.go
  cmd/configuration.go
  configuration/configuration.go
  docs/configuration/backends/eureka.md
  provider/eureka/eureka.go
Labels: area/provider/eureka, kind/enhancement, size/S, status/3-needs-merge

#2980 Unable to generate documentation
  .travis.yml
  requirements.txt
Labels: area/documentation, area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#2973 Add some missing quotes in templates
  autogen/gentemplates/gen.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/eureka.tmpl
  templates/kubernetes.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
Labels: area/provider, kind/bug/fix, size/M, status/3-needs-merge

#2982 Merge current v1.5 into master
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  requirements.txt
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
Labels: area/infrastructure, size/S

#2983 Safe access to ECS API pointer values.
  provider/ecs/ecs.go
Labels: area/provider/ecs, kind/bug/fix, size/S, status/3-needs-merge

#2981 Propagate insecure in white list.
  whitelist/ip.go
  whitelist/ip_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#2987 Merge current v1.5 into master
  provider/ecs/config.go
  provider/ecs/ecs.go
  whitelist/ip.go
  whitelist/ip_test.go
Labels: area/infrastructure, size/S

#2992 Added entrypoint metrics to influxdb
  metrics/influxdb.go
  metrics/influxdb_test.go
Labels: area/middleware/metrics, kind/enhancement, size/S

#2996 Enhance Traefik TOML sample.
  examples/accessLog/traefik.ab.toml
  examples/accessLog/traefik.example.toml
  examples/acme/acme.toml
  examples/compose-rancher.yml
  examples/compose-traefik.yml
  examples/k8s/traefik-deployment.yaml
  examples/k8s/traefik-ds.yaml
  integration/fixtures/acme/acme_http01.toml
  integration/fixtures/acme/acme_http01_web.toml
  integration/fixtures/acme/certificates.toml
  traefik.sample.toml
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#2984 Clarify how setting a frontend priority works
  docs/basics.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#3004 Handle quoted strings in UnmarshalJSON
  Gopkg.lock
  vendor/github.com/containous/flaeg/parse/parse.go
Labels: bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#3000 Updated the test-it example according to the latest docker version
  docs/index.md
Labels: area/documentation, size/S, status/3-needs-merge

#3006 Merge current v1.5 into master
  Gopkg.lock
  docs/basics.md
  docs/index.md
  docs/user-guide/examples.md
  examples/accessLog/traefik.ab.toml
  examples/accessLog/traefik.example.toml
  examples/acme/acme.toml
  integration/fixtures/acme/acme_http01.toml
  integration/fixtures/acme/acme_http01_web.toml
  integration/fixtures/acme/certificates.toml
  traefik.sample.toml
  vendor/github.com/containous/flaeg/parse/parse.go
Labels: size/S

#3007 Use context in Server
  cmd/context.go
  cmd/traefik/traefik.go
  server/server.go
  server/server_signals.go
  server/server_signals_windows.go
Labels: kind/enhancement, size/S, status/3-needs-merge

#2988 Ultimate Access log filter
  Gopkg.lock
  Gopkg.toml
  cmd/configuration.go
  cmd/traefik/traefik.go
  docs/configuration/commons.md
  docs/configuration/logs.md
  integration/access_log_test.go
  middlewares/accesslog/logdata.go
  middlewares/accesslog/logger.go
  middlewares/accesslog/logger_formatters.go
  middlewares/accesslog/logger_formatters_test.go
  middlewares/accesslog/logger_test.go
  middlewares/accesslog/parser.go
  middlewares/accesslog/parser_test.go
  middlewares/error_pages.go
  mkdocs.yml
  types/logs.go
  types/logs_test.go
  types/types.go
  types/types_test.go
  vendor/github.com/mattn/go-shellwords/LICENSE
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
Labels: area/logs, area/middleware, kind/enhancement, size/L, status/3-needs-merge

#3016 Add [file] in syntax reference
  docs/configuration/backends/file.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#3015 Add lower-case passHostHeader key support.
  autogen/gentemplates/gen.go
  docs/user-guide/kv-config.md
  templates/kv.tmpl
Labels: area/provider/kv, kind/bug/fix, size/S, status/3-needs-merge

#3013 Use goroutine pool in throttleProvider
  server/server.go
  server/server_test.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#2962 Fix Rancher Healthcheck when upgrading a service
  provider/rancher/rancher.go
Labels: area/provider/rancher, kind/bug/fix, size/S, status/3-needs-merge

#3012 Add TLS Docs
  docs/configuration/backends/kubernetes.md
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#3022 Prepare release v1.5.4
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3024 Merge v1.5.4 into master
  CHANGELOG.md
  docs/configuration/backends/file.md
  docs/configuration/backends/kubernetes.md
  docs/user-guide/kv-config.md
  provider/kv/keynames.go
  provider/kv/kv_config.go
  provider/rancher/config.go
  provider/rancher/rancher.go
  server/server.go
  server/server_test.go
Labels: bot/light-review, size/S, status/3-needs-merge

#3037 Set INFO log level in Kubernetes guide and examples.
  docs/user-guide/kubernetes.md
  examples/k8s/traefik-deployment.yaml
  examples/k8s/traefik-ds.yaml
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#3051 Fix link to InsecureSkipVerify option.
  docs/configuration/backends/kubernetes.md
Labels: area/documentation, area/provider/k8s, kind/bug/confirmed, size/S, status/3-needs-merge

#3033 Add SF to supported backends in docs
  docs/index.md
Labels: area/documentation, area/provider/servicefabric, size/S, status/3-needs-merge

#3036 Fix goroutine leak in consulcatalog when consul is down
  provider/consul/consul_catalog.go
Labels: area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#3050 Allow overriding the log level in debug mode.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bugs.md
  cmd/bug/bug.go
  cmd/configuration.go
  cmd/traefik/traefik.go
  configuration/configuration.go
  docs/configuration/commons.md
Labels: area/logs, kind/enhancement, size/S, status/3-needs-merge

#3057 Dependency fsnotify organization has been renamed
  Gopkg.lock
  Gopkg.toml
Labels: kind/bug/fix, size/S, status/3-needs-merge

#3041 Miss-leading Docker backend documentation
  docs/configuration/backends/docker.md
Labels: area/provider/docker, kind/enhancement, size/S, status/3-needs-merge

#3048 Introduction update
  README.md
  docs/index.md
  examples/quickstart/README.md
  examples/quickstart/docker-compose.yml
Labels: area/documentation, kind/enhancement, size/L, status/3-needs-merge

#3067 Merge current v1.5 into master
  README.md
  docs/configuration/backends/docker.md
  docs/index.md
  examples/quickstart/README.md
  examples/quickstart/docker-compose.yml
Labels: area/infrastructure, size/L

#2991 Added support for templates to file provider
  configuration/configuration.go
  configuration/configuration_test.go
  provider/file/file.go
  provider/file/file_test.go
  provider/provider.go
Labels: area/provider/file, kind/enhancement, size/S, status/3-needs-merge

#3028 Drop capabilities in Kubernetes DaemonSet example
  docs/user-guide/kubernetes.md
  examples/k8s/traefik-ds.yaml
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#3065 Remove non-supported label.
  docs/configuration/backends/consulcatalog.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/mesos.md
  docs/configuration/backends/rancher.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#3064 Update Service Fabric backend.
  Gopkg.lock
  Gopkg.toml
  docs/configuration/backends/servicefabric.md
  vendor/github.com/containous/traefik-extra-service-fabric/labels.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_config.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_labelfuncs.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
  vendor/github.com/containous/traefik-extra-service-fabric/types.go
  vendor/github.com/jjcollinge/servicefabric/servicefabric.go
Labels: area/provider/servicefabric, kind/enhancement, size/S

#3009 Added cluster/leader endpoint
  cluster/leadership.go
  docs/configuration/api.md
  server/server.go
Labels: area/api, area/cluster, size/S, status/3-needs-merge

#3062 Toggle /ping to artificially return unhealthy response on SIGTERM during requestAcceptGraceTimeout interval
  docs/configuration/ping.md
  integration/basic_test.go
  integration/fixtures/reqacceptgrace.toml
  ping/ping.go
  server/server.go
Labels: area/healthcheck, kind/enhancement, size/S

#3042 add access log filter for retry attempts
  docs/configuration/logs.md
  middlewares/accesslog/logger.go
  middlewares/accesslog/logger_test.go
  types/logs.go
  types/types.go
  types/types_test.go
Labels: area/logs, area/middleware, kind/enhancement, size/M, status/3-needs-merge

#3070 Ability to use "X-Forwarded-For" as a source of IP for white list.
  autogen/gentemplates/gen.go
  configuration/configuration.go
  configuration/entrypoints.go
  configuration/entrypoints_test.go
  docs/configuration/backends/consulcatalog.md
  docs/configuration/backends/docker.md
  docs/configuration/backends/ecs.md
  docs/configuration/backends/file.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/mesos.md
  docs/configuration/backends/rancher.md
  docs/configuration/entrypoints.md
  middlewares/ip_whitelister.go
  provider/consulcatalog/consul_catalog_config.go
  provider/consulcatalog/consul_catalog_config_test.go
  provider/docker/config.go
  provider/docker/config_container_docker_test.go
  provider/docker/config_container_swarm_test.go
  provider/docker/config_segment_test.go
  provider/docker/deprecated_config.go
  provider/ecs/config.go
  provider/ecs/config_test.go
  provider/kubernetes/annotations.go
  provider/kubernetes/builder_configuration_test.go
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
  provider/kv/keynames.go
  provider/kv/kv_config.go
  provider/kv/kv_config_test.go
  provider/label/names.go
  provider/marathon/config.go
  provider/marathon/config_test.go
  provider/mesos/config.go
  provider/mesos/config_test.go
  provider/rancher/config.go
  provider/rancher/config_test.go
  server/header_rewriter.go
  server/server.go
  server/server_test.go
  templates/consul_catalog.tmpl
  templates/docker.tmpl
  templates/ecs.tmpl
  templates/kubernetes.tmpl
  templates/kv.tmpl
  templates/marathon.tmpl
  templates/mesos.tmpl
  templates/rancher.tmpl
  types/types.go
  whitelist/ip.go
  whitelist/ip_test.go
Labels: area/middleware, area/provider/consulcatalog, area/provider/docker, area/provider/ecs, area/provider/k8s, area/provider/kv, area/provider/marathon, area/provider/mesos, area/provider/rancher, kind/enhancement, size/L, status/3-needs-merge

#3073 Segments Labels: Rancher & Marathon
  autogen/gentemplates/gen.go
  configuration/configuration.go
  docs/configuration/backends/docker.md
  docs/configuration/backends/marathon.md
  docs/configuration/backends/rancher.md
  provider/docker/config.go
  provider/docker/config_container_docker_test.go
  provider/label/label.go
  provider/label/label_test.go
  provider/label/partial.go
  provider/label/partial_test.go
  provider/label/segment_test.go
  provider/marathon/builder_test.go
  provider/marathon/config.go
  provider/marathon/config_root.go
  provider/marathon/config_test.go
  provider/marathon/convert_types.go
  provider/marathon/deprecated_config.go
  provider/marathon/deprecated_config_test.go
  provider/marathon/fake_client_test.go
  provider/marathon/marathon.go
  provider/rancher/config.go
  provider/rancher/config_root.go
  provider/rancher/config_test.go
  provider/rancher/deprecated_config.go
  provider/rancher/deprecated_config_test.go
  provider/rancher/rancher.go
  templates/marathon-v1.tmpl
  templates/marathon.tmpl
  templates/rancher-v1.tmpl
  templates/rancher.tmpl
Labels: area/provider/docker, area/provider/marathon, area/provider/rancher, kind/enhancement, size/L, status/3-needs-merge

#3078 Prepare release 1.6.0-rc1
  .semaphoreci/vars
  .travis.yml
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/M, status/3-needs-merge

#3084 Fix panic with wrong ACME configuration
  configuration/configuration.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#3086 Fix basic documentation
  docs/basics.md
  docs/configuration/entrypoints.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#3080 Add wildcard match to acme domains
  acme/account.go
  acme/acme.go
  acme/acme_test.go
  provider/acme/provider.go
  server/server.go
  types/domain_test.go
  types/domains.go
Labels: area/acme, kind/bug/fix, status/3-needs-merge

#3087 Prepare release v1.6.0-rc2
  CHANGELOG.md
Labels: area/documentation, size/S

#3091 Frontend rule and segment labels.
  autogen/gentemplates/gen.go
  provider/docker/config.go
  provider/docker/config_container_docker_test.go
  provider/docker/config_container_swarm_test.go
  provider/label/segment.go
  provider/rancher/config.go
  provider/rancher/config_test.go
  provider/rancher/deprecated_config.go
  provider/rancher/deprecated_config_test.go
  templates/docker.tmpl
  templates/rancher.tmpl
Labels: area/provider/rancher, kind/bug/fix, size/S, status/3-needs-merge

#3096 Prepare release v1.6.0-rc3.
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#3102 Fixed documentation urls on README.md
  README.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge
