Repository traefik/traefik, pull requests merged in 2019-12, with the labels that each got.

#5840 Do not give responsewriter or its headers to asynchronous logging goroutine
  pkg/middlewares/accesslog/logdata.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
Labels: area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5920 Fix extraction for zipkin tracing
  go.mod
  go.sum
  pkg/middlewares/tracing/entrypoint.go
  pkg/tracing/carrier.go
  pkg/tracing/tracing.go
Labels: area/middleware/tracing, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5923 Add custom help function to command
  pkg/cli/commands.go
  pkg/cli/commands_test.go
  pkg/cli/loader_file.go
Labels: area/cli, size/M, status/3-needs-merge

#5927 Prepare release v2.0.6
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5928 Merge current v2.0 branch into v2.1
  CHANGELOG.md
  cmd/healthcheck/healthcheck.go
  docs/content/getting-started/install-traefik.md
  docs/content/https/acme.md
  docs/content/https/ref-acme.txt
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/observability/logs.md
  docs/content/observability/metrics/datadog.md
  docs/content/observability/metrics/influxdb.md
  docs/content/observability/metrics/prometheus.md
  docs/content/observability/metrics/statsd.md
  docs/content/observability/tracing/datadog.md
  docs/content/observability/tracing/haystack.md
  docs/content/observability/tracing/instana.md
  docs/content/observability/tracing/jaeger.md
  docs/content/observability/tracing/overview.md
  docs/content/observability/tracing/zipkin.md
  docs/content/operations/ping.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/marathon.md
  docs/content/providers/rancher.md
  docs/content/providers/rancher.txt
  docs/content/providers/rancher.yml
  docs/content/routing/entrypoints.md
  docs/content/routing/overview.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
  docs/content/user-guides/grpc.md
  go.mod
  go.sum
  integration/fixtures/healthcheck/multiple-routers-one-same-service.toml
  integration/healthcheck_test.go
  pkg/healthcheck/healthcheck.go
  pkg/middlewares/accesslog/logdata.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/headers_test.go
  pkg/middlewares/tracing/entrypoint.go
  pkg/provider/rancher/rancher.go
  pkg/server/service/service.go
  pkg/tracing/carrier.go
  pkg/tracing/tracing.go
  webui/src/_services/HttpService.js
  webui/src/_services/TcpService.js
  webui/src/components/_commons/PanelRouterDetails.vue
  webui/src/components/_commons/PanelServiceDetails.vue
Labels: size/L

#5929 Prepare release v2.1.0-rc3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5930 Upgrade python version to 3.7 for netlify
  docs/runtime.txt
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#5931 Merge current v2.0 branch into v2.1
  docs/runtime.txt
Labels: bot/light-review, size/S, status/3-needs-merge

#5937 fix: debug endpoint when insecure API.
  pkg/provider/traefik/fixtures/full_configuration.json
  pkg/provider/traefik/internal.go
  pkg/provider/traefik/internal_test.go
Labels: area/api, kind/bug/fix, size/S, status/3-needs-merge

#5935 Do not stop to listen on tcp listeners on temporary errors
  pkg/server/server_entrypoint_tcp.go
  pkg/tls/certificate.go
Labels: area/server, kind/bug/fix, size/S, status/3-needs-merge

#5945 readme: Fix link to file backend/provider documentation
  README.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5949 Fix Docker example in "Strip and Rewrite Path Prefixes" in migration guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5902 Document LE caveats with Kubernetes on v2
  docs/content/https/acme.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
Labels: area/acme, area/documentation, area/provider/k8s/crd, area/provider/k8s/ingress, size/M, status/3-needs-merge

#5964 The Cloudflare hint for the GLOBAL API KEY for CF MAIL/API_KEY
  docs/content/https/acme.md
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5939 Improve documentation on file provider limitations with file system notifications
  docs/content/migration/v1-to-v2.md
  docs/content/providers/file.md
  docs/content/routing/overview.md
  docs/content/user-guides/grpc.md
Labels: area/documentation, area/provider/file, kind/enhancement, size/S, status/3-needs-merge

#5941 Truncate key for identification in log
  acme/account.go
  provider/acme/account.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#5921 fix: PassClientTLSCert middleware separators and formatting
  docs/content/middlewares/passtlsclientcert.md
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
Labels: area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#5963 Make trailing slash more prominent for the "secure dashboard setup" too
  docs/content/operations/dashboard.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5967 Remove mirroring impact in accesslog
  pkg/server/service/loadbalancer/mirror/mirror.go
Labels: area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5960 fix: remove double call to server Close.
  cmd/traefik/traefik.go
  pkg/server/configurationwatcher.go
  pkg/server/server.go
Labels: area/server, kind/bug/fix, size/S, status/3-needs-merge

#5971 fix: flaky Travis builds due to 'not get uid/gid'
  docs/check.Dockerfile
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5819 Improve documentation for ACME/Let's Encrypt
  docs/content/https/.markdownlint.json
  docs/content/https/acme.md
  docs/content/https/include-acme-multiple-domains-example.md
  docs/content/https/include-acme-multiple-domains-from-rule-example.md
  docs/content/https/include-acme-single-domain-example.md
  docs/content/index.md
  docs/content/routing/providers/marathon.md
  docs/mkdocs.yml
Labels: area/acme, area/documentation, size/L, status/3-needs-merge

#5976 Prepare release v2.0.7
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5977 Merge current v2.0 branch into v2.1
  CHANGELOG.md
  README.md
  docs/check.Dockerfile
  docs/content/https/.markdownlint.json
  docs/content/https/acme.md
  docs/content/https/include-acme-multiple-domains-example.md
  docs/content/https/include-acme-multiple-domains-from-rule-example.md
  docs/content/https/include-acme-single-domain-example.md
  docs/content/index.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/migration/v1-to-v2.md
  docs/content/operations/dashboard.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/overview.md
  docs/content/routing/providers/marathon.md
  docs/content/user-guides/grpc.md
  docs/mkdocs.yml
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/tls/certificate.go
Labels: size/L

#5983 Fix weighted service provider icon
  webui/src/components/_commons/PanelMirroringServices.vue
  webui/src/components/_commons/PanelWeightedServices.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#5984 Use valid condition in the service details panel UI
  webui/src/components/_commons/PanelServiceDetails.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#5987 Several documentation fixes
  docs/content/operations/ping.md
  docs/content/routing/services/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5986 Fix http/tcp resources pagination
  webui/src/_services/HttpService.js
  webui/src/_services/TcpService.js
  webui/src/_services/utils.js
  webui/src/index.template.html
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#5989 Prepare release v1.7.20
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5985 detect CloseNotify capability in accesslog and metrics
  pkg/middlewares/accesslog/capture_response_writer.go
  pkg/middlewares/accesslog/field_middleware.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/metrics/metrics.go
  pkg/middlewares/metrics/recorder.go
Labels: area/logs, area/middleware, area/middleware/metrics, kind/bug/fix, size/S, status/3-needs-merge

#6002 Prepare release v2.1.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#6004 Merge current v2.1 branch into master
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  cmd/traefik/traefik.go
  docs/check.Dockerfile
  docs/content/https/.markdownlint.json
  docs/content/https/acme.md
  docs/content/https/include-acme-multiple-domains-example.md
  docs/content/https/include-acme-multiple-domains-from-rule-example.md
  docs/content/https/include-acme-single-domain-example.md
  docs/content/index.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/migration/v1-to-v2.md
  docs/content/operations/dashboard.md
  docs/content/operations/ping.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/overview.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/services/index.md
  docs/content/user-guides/grpc.md
  docs/mkdocs.yml
  pkg/middlewares/accesslog/capture_response_writer.go
  pkg/middlewares/accesslog/field_middleware.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/metrics/metrics.go
  pkg/middlewares/metrics/recorder.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
  pkg/provider/traefik/fixtures/full_configuration.json
  pkg/provider/traefik/internal.go
  pkg/provider/traefik/internal_test.go
  pkg/server/configurationwatcher.go
  pkg/server/server.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/tls/certificate.go
  webui/src/_services/HttpService.js
  webui/src/_services/TcpService.js
  webui/src/_services/utils.js
  webui/src/components/_commons/PanelMirroringServices.vue
  webui/src/components/_commons/PanelServiceDetails.vue
  webui/src/components/_commons/PanelWeightedServices.vue
Labels: size/L

#5910 Web UI: Take off logic from generic table component
  webui/package-lock.json
  webui/package.json
  webui/src/_mixins/GetTableProps.js
  webui/src/components/_commons/Chips.vue
  webui/src/components/_commons/MainTable.vue
  webui/src/components/_commons/ProviderIcon.vue
  webui/src/pages/_commons/MiddlewareDetail.vue
  webui/src/pages/_commons/ServiceDetail.vue
  webui/src/pages/http/Middlewares.vue
  webui/src/pages/http/Routers.vue
  webui/src/pages/http/Services.vue
  webui/src/pages/tcp/Routers.vue
  webui/src/pages/tcp/Services.vue
Labels: area/webui, kind/enhancement, size/L, status/3-needs-merge

#5915 Add serial number certificate to forward headers
  docs/content/middlewares/passtlsclientcert.md
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  pkg/config/dynamic/middlewares.go
  pkg/config/label/label_test.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
Labels: area/middleware, kind/enhancement, size/L, status/3-needs-merge

#6010 CloseNotifier: return pointer instead of value
  pkg/middlewares/accesslog/capture_response_writer.go
  pkg/middlewares/accesslog/capture_response_writer_test.go
  pkg/middlewares/metrics/metrics_test.go
  pkg/middlewares/metrics/recorder.go
Labels: area/logs, area/middleware, area/middleware/metrics, kind/bug/fix, size/M, status/3-needs-merge

#6016 Improve documentation about Traefik build.
  docs/content/contributing/building-testing.md
Labels: area/documentation, area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#6017 Add Migration Guide for Traefik v2.1
  docs/content/migration/v2.md
  docs/mkdocs.yml
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#5950 chore: update some dependencies
  docs/content/migration/v1-to-v2.md
  go.mod
  go.sum
  integration/consul_catalog_test.go
  pkg/tracing/jaeger/jaeger.go
Labels: area/infrastructure, area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#6021 Prepare release v2.1.1
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#6022 add a documentation example for dashboard and api for kubernetes CRD
  docs/content/operations/include-api-examples.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#6019 Use consistent name in ACME documentation
  docs/content/https/acme.md
  docs/content/https/include-acme-multiple-domains-from-rule-example.md
  docs/content/https/include-acme-single-domain-example.md
  docs/content/https/ref-acme.toml
  docs/content/https/ref-acme.txt
  docs/content/https/ref-acme.yaml
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#6037 Added ExternalName https support for Kubernetes CRD, as done in v2.0
  pkg/provider/kubernetes/crd/kubernetes_http.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#6051 doc: remove section about templates
  docs/content/contributing/building-testing.md
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#5909 Web UI: Polling on tables
  webui/.eslintrc.js
  webui/package-lock.json
  webui/package.json
  webui/quasar.conf.js
  webui/src/_helpers/Errors.js
  webui/src/_helpers/Helps.js
  webui/src/_helpers/Mutations.js
  webui/src/_mixins/Pagination.js
  webui/src/boot/lodash.js
  webui/src/components/_commons/ChartDoughnut.vue
  webui/src/components/dashboard/PanelFeature.vue
  webui/src/pages/http/Middlewares.vue
  webui/src/pages/http/Routers.vue
  webui/src/pages/http/Services.vue
  webui/src/pages/tcp/Routers.vue
  webui/src/pages/tcp/Services.vue
  webui/src/store/http/mutations.js
  webui/src/store/http/mutations.spec.js
  webui/src/store/tcp/mutations.js
  webui/src/store/tcp/mutations.spec.js
Labels: area/webui, kind/enhancement, size/L, status/3-needs-merge

#6028 fix: invalid label/flag parsing.
  pkg/config/parser/labels_decode.go
  pkg/config/parser/labels_decode_test.go
Labels: area/cli, kind/bug/fix, size/S, status/3-needs-merge

#6030 Don't set user-agent to Go-http-client/1.1
  pkg/server/service/proxy.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#5969 Support SSH connection to Docker
  docs/content/providers/docker.md
  go.mod
  go.sum
  pkg/provider/docker/docker.go
Labels: area/provider/docker, kind/enhancement, size/S, status/3-needs-merge

#6005 Add edge case for root path with rewrite-target
  provider/kubernetes/fixtures/ingressAnnotations_ingresses.yml
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#6046 Query consul for service health separately
  integration/consul_catalog_test.go
  pkg/provider/consulcatalog/consul_catalog.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#6070 Update ipwhitelist.md
  docs/content/middlewares/ipwhitelist.md
Labels: area/documentation, area/middleware, bot/light-review, size/S, status/3-needs-merge

#6079 fix: Malformed x-b3-traceid Header
  go.mod
  go.sum
Labels: area/middleware/tracing, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#6078 fix: dashboard redirect loop
  integration/testdata/rawdata-ingress.json
  pkg/provider/traefik/fixtures/api_insecure_with_dashboard.json
  pkg/provider/traefik/fixtures/full_configuration.json
  pkg/provider/traefik/internal.go
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge
