Repository traefik/traefik, pull requests merged in 2019-10, with the labels that each got.

#5517 Add a response forwarding section to the service documentation
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/services/index.md
Labels: area/documentation, kind/enhancement, size/S, status/2-needs-review, status/3-needs-merge

#5558 Typo in documentation
  docs/content/middlewares/headers.md
Labels: area/documentation, area/middleware, size/S, status/3-needs-merge

#5539 Add overview to API documentation
  docs/content/operations/api.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5569 Fix yaml domains example
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5572 fix: remove extra backtick from routers docs
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5575 fix: typo in healthCheck examples
  docs/content/routing/services/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5574 Fix Location response header http to https when SSL
  Gopkg.lock
  vendor/github.com/unrolled/secure/secure.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5555 Backport Go 1.13 integration test fixes
  integration/https_test.go
  integration/integration_test.go
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#5586 typo in cli command
  docs/content/observability/metrics/prometheus.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5584 Update scope of services and middlewares
  docs/content/middlewares/overview.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5570 Remove deprecated videos
  README.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5590 Fix typo in log
  pkg/provider/kubernetes/crd/client.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#5523 Clarifies how to configure and access the dashboard in the api & dashboard documentations
  docs/content/migration/v1-to-v2.md
  docs/content/operations/dashboard.md
Labels: area/api, area/documentation, area/webui, kind/enhancement, size/S, status/3-needs-merge

#5527 State clearly, that they are mutual exclusive
  docs/content/providers/file.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5233 Replace ambiguous cli help message wording
  cmd/healthcheck/healthcheck.go
  docs/content/operations/ping.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5585 Update 04-ingressroutes.yml
  docs/content/user-guides/crd-acme/04-ingressroutes.yml
Labels: area/documentation, area/provider/k8s/crd, size/S, status/3-needs-merge

#5594 Improve ciphersuite examples
  docs/content/migration/v1-to-v2.md
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5601 ci: reduce memory consumption of the linter
  .golangci.toml
  build.Dockerfile
  pkg/job/job_test.go
  pkg/safe/routine_test.go
  pkg/tracing/tracing.go
Labels: area/infrastructure, area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#5608 doc: update issues and PRs templates.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#5607 fix: ovh client int overflow.
  docs/content/https/acme.md
  go.mod
  go.sum
Labels: area/acme, bot/light-review, kind/bug/fix, status/3-needs-merge

#5605 Update apiVersion in documentation descriptor
  docs/content/user-guides/crd-acme/03-deployments.yml
Labels: area/documentation, area/provider/k8s/crd, kind/enhancement, size/S, status/3-needs-merge

#5613 fix misspelling on documentation landing page
  docs/content/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5612 fix: default router name for k8s ingress.
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/api, area/provider/k8s, area/provider/k8s/ingress, size/S, status/3-needs-merge

#5579 Add a service sticky details vue component
  webui/src/components/_commons/PanelServiceDetails.vue
  webui/src/components/_commons/StickyServiceDetails.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#5617 Prepare release v2.0.2
  .golangci.toml
  CHANGELOG.md
  script/validate-misspell
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5633 Fix acme storage file docker mounting example
  docs/content/https/acme.md
Labels: area/acme, area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5636 fix: add filename in the file provider logs.
  docs/content/routing/services/index.md
  pkg/provider/file/file.go
Labels: area/provider/file, kind/bug/fix, size/S, status/3-needs-merge

#5623 Normalize service and router names for ingress.
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#5644 chore(node/webui): update node to 12.11 version
  exp.Dockerfile
  webui/Dockerfile
  webui/readme.md
Labels: area/infrastructure, area/webui, kind/enhancement, size/S, status/3-needs-merge

#5600 Migration guide: pathprefixstrip migration
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, area/middleware, kind/enhancement, size/S, status/3-needs-merge

#5637 Update jaeger dependencies
  go.mod
  go.sum
  integration/fixtures/tracing/simple-jaeger.toml
  integration/resources/compose/tracing.yml
  integration/tracing_test.go
Labels: area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#5655 Remove deadcode.
  pkg/hostresolver/hostresolver.go
  pkg/hostresolver/hostresolver_test.go
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/M, status/3-needs-merge

#5395 Add Consul Catalog provider
  docs/content/assets/img/providers/consul.png
  docs/content/middlewares/addprefix.md
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/chain.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/overview.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/middlewares/redirectregex.md
  docs/content/middlewares/redirectscheme.md
  docs/content/middlewares/replacepath.md
  docs/content/middlewares/replacepathregex.md
  docs/content/middlewares/retry.md
  docs/content/middlewares/stripprefix.md
  docs/content/middlewares/stripprefixregex.md
  docs/content/operations/api.md
  docs/content/providers/consul-catalog.md
  docs/content/providers/consul-catalog.toml
  docs/content/providers/consul-catalog.txt
  docs/content/providers/consul-catalog.yml
  docs/content/reference/dynamic-configuration/consul-catalog.md
  docs/content/reference/dynamic-configuration/consul-catalog.yml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/providers/consul-catalog.md
  docs/mkdocs.yml
  go.mod
  go.sum
  integration/consul_catalog_test.go
  integration/fixtures/consul_catalog/default_not_exposed.toml
  integration/fixtures/consul_catalog/simple.toml
  integration/integration_test.go
  integration/resources/compose/consul_catalog.yml
  pkg/config/static/static_config.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/consulcatalog/config.go
  pkg/provider/consulcatalog/config_test.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/consulcatalog/convert_types.go
  pkg/provider/consulcatalog/convert_types_test.go
  pkg/provider/consulcatalog/label.go
  webui/src/statics/providers/consulcatalog.svg
Labels: area/provider/consulcatalog, kind/enhancement, size/L, status/3-needs-merge

#5664 Clarify unit of duration field in access log
  docs/content/observability/access-logs.md
Labels: area/documentation, area/logs, kind/enhancement, size/S, status/3-needs-merge

#5661 Fix consul catalog documentation
  docs/content/migration/v1-to-v2.md
  docs/content/providers/consul-catalog.yml
  docs/content/providers/overview.md
Labels: area/documentation, area/provider/consul, area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#5658 Let instana/go-sensor handle default agent host
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/tracing/instana/instana.go
Labels: area/middleware/tracing, kind/bug/fix, size/S, status/3-needs-merge

#5674 Fix spelling mistake: "founded" -> "found"
  pkg/provider/acme/provider.go
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5660 Adding support for HTTPs backends with Kubernetes ExternalName services
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#5683 fix ForwardAuth tls.skipverify examples
  docs/content/middlewares/forwardauth.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5694 fix typo for stripPrefix in tab File (YAML)
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5682 Update DaemonSet apiVersion
  examples/k8s/traefik-ds.yaml
Labels: area/documentation, area/provider/k8s, size/S, status/3-needs-merge

#5706 Fix Security Headers Doc
  docs/content/middlewares/headers.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5641 Use debug for log about skipping addition of cert
  pkg/tls/certificate.go
Labels: area/acme, area/logs, kind/bug/fix, size/S, status/3-needs-merge

#5712 Set proxy protocol logger to DEBUG level
  pkg/server/server_entrypoint_tcp.go
Labels: area/logs, kind/bug/fix, size/S, status/3-needs-merge

#5722 fix: skip akamai url verify.
  docs/scripts/verify.sh
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5720 fix: deep copy of passHostHeader on ServersLoadBalancer.
  pkg/config/dynamic/zz_generated.deepcopy.go
Labels: bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5707 Remove unnecessary reload of the configuration.
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#5724 Fix ldflags using incorrect pkg url
  script/binary
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#5662 Allow Default Certificate to work on macOS 10.15
  tls/generate/generate.go
Labels: area/tls, kind/bug/fix, size/S, status/3-needs-merge

#5714 Add documentation about backtick for rule definition.
  docs/content/routing/routers/index.md
Labels: area/documentation, area/rules, kind/enhancement, size/S, status/3-needs-merge

#5625 Improve documentation of the router rules for API and dashboard
  docs/content/operations/.markdownlint.json
  docs/content/operations/api.md
  docs/content/operations/dashboard.md
Labels: area/documentation, area/webui, kind/enhancement, size/S, status/3-needs-merge

#5734 doc: @ is not authorized in names definition.
  docs/content/providers/docker.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/providers/service-by-label.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5717 fix: default tracing backend.
  pkg/server/server.go
Labels: area/middleware/tracing, kind/bug/fix, size/S, status/3-needs-merge

#5739 Prepare release v1.7.19
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5224 Add example for changing the port used by traefik to connect to a service
  docs/content/routing/providers/docker.md
  docs/content/routing/services/.markdownlint.json
  docs/content/routing/services/index.md
Labels: area/documentation, size/S, status/3-needs-merge

#5743 Fix a typo in routing documentation for Docker
  docs/content/routing/providers/docker.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5742 Prepare release v2.0.3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, status/3-needs-merge

#5744 fix: release timeout.
  Makefile
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5746 Fix error in link description for priority
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
Labels: area/documentation, area/provider/docker, bot/light-review, size/S, status/3-needs-merge

#5749 Merge current v2.0 branch into master
  CHANGELOG.md
  Makefile
  README.md
  docs/content/getting-started/configuration-overview.md
  docs/content/https/acme.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/operations/.markdownlint.json
  docs/content/operations/api.md
  docs/content/operations/dashboard.md
  docs/content/providers/docker.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/providers/service-by-label.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/.markdownlint.json
  docs/content/routing/services/index.md
  docs/content/user-guides/crd-acme/index.md
  docs/scripts/verify.sh
  exp.Dockerfile
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/hostresolver/hostresolver.go
  pkg/hostresolver/hostresolver_test.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
  pkg/middlewares/recovery/recovery.go
  pkg/provider/acme/provider.go
  pkg/provider/file/file.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/server/server.go
  pkg/server/server_entrypoint_tcp.go
  pkg/tls/certificate.go
  pkg/tls/generate/generate.go
  pkg/tracing/instana/instana.go
  script/binary
  webui/Dockerfile
  webui/readme.md
Labels: size/L

#5725 fix: Consul Catalog documentation.
  docs/content/assets/img/providers/consul.png
  docs/content/providers/consul-catalog.md
  docs/content/providers/consul-catalog.toml
  docs/content/providers/consul-catalog.txt
  docs/content/providers/consul-catalog.yml
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  integration/fixtures/consul_catalog/default_not_exposed.toml
  integration/fixtures/consul_catalog/simple.toml
  pkg/config/static/static_config.go
  webui/src/statics/providers/consulcatalog.svg
Labels: area/documentation, area/provider/consulcatalog, kind/bug/fix, size/M, status/3-needs-merge

#5650 Add support for MaxVersion in tls.Options
  docs/content/https/tls.md
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/tls/certificate.go
  pkg/tls/tls.go
  pkg/tls/tlsmanager.go
Labels: area/tls, kind/enhancement, size/S, status/3-needs-merge

#5754 Upgrades zipkin library to avoid errors when using textMap.
  go.mod
  go.sum
Labels: area/middleware/tracing, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5721 Conditionnal compression based on Content-Type
  docs/content/middlewares/compress.md
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/middlewares/compress/compress.go
  pkg/middlewares/compress/compress_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/server/middleware/middlewares.go
Labels: area/middleware, kind/enhancement, size/M, status/3-needs-merge

#5752 feat: add consul catalog options
  docs/content/providers/consul-catalog.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/consulcatalog/consul_catalog.go
Labels: area/provider/consulcatalog, kind/enhancement, size/M, status/3-needs-merge
