Repository traefik/traefik, pull requests merged in 2019-09, with the labels that each got.

#5273 fix: stripPrefixRegex documentation.
  docs/content/middlewares/stripprefixregex.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/marathon-labels.json
Labels: area/documentation, area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#5274 deep-copy for MirrorService
  pkg/config/dynamic/zz_generated.deepcopy.go
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#5272 fix: Datadog case.
  CHANGELOG.md
  docs/content/observability/metrics/datadog.md
  docs/content/observability/metrics/overview.md
  docs/content/observability/tracing/datadog.md
  docs/content/observability/tracing/overview.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/mkdocs.yml
  pkg/anonymize/anonymize_config_test.go
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/file/file_node_test.go
  pkg/config/file/fixtures/sample.toml
  pkg/config/file/fixtures/sample.yml
  pkg/config/static/static_config.go
  pkg/metrics/datadog.go
  pkg/metrics/datadog_test.go
  pkg/server/server.go
  pkg/tracing/datadog/datadog.go
  pkg/tracing/haystack/haystack.go
  pkg/types/metrics.go
Labels: area/middleware/metrics, area/middleware/tracing, kind/bug/fix, size/M, status/3-needs-merge

#5270 Update restrictions in the documentation.
  docs/content/contributing/data-collection.md
  docs/content/https/tls.md
  docs/content/operations/api.md
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#5283 Update Zipkin OpenTracing driver to latest 0.4.3 release
  docs/content/observability/tracing/zipkin.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  integration/fixtures/tracing/simple-zipkin.toml
  integration/resources/compose/tracing.yml
  pkg/anonymize/anonymize_config_test.go
  pkg/config/file/file_node_test.go
  pkg/config/file/fixtures/sample.toml
  pkg/config/file/fixtures/sample.yml
  pkg/tracing/zipkin/zipkin.go
Labels: area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#5287 Update go version to go 1.13rc2
  .semaphoreci/setup.sh
  build.Dockerfile
  docs/content/contributing/building-testing.md
  exp.Dockerfile
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#5288 Re enable ratelimit integration tests
  docs/content/assets/img/middleware/ratelimit.png
  docs/content/middlewares/ratelimit.md
  integration/access_log_test.go
  integration/fixtures/tracing/simple-jaeger-collector.toml
  integration/fixtures/tracing/simple-jaeger.toml
  integration/fixtures/tracing/simple-zipkin.toml
  integration/resources/compose/access_log.yml
  integration/tracing_test.go
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/file/fixtures/sample.toml
Labels: area/middleware, area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#5281 fix buffering middleware
  cmd/traefik/traefik.go
  pkg/server/middleware/middlewares.go
  pkg/server/middleware/middlewares_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5289 Don't panic with undefined middleware
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
  pkg/server/middleware/middlewares.go
  pkg/server/middleware/middlewares_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5286 Fix some documentation issues
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/providers/docker.md
  docs/content/providers/file.md
  docs/content/routing/routers/index.md
  docs/content/user-guides/marathon.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5290 The chain middleware in k8s use middlewareRef
  docs/content/middlewares/chain.md
  integration/fixtures/k8s/04-ingressroute.yml
  integration/testdata/rawdata-crd.json
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: area/middleware, area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/L, status/3-needs-merge

#5291 fix: stripPrefix and stripPrefixRegex.
  docs/content/middlewares/stripprefixregex.md
  integration/fixtures/https/https_redirect.toml
  pkg/middlewares/stripprefix/strip_prefix.go
  pkg/middlewares/stripprefix/strip_prefix_test.go
  pkg/middlewares/stripprefixregex/strip_prefix_regex.go
  pkg/middlewares/stripprefixregex/strip_prefix_regex_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5293 Prepare release v2.0.0-rc2
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5296 Update to go 1.13
  .semaphoreci/setup.sh
  build.Dockerfile
  docs/content/contributing/building-testing.md
  exp.Dockerfile
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#5298 Enhance the Retry Middleware Documentation
  docs/content/middlewares/retry.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5302 misc documentation fixes
  docs/content/observability/access-logs.md
  docs/content/providers/docker.md
  docs/content/providers/marathon.md
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5299 Auth middlewares in kubernetes CRD uses secrets
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/forwardauth.md
  docs/content/observability/access-logs.md
  pkg/middlewares/buffering/buffering.go
  pkg/provider/kubernetes/crd/fixtures/with_auth.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/server/router/tcp/router.go
Labels: area/authentication, area/middleware, area/provider/k8s, area/provider/k8s/crd, kind/enhancement, size/L, status/3-needs-merge

#5314 Default to CLF when accesslog format is unsupported
  docs/content/observability/access-logs.md
  pkg/middlewares/accesslog/logger.go
Labels: area/logs, kind/enhancement, size/S, status/3-needs-merge

#5320 Update Acme doc - Vultr Wildcard & Root
  docs/configuration/acme.md
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5307 Misc documentation fixes
  .semaphoreci/setup.sh
  docs/content/https/tls.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/overview.md
  docs/content/middlewares/redirectregex.md
  docs/content/middlewares/stripprefix.md
  docs/content/middlewares/stripprefixregex.md
  docs/content/migration/v1-to-v2.md
  docs/content/operations/ping.md
  docs/content/providers/docker.md
  docs/content/providers/marathon.md
  docs/content/providers/rancher.md
  docs/content/routing/entrypoints.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5327 fix: TLS domains with IngressRoute.
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#5329 Write HTTP server logs into the global logger.
  pkg/server/server_entrypoint_tcp.go
Labels: area/server, kind/bug/fix, size/S, status/3-needs-merge

#5310 Improve rate limiter tests
  pkg/middlewares/ratelimiter/rate_limiter_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5334 Add provider in middleware chain
  integration/testdata/rawdata-crd.json
  pkg/server/middleware/middlewares.go
  pkg/server/router/router.go
  pkg/server/router/router_test.go
Labels: area/api, kind/bug/fix, size/S, status/3-needs-merge

#5339 k8s ErrorPage middleware now uses k8s service
  docs/content/middlewares/errorpages.md
  pkg/provider/kubernetes/crd/fixtures/with_error_page.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: area/middleware, area/provider/k8s, area/provider/k8s/crd, kind/enhancement, size/M

#5340 Update golangci-lint
  .golangci.toml
  build.Dockerfile
  integration/https_test.go
  integration/simple_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/server/router/route_appender_aggregator.go
  pkg/server/service/loadbalancer/mirror/mirror.go
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#5343 Prepare release v2.0.0-rc3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5353 Consider default cert domain in certificate store
  tls/certificate_store.go
  tls/certificate_store_test.go
Labels: area/tls, kind/bug/fix, size/M, status/3-needs-merge

#5238 Improve Access Logs Documentation page
  docs/configuration/logs.md
Labels: area/documentation, area/logs, kind/enhancement, size/S, status/3-needs-merge

#5373 fix a service with one server .yaml example
  docs/content/routing/services/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5376 implement Flusher and Hijacker for codeCatcher
  middlewares/errorpages/error_pages.go
Labels: area/middleware, area/websocket, kind/bug/fix, priority/P0, size/S, status/3-needs-merge

#5378 Prepare release v1.7.16
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5368 Add passHostHeader and responseForwarding in IngressRoute
  docs/content/providers/kubernetes-crd.md
  pkg/middlewares/ratelimiter/rate_limiter_test.go
  pkg/provider/kubernetes/crd/fixtures/with_options.yml
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/enhancement, size/M, status/3-needs-merge

#5366 On client CloseWrite, do CloseWrite instead of Close for backend
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/routing/services/index.md
  integration/testdata/rawdata-crd.json
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/config/label/label_test.go
  pkg/provider/docker/config.go
  pkg/provider/docker/config_test.go
  pkg/provider/marathon/config.go
  pkg/provider/marathon/config_test.go
  pkg/provider/rancher/config.go
  pkg/provider/rancher/config_test.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/tcp/service.go
  pkg/tcp/handler.go
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
  pkg/tcp/router.go
  pkg/tcp/rr_load_balancer.go
  pkg/tcp/switcher.go
  pkg/tcp/tls.go
Labels: area/tcp, kind/bug/fix, size/L, status/3-needs-merge

#5372 fix: boolean flag parsing with map.
  pkg/config/flag/flagparser.go
  pkg/config/flag/flagparser_test.go
Labels: area/cli, kind/bug/fix, size/S, status/3-needs-merge

#5370 fix: logger and context.
  integration/access_log_test.go
  integration/fake_dns_server.go
  integration/grpc_test.go
  integration/integration_test.go
  pkg/collector/collector.go
  pkg/config/static/static_config.go
  pkg/healthcheck/healthcheck.go
  pkg/log/deprecated.go
  pkg/log/fields.go
  pkg/middlewares/addprefix/add_prefix.go
  pkg/middlewares/auth/basic_auth.go
  pkg/middlewares/auth/digest_auth.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/buffering/buffering.go
  pkg/middlewares/chain/chain.go
  pkg/middlewares/circuitbreaker/circuit_breaker.go
  pkg/middlewares/compress/compress.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/ipwhitelist/ip_whitelist.go
  pkg/middlewares/metrics/metrics.go
  pkg/middlewares/middleware.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/pipelining/pipelining.go
  pkg/middlewares/ratelimiter/rate_limiter.go
  pkg/middlewares/recovery/recovery.go
  pkg/middlewares/redirect/redirect.go
  pkg/middlewares/redirect/redirect_regex.go
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/replacepath/replace_path.go
  pkg/middlewares/replacepathregex/replace_path_regex.go
  pkg/middlewares/retry/retry.go
  pkg/middlewares/stripprefix/strip_prefix.go
  pkg/middlewares/stripprefixregex/strip_prefix_regex.go
  pkg/middlewares/tracing/entrypoint.go
  pkg/middlewares/tracing/forwarder.go
  pkg/provider/acme/provider.go
  pkg/provider/docker/config.go
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/safe/routine.go
  pkg/server/cookie/cookie.go
  pkg/server/router/tcp/router_test.go
  pkg/server/server.go
  pkg/server/server_configuration.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/service/service.go
  pkg/tcp/rr_load_balancer.go
  pkg/tls/tlsmanager.go
  pkg/tls/tlsmanager_test.go
  pkg/version/version.go
Labels: area/logs, kind/bug/fix, size/M, status/3-needs-merge

#5383 Fix kubernetes id name
  integration/testdata/rawdata-crd.json
  integration/testdata/rawdata-ingress.json
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, kind/enhancement, size/L, status/3-needs-merge

#5384 Prepare release v2.0.0-rc4
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5388 fix: invalid hash for github.com/labbsr0x/goh
  go.mod
  go.sum
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5389 Web UI graph names.
  webui/quasar.conf.js
  webui/src/components/dashboard/PanelEntry.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#5386 Fix typo in documentation
  docs/content/observability/metrics/influxdb.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5392 Fix error in the documentation for CLI configuration example
  docs/content/https/acme.md
Labels: area/acme, area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5393 Disable collect data by default.
  cmd/traefik/traefik.go
  docs/content/contributing/data-collection.md
  pkg/anonymize/anonymize_config_test.go
  pkg/config/static/static_config.go
Labels: kind/enhancement, size/S, status/3-needs-merge

#5394 Prepare release v2.0.0
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/M, status/3-needs-merge

#5399 Update Traefik image version.
  docs/configuration/entrypoints.md
  docs/index.md
  docs/user-guide/cluster-docker-consul.md
  docs/user-guide/docker-and-lets-encrypt.md
  docs/user-guide/kubernetes.md
  docs/user-guide/kv-config.md
  examples/compose-rancher.yml
  examples/compose-traefik.yml
  examples/k8s/traefik-deployment.yaml
  examples/k8s/traefik-ds.yaml
  examples/quickstart/README.md
  examples/quickstart/docker-compose.yml
  webui/.gitignore
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5397 Fix case-sensitive header in websocket
  pkg/server/service/proxy.go
Labels: area/websocket, kind/bug/fix, size/S, status/3-needs-merge

#5401 fix: CNAME of the docs.
  docs/content/CNAME
Labels: area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#5391 Improve the Migration Guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/enhancement, size/L, status/3-needs-merge

#5409 fix typo for kubectl version
  docs/content/user-guides/crd-acme/index.md
Labels: area/acme, area/documentation, size/S, status/3-needs-merge

#5411 Update links in readme.
  README.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5412 Update docs links.
  .travis.yml
  CONTRIBUTING.md
  README.md
  cmd/traefik/traefik.go
  contrib/systemd/traefik.service
  examples/quickstart/README.md
  webui/src/app/components/header/header.component.html
Labels: area/documentation, area/webui, bot/light-review, size/S, status/3-needs-merge

#5407 Return an actual server status updater
  pkg/server/service/service.go
Labels: area/api, area/healthcheck, kind/bug/fix, size/S, status/3-needs-merge

#5362 Add note clarifying client certificate header
  docs/configuration/backends/kubernetes.md
Labels: area/provider/k8s, size/S, status/3-needs-merge

#5423 fix indentation for tab on migration guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5425 fixed doc typoes
  docs/content/operations/api.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5438 Flag names don't need a consistent case.
  pkg/config/parser/labels_decode.go
  pkg/config/parser/labels_decode_test.go
Labels: area/cli, kind/bug/fix, size/S, status/3-needs-merge

#5430 Improve the migration guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#5437 Improve documentation for the TLS section of the provider connection.
  docs/content/middlewares/forwardauth.md
  docs/content/providers/docker.md
  docs/content/providers/marathon.md
Labels: area/documentation, area/middleware, area/provider/docker, area/provider/marathon, area/tls, kind/enhancement, size/S, status/3-needs-merge

#5431 document that /dashboard should be preferred over /
  docs/content/operations/dashboard.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5428 doc: Flags and labels are case insensitive.
  docs/content/operations/cli.md
  docs/content/providers/docker.md
  docs/content/providers/marathon.md
  docs/content/providers/rancher.md
Labels: area/cli, area/documentation, area/provider/docker, kind/enhancement, size/S, status/3-needs-merge

#5404 Actually send header and code during WriteHeader, if needed
  middlewares/errorpages/error_pages.go
  middlewares/errorpages/error_pages_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5439 Wrong acme example.
  docs/content/https/acme.md
  docs/content/migration/v1-to-v2.md
Labels: area/acme, area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5452 fix: typo in TOML for HTTP to HTTPS redirection
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5448 Improve TLS documentation.
  docs/content/https/acme.md
  docs/content/https/tls.md
Labels: area/acme, area/documentation, area/tls, kind/enhancement, size/M, status/3-needs-merge

#5450 Improve routing documentation
  docs/content/contributing/data-collection.md
  docs/content/getting-started/concepts.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/https/acme.md
  docs/content/https/tls.md
  docs/content/index.md
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/observability/logs.md
  docs/content/operations/api.md
  docs/content/operations/cli.md
  docs/content/operations/dashboard.md
  docs/content/providers/docker.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/marathon.md
  docs/content/providers/overview.md
  docs/content/providers/rancher.md
  docs/content/routing/entrypoints.md
  docs/content/routing/overview.md
  docs/content/routing/providers/crd_ingress_route.yml
  docs/content/routing/providers/crd_middlewares.yml
  docs/content/routing/providers/crd_tls_option.yml
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
  docs/mkdocs.yml
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: area/documentation, kind/enhancement, size/L, status/3-needs-merge

#5459 Avoid closing stdout when the accesslog handler is closed
  middlewares/accesslog/logger.go
Labels: area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5461 YAML I love you
  docs/content/https/acme.md
  docs/content/https/tls.md
  docs/content/middlewares/addprefix.md
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/chain.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/overview.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/middlewares/redirectregex.md
  docs/content/middlewares/redirectscheme.md
  docs/content/middlewares/replacepath.md
  docs/content/middlewares/replacepathregex.md
  docs/content/middlewares/retry.md
  docs/content/middlewares/stripprefix.md
  docs/content/middlewares/stripprefixregex.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/observability/metrics/prometheus.md
  docs/content/operations/api.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/routing/entrypoints.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
  docs/content/user-guides/grpc.md
  docs/mkdocs.yml
Labels: area/documentation, area/yaml, kind/enhancement, size/L, status/3-needs-merge

#5467 add indent to fix notes
  docs/content/routing/providers/kubernetes-crd.md
Labels: area/documentation, area/provider/k8s, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5469 Prepare release v1.7.17
  CHANGELOG.md
Labels: area/documentation, bot/light-review, status/3-needs-merge

#5492 Update Casing on STS Header Directive
  docs/content/middlewares/headers.md
  go.mod
  go.sum
Labels: area/middleware, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#5485 Do not initialize list of middlewares if not needed
  pkg/server/middleware/middlewares.go
  pkg/server/router/router.go
Labels: area/server, kind/bug/fix, size/S, status/3-needs-merge

#5494 fix doc about file.filename
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/provider/file/file.go
Labels: area/documentation, area/provider/file, kind/bug/fix, size/S, status/3-needs-merge

#5486 fix: improve log for invalid middleware.
  pkg/server/middleware/middlewares.go
Labels: area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5490 fix: update linter.
  .golangci.toml
  cmd/traefik/traefik.go
  integration/error_pages_test.go
  integration/grpc_test.go
  integration/healthcheck_test.go
  integration/simple_test.go
  integration/tcp_test.go
  integration/tracing_test.go
  integration/websocket_test.go
  pkg/cli/commands_test.go
  pkg/cli/file_finder_test.go
  pkg/config/dynamic/middlewares.go
  pkg/config/parser/nodes_metadata.go
  pkg/config/runtime/runtime_test.go
  pkg/config/static/entrypoints.go
  pkg/log/log_test.go
  pkg/metrics/influxdb_test.go
  pkg/metrics/prometheus_test.go
  pkg/middlewares/accesslog/field_middleware.go
  pkg/middlewares/accesslog/logger_formatters.go
  pkg/middlewares/accesslog/logger_formatters_test.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/middlewares/auth/forward_test.go
  pkg/middlewares/headers/headers_test.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
  pkg/middlewares/pipelining/pipelining.go
  pkg/middlewares/ratelimiter/rate_limiter_test.go
  pkg/middlewares/redirect/redirect_regex_test.go
  pkg/middlewares/redirect/redirect_scheme_test.go
  pkg/middlewares/replacepath/replace_path_test.go
  pkg/middlewares/replacepathregex/replace_path_regex_test.go
  pkg/middlewares/tracing/entrypoint_test.go
  pkg/middlewares/tracing/forwarder_test.go
  pkg/provider/acme/local_store.go
  pkg/provider/acme/provider.go
  pkg/provider/docker/docker.go
  pkg/provider/file/file_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/marathon/marathon.go
  pkg/provider/rancher/config.go
  pkg/provider/rest/rest.go
  pkg/server/router/router_test.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/loadbalancer/wrr/wrr_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/server/service/service_test.go
  pkg/server/service/tcp/service.go
  pkg/tls/certificate.go
  pkg/tls/certificate_store.go
  pkg/types/logs.go
Labels: area/infrastructure, kind/bug/fix, size/L, status/3-needs-merge

#5491 fix: docker service name.
  integration/docker_compose_test.go
  pkg/provider/docker/config.go
  pkg/provider/docker/docker.go
Labels: area/provider/docker, kind/bug/fix, size/S, status/3-needs-merge

#5493 clarify automatic service creation/assignment with labels
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/providers/service-by-label.md
  docs/content/routing/routers/index.md
  pkg/provider/docker/config_test.go
Labels: area/documentation, area/provider/docker, area/provider/marathon, area/provider/rancher, kind/enhancement, size/M, status/3-needs-merge

#5481 Add the router priority documentation
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5505 Prepare release v1.7.18
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#5508 Prepare release v2.0.1
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/2-needs-review, status/3-needs-merge

#5504 Change instances of "dymanic" to "dynamic"
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#5520 Fixed typo in routing/providers/docker documentation
  docs/content/routing/providers/docker.md
Labels: area/documentation, area/provider/docker, bot/light-review, size/S, status/3-needs-merge

#5540 Fix misleading text
  docs/content/middlewares/redirectscheme.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#5500 Add the pass host header section to the services documentation
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/services/index.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5536 fix: panic with metrics recorder.
  pkg/middlewares/metrics/recorder.go
Labels: area/middleware, area/middleware/metrics, kind/bug/fix, size/S, status/3-needs-merge

#5531 doc: fix influxDB and statsD case in configuration page.
  docs/content/observability/metrics/influxdb.md
  docs/content/observability/metrics/statsd.md
Labels: area/documentation, area/middleware/metrics, kind/bug/fix, size/S, status/3-needs-merge

#5529 document serversTransport
  docs/content/routing/overview.md
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#5549 fix: return an error instead of panic.
  pkg/config/file/raw_node.go
  pkg/config/file/raw_node_test.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#5516 fix: default passHostHeader for file provider.
  pkg/api/handler_http_test.go
  pkg/api/handler_test.go
  pkg/api/testdata/getrawdata.json
  pkg/api/testdata/service-bar.json
  pkg/api/testdata/services-filtered-search.json
  pkg/api/testdata/services-filtered-status.json
  pkg/api/testdata/services-page2.json
  pkg/api/testdata/services.json
  pkg/config/dynamic/http_config.go
  pkg/config/label/label_test.go
  pkg/provider/docker/config_test.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/provider/marathon/config_test.go
  pkg/provider/rancher/config_test.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/server/service/service.go
  pkg/server/service/service_test.go
Labels: area/provider/file, kind/bug/fix, size/M, status/3-needs-merge

#5519 document providersThrottleDuration
  docs/content/providers/overview.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#5528 $ needs escaping in docker-compose.yml
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge
