Repository traefik/traefik, pull requests merged in 2019-02, with the labels that each got.

#4442 fix missing trailers with retry
  integration/fixtures/grpc/config_retry.toml
  integration/grpc_test.go
  middlewares/retry.go
Labels: area/middleware, kind/bug/fix, status/3-needs-merge

#4457 Updates Backoff
  Gopkg.lock
  Gopkg.toml
  acme/acme.go
  acme/challenge_http_provider.go
  acme/challenge_tls_provider.go
  cluster/datastore.go
  cluster/leadership.go
  cmd/traefik/traefik.go
  job/job.go
  job/job_test.go
  old/provider/consulcatalog/consul_catalog.go
  old/provider/dynamodb/dynamodb.go
  old/provider/ecs/ecs.go
  old/provider/eureka/eureka.go
  old/provider/kubernetes/kubernetes.go
  old/provider/kv/kv.go
  old/provider/mesos/mesos.go
  old/provider/rancher/api.go
  old/provider/rancher/metadata.go
  provider/acme/challenge_http.go
  provider/acme/provider.go
  provider/docker/docker.go
  provider/marathon/marathon.go
  safe/routine.go
  safe/routine_test.go
  vendor/github.com/cenkalti/backoff/LICENSE
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/tries.go
Labels: bot/light-review, kind/enhancement, size/M, status/3-needs-merge

#4468 Update default value in docs of buckets for Prometheus
  docs/configuration/metrics.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#4462 chore(lint): include lint in build process
  webui/Dockerfile
  webui/src/app/services/api.service.ts
Labels: area/provider/docker, area/webui, size/S, status/3-needs-merge

#4466 refactor: applies linting.
  .golangci.toml
  cmd/bug/bug.go
  cmd/traefik/traefik.go
  config/static/entrypoints.go
  config/static/static_config.go
  healthcheck/healthcheck.go
  middlewares/accesslog/logger.go
  middlewares/auth/forward.go
  middlewares/headers/headers_test.go
  middlewares/passtlsclientcert/pass_tls_client_cert.go
  middlewares/retry/retry_test.go
  provider/acme/local_store.go
  provider/acme/provider.go
  provider/base_provider.go
  provider/docker/config.go
  provider/file/file.go
  provider/rest/rest.go
  server/server_signals.go
  server/service/service.go
  types/constraints.go
Labels: area/infrastructure, kind/enhancement, size/M, status/3-needs-merge

#4463 chore(webui): format code with prettier
  webui/.prettierrc
  webui/Dockerfile
  webui/package.json
  webui/readme.md
  webui/src/app/app.component.spec.ts
  webui/src/app/app.component.ts
  webui/src/app/app.module.ts
  webui/src/app/charts/bar-chart/bar-chart.component.html
  webui/src/app/charts/bar-chart/bar-chart.component.spec.ts
  webui/src/app/charts/bar-chart/bar-chart.component.ts
  webui/src/app/charts/line-chart/line-chart.component.html
  webui/src/app/charts/line-chart/line-chart.component.ts
  webui/src/app/components/header/header.component.html
  webui/src/app/components/header/header.component.ts
  webui/src/app/components/health/health.component.html
  webui/src/app/components/health/health.component.ts
  webui/src/app/components/providers/providers.component.html
  webui/src/app/components/providers/providers.component.ts
  webui/src/app/directives/let.directive.ts
  webui/src/app/pipes/backend.filter.pipe.ts
  webui/src/app/pipes/frontend.filter.pipe.ts
  webui/src/app/pipes/humanreadable.filter.pipe.spec.ts
  webui/src/app/pipes/humanreadable.filter.pipe.ts
  webui/src/app/pipes/keys.pipe.ts
  webui/src/app/services/api.service.ts
  webui/src/app/services/window.service.ts
  webui/src/index.html
  webui/src/main.ts
  webui/src/polyfills.ts
  webui/src/test.ts
  webui/tslint.json
  webui/yarn.lock
Labels: area/webui, size/L, status/3-needs-merge

#4471 Fixed curl example
  docs/configuration/backends/rest.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#4478 Fixes the display of the associativity rules.
  docs/basics.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#4479 Add support for specifying the name of the endpoint.
  Gopkg.lock
  Gopkg.toml
  docs/configuration/backends/servicefabric.md
  vendor/github.com/cenk/backoff/context.go
  vendor/github.com/cenk/backoff/exponential.go
  vendor/github.com/cenk/backoff/retry.go
  vendor/github.com/cenk/backoff/ticker.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
Labels: area/provider/servicefabric, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#4482 Prepare release v1.7.9
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#4499 Applies new goimports recommendations.
  anonymize/anonymize_config_test.go
  api/dashboard.go
  api/handler.go
  cluster/datastore.go
  cmd/configuration.go
  cmd/traefik/traefik.go
  configuration/configuration.go
  integration/etcd3_test.go
  provider/etcd/etcd.go
  provider/kubernetes/weight_allocator_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#4498 Applies new goimports recommendations.
  anonymize/anonymize_config_test.go
  api/dashboard.go
  api/handler.go
  cluster/datastore.go
  cmd/traefik/traefik.go
  config/static/static_config.go
  integration/etcd3_test.go
  old/api/dashboard.go
  old/api/handler.go
  old/provider/etcd/etcd.go
  old/provider/kubernetes/weight_allocator_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#4453 Instana tracer implementation
  Gopkg.lock
  Gopkg.toml
  cmd/configuration.go
  config/static/static_config.go
  docs/configuration/tracing.md
  server/server.go
  tracing/instana/instana.go
  vendor/github.com/instana/go-sensor/LICENSE.md
  vendor/github.com/instana/go-sensor/agent.go
  vendor/github.com/instana/go-sensor/context.go
  vendor/github.com/instana/go-sensor/eum.go
  vendor/github.com/instana/go-sensor/event.go
  vendor/github.com/instana/go-sensor/fsm.go
  vendor/github.com/instana/go-sensor/json_span.go
  vendor/github.com/instana/go-sensor/log.go
  vendor/github.com/instana/go-sensor/meter.go
  vendor/github.com/instana/go-sensor/options.go
  vendor/github.com/instana/go-sensor/propagation.go
  vendor/github.com/instana/go-sensor/recorder.go
  vendor/github.com/instana/go-sensor/sensor.go
  vendor/github.com/instana/go-sensor/span.go
  vendor/github.com/instana/go-sensor/tracer.go
  vendor/github.com/instana/go-sensor/tracer_options.go
  vendor/github.com/instana/go-sensor/util.go
  vendor/github.com/looplab/fsm/LICENSE
  vendor/github.com/looplab/fsm/errors.go
  vendor/github.com/looplab/fsm/event.go
  vendor/github.com/looplab/fsm/fsm.go
  vendor/github.com/looplab/fsm/utils.go
  vendor/github.com/opentracing/basictracer-go/LICENSE
  vendor/github.com/opentracing/basictracer-go/context.go
  vendor/github.com/opentracing/basictracer-go/debug.go
  vendor/github.com/opentracing/basictracer-go/event.go
  vendor/github.com/opentracing/basictracer-go/propagation.go
  vendor/github.com/opentracing/basictracer-go/propagation_ot.go
  vendor/github.com/opentracing/basictracer-go/raw.go
  vendor/github.com/opentracing/basictracer-go/recorder.go
  vendor/github.com/opentracing/basictracer-go/span.go
  vendor/github.com/opentracing/basictracer-go/tracer.go
  vendor/github.com/opentracing/basictracer-go/util.go
  vendor/github.com/opentracing/basictracer-go/wire/carrier.go
  vendor/github.com/opentracing/basictracer-go/wire/gen.go
  vendor/github.com/opentracing/basictracer-go/wire/wire.pb.go
Labels: area/middleware/tracing, kind/enhancement, size/M, status/3-needs-merge

#4508 Update Structor to v1.4.0
  .travis.yml
Labels: area/documentation, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#4511 Cherry pick v1.7 into master
  .travis.yml
Labels: size/S

#4476 Adds Kubernetes provider support
  cmd/configuration.go
  cmd/traefik/traefik.go
  config/static/static_config.go
  provider/aggregator/aggregator.go
  provider/kubernetes/builder_endpoint_test.go
  provider/kubernetes/builder_ingress_test.go
  provider/kubernetes/builder_service_test.go
  provider/kubernetes/client.go
  provider/kubernetes/client_mock_test.go
  provider/kubernetes/client_test.go
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
  provider/kubernetes/namespace.go
Labels: area/provider/k8s, kind/enhancement, size/L, status/3-needs-merge

#4520 chore(webui): dropping rxjs-compat in favor of pipe
  webui/package.json
  webui/src/app/components/health/health.component.ts
  webui/src/app/components/providers/providers.component.ts
  webui/src/app/services/api.service.ts
  webui/src/app/services/window.service.ts
  webui/yarn.lock
Labels: area/webui, kind/enhancement, size/S, status/3-needs-merge

#4486 Loop through service ports for global backend
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#4535 fix: image links.
  README.md
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#4538 Travis: switch fallback dockerfile for structor
  .travis.yml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#4543 Fixed dead link in README.md
  README.md
Labels: area/documentation, area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge
