Repository traefik/traefik, pull requests merged in 2019-05, with the labels that each got.

#4831 docker-compose basic auth needs dubble dollar signs
  docs/content/middlewares/basicauth.md
Labels: area/documentation, area/middleware, kind/enhancement, size/S, status/3-needs-merge

#4751 Docs: Troubleshooting help for Docker Swarm labels
  docs/configuration/backends/docker.md
Labels: area/documentation, area/provider/docker, size/S, status/3-needs-merge

#4834 Clarification of the correct pronunciation of the word "Traefik"
  README.md
  docs/theme/main.html
  old/docs/theme/partials/footer.html
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#4821 Allow SANs for wildcards domain.
  CONTRIBUTING.md
  acme/acme.go
  acme/acme_test.go
  docs/theme/partials/footer.html
  provider/acme/provider.go
  provider/acme/provider_test.go
Labels: area/acme, bot/need-human-merge, kind/bug/fix, size/S, status/3-needs-merge

#4844 Fix `make validate` on MacOS outside container
  script/test-integration
  script/update-cert.sh
  script/update-generated-crd-code.sh
  script/validate-vendor
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#4763 Allow matching with FQDN hosts with trailing periods
  docs/content/contributing/submitting-pull-requests.md
  integration/fixtures/file/simple-hosts.toml
  integration/simple_test.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
Labels: area/rules, kind/bug/fix, size/S, status/3-needs-merge

#4848 Fixed spelling typo
  docs/content/routing/overview.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#4849 fix: typo in routing example.
  docs/content/routing/routers/index.md
Labels: area/documentation, area/tls, kind/bug/fix, size/S, status/3-needs-merge

#4847 Clarify docs with labels in Swarm Mode
  docs/content/providers/docker.md
Labels: area/documentation, area/provider/docker, size/S

#4858 Don't add TCP proxy when error occurs during creation.
  pkg/server/router/router.go
  pkg/server/router/tcp/router.go
  pkg/server/service/tcp/service.go
  pkg/server/service/tcp/service_test.go
  pkg/tcp/proxy.go
  pkg/tcp/rr_load_balancer.go
Labels: area/tcp, kind/bug/fix, size/S, status/3-needs-merge

#4860 Add note about ACME renewal
  docs/content/https-tls/acme.md
Labels: area/acme, area/documentation, kind/enhancement, size/S, status/3-needs-merge

#4842 Remove timeout/interval from the ACME Provider
  docs/content/https-tls/acme.md
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
Labels: area/acme, kind/enhancement, size/M, status/3-needs-merge

#4866 Remove old docs folder.
  old/docs/CNAME
  old/docs/benchmarks.md
  old/docs/configuration/api.md
  old/docs/configuration/backends/boltdb.md
  old/docs/configuration/backends/consul.md
  old/docs/configuration/backends/consulcatalog.md
  old/docs/configuration/backends/docker.md
  old/docs/configuration/backends/dynamodb.md
  old/docs/configuration/backends/ecs.md
  old/docs/configuration/backends/etcd.md
  old/docs/configuration/backends/eureka.md
  old/docs/configuration/backends/file.md
  old/docs/configuration/backends/kubernetes.md
  old/docs/configuration/backends/marathon.md
  old/docs/configuration/backends/mesos.md
  old/docs/configuration/backends/rancher.md
  old/docs/configuration/backends/rest.md
  old/docs/configuration/backends/servicefabric.md
  old/docs/configuration/backends/zookeeper.md
  old/docs/configuration/commons.md
  old/docs/img/architecture.png
  old/docs/img/architecture.svg
  old/docs/img/grpc.svg
  old/docs/img/internal.png
  old/docs/img/letsencrypt-logo-horizontal.svg
  old/docs/img/overview.svg
  old/docs/img/traefik-health.png
  old/docs/img/traefik.icon.png
  old/docs/img/traefik.logo.png
  old/docs/img/web.frontend.png
  old/docs/img/zenika.logo.png
  old/docs/index.md
  old/docs/metrics.md
  old/docs/theme/js/extra.js
  old/docs/theme/js/hljs/LICENSE
  old/docs/theme/js/hljs/highlight.pack.js
  old/docs/theme/partials/footer.html
  old/docs/theme/styles/atom-one-light.css
  old/docs/theme/styles/extra.css
  old/docs/user-guide/cluster-docker-consul.md
  old/docs/user-guide/cluster.md
  old/docs/user-guide/docker-and-lets-encrypt.md
  old/docs/user-guide/examples.md
  old/docs/user-guide/grpc.md
  old/docs/user-guide/kubernetes.md
  old/docs/user-guide/kv-config.md
  old/docs/user-guide/marathon.md
  old/docs/user-guide/swarm-mode.md
  old/docs/user-guide/swarm.md
Labels: area/documentation, area/infrastructure, bot/light-review, size/L, status/3-needs-merge

#4859 Add shell script linting with shellcheck for better portability
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  Makefile
  docs/content/contributing/building-testing.md
  script/binary
  script/crossbinary-default
  script/deploy.sh
  script/make.sh
  script/test-integration
  script/test-unit
  script/update-cert.sh
  script/update-generated-crd-code.sh
  script/validate-misspell
  script/validate-shell-script.sh
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#4873 Fix regression on plumbing scripts for developer usages
  script/binary
  script/test-integration
  script/test-unit
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#4877 Enhance KV logs.
  provider/kv/kv_config.go
Labels: area/provider/consul, kind/bug/fix, size/S, status/3-needs-merge

#4878 Upgraded DataDog tracing library to 1.13.0
  Gopkg.lock
  Gopkg.toml
  vendor/google.golang.org/api/dns/v1/dns-gen.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ddtrace.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext/tags.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer/option.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/option.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/sampler.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/span.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/spancontext.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/textmap.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/transport.go
  vendor/gopkg.in/DataDog/dd-trace-go.v1/internal/globalconfig/globalconfig.go
Labels: area/middleware/metrics, kind/bug/fix, size/S, status/3-needs-merge

#4884 Fix typos in documentation
  cmd/storeconfig/storeconfig.go
  docs/content/getting-started/concepts.md
  docs/content/getting-started/quick-start.md
  docs/content/operations/cli.md
  docs/content/providers/docker.md
  docs/content/providers/overview.md
  docs/content/routing/overview.md
  docs/content/routing/routers/index.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#4882 Fixed readme misspelling
  webui/readme.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#4886 documentation remove traefik.port.
  docs/content/providers/docker.md
Labels: area/documentation, area/provider/docker, kind/bug/fix, size/S, status/3-needs-merge

#4890 Adds a log fields documentation.
  docs/configuration/logs.md
Labels: area/documentation, area/logs, kind/enhancement, size/S, status/3-needs-merge

#4891 Fix typos in data collection message
  cmd/traefik/traefik.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#4900 Add missing callback on close of hijacked connections
  Gopkg.lock
  vendor/github.com/vulcand/oxy/forward/fwd.go
Labels: area/server, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#4901 fix kubernetes template for backend responseforwarding flushinterval setting
  autogen/gentemplates/gen.go
  templates/kubernetes.tmpl
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#4902 Fix typo in the CRD documentation
  docs/content/middlewares/overview.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/kubernetes-crd.yml
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#4896 Entry points CLI description.
  docs/content/reference/static-configuration.txt
  pkg/config/static/static_config.go
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#4888 fix the documentation about middleware labels.
  docs/content/middlewares/overview.md
  docs/content/providers/docker.md
  docs/content/providers/marathon.md
  docs/content/providers/rancher.md
Labels: area/documentation, area/middleware, area/provider, kind/bug/fix, size/S, status/3-needs-merge

#4908 Docs: improve the "reading path" for new contributers
  CONTRIBUTING.md
  docs/content/contributing/thank-you.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#4910 fix: update-lego.
  Gopkg.lock
  Gopkg.toml
  docs/configuration/acme.md
  vendor/github.com/go-acme/lego/acme/api/internal/sender/useragent.go
  vendor/github.com/go-acme/lego/certificate/certificates.go
  vendor/github.com/go-acme/lego/challenge/dns01/dns_challenge_manual.go
  vendor/github.com/go-acme/lego/platform/config/env/env.go
  vendor/github.com/go-acme/lego/providers/dns/bindman/bindman.go
  vendor/github.com/go-acme/lego/providers/dns/digitalocean/client.go
  vendor/github.com/go-acme/lego/providers/dns/digitalocean/digitalocean.go
  vendor/github.com/go-acme/lego/providers/dns/dns_providers.go
  vendor/github.com/go-acme/lego/providers/dns/easydns/client.go
  vendor/github.com/go-acme/lego/providers/dns/easydns/easydns.go
  vendor/github.com/go-acme/lego/providers/dns/exec/exec.go
  vendor/github.com/go-acme/lego/providers/dns/gcloud/googlecloud.go
  vendor/github.com/go-acme/lego/providers/dns/joker/client.go
  vendor/github.com/go-acme/lego/providers/dns/joker/joker.go
  vendor/github.com/go-errors/errors/LICENSE.MIT
  vendor/github.com/go-errors/errors/error.go
  vendor/github.com/go-errors/errors/parse_panic.go
  vendor/github.com/go-errors/errors/stackframe.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/LICENSE
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/client/client.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/dnsmanager.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/dnsrecord.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/error.go
  vendor/github.com/labbsr0x/goh/LICENSE
  vendor/github.com/labbsr0x/goh/gohclient/gohclient.go
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#4918 Remove authentication hashes from API
  types/types.go
Labels: area/api, area/authentication, kind/bug/fix, size/S, status/3-needs-merge

#4919 Prepare release v1.7.12
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge
