Repository traefik/traefik, pull requests merged in 2020-11, with the labels that each got.

#7501 Add ECS menu to dynamic config reference
  docs/content/routing/providers/ecs.md
  docs/mkdocs.yml
Labels: area/documentation, area/provider/ecs, kind/bug/fix, size/S, status/3-needs-merge

#7512 Add AccessControlAllowOriginListRegex field to deepcopy
  pkg/config/dynamic/zz_generated.deepcopy.go
Labels: area/middleware, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#7460 Feature: Exponential Backoff in Retry Middleware
  docs/content/middlewares/retry.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  integration/fixtures/retry/backoff.toml
  integration/retry_test.go
  pkg/config/dynamic/middlewares.go
  pkg/config/label/label_test.go
  pkg/middlewares/retry/retry.go
  pkg/middlewares/retry/retry_test.go
Labels: area/middleware, kind/enhancement, size/L, status/3-needs-merge

#7516 chore: update linter.
  .golangci.toml
  build.Dockerfile
  go.sum
  pkg/log/log.go
  pkg/metrics/prometheus.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/recovery/recovery.go
  pkg/provider/docker/docker.go
  pkg/server/server.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/server/service/loadbalancer/wrr/wrr.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_websocket_test.go
  pkg/tcp/router.go
  pkg/udp/conn_test.go
Labels: area/infrastructure, kind/enhancement, size/S, status/3-needs-merge

#7523 Fix Traefik Proxy product nav in docs
  docs/theme/partials/company-header.html
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7526 Update go-acme/lego to v4.1.0
  docs/content/https/acme.md
  go.mod
  go.sum
  integration/resources/compose/pebble.yml
  integration/resources/compose/proxy-protocol.yml
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7527 Update Yaegi to v0.9.5
  go.mod
  go.sum
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7529 Merge current v2.3 branch into master
  .golangci.toml
  build.Dockerfile
  docs/content/https/acme.md
  docs/content/routing/providers/ecs.md
  docs/mkdocs.yml
  docs/theme/partials/company-header.html
  go.mod
  go.sum
  integration/resources/compose/pebble.yml
  integration/resources/compose/proxy-protocol.yml
  pkg/anonymize/anonymize.go
  pkg/anonymize/anonymize_config_test.go
  pkg/anonymize/anonymize_doOnJSON_test.go
  pkg/anonymize/anonymize_doOnStruct_test.go
  pkg/anonymize/testdata/anonymized-static-config.json
  pkg/anonymize/testdata/example.json
  pkg/anonymize/testdata/expected.json
  pkg/config/static/entrypoints.go
  pkg/config/static/experimental.go
  pkg/config/static/static_config.go
  pkg/log/log.go
  pkg/metrics/prometheus.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/recovery/recovery.go
  pkg/ping/ping.go
  pkg/plugins/types.go
  pkg/provider/acme/provider.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/docker/docker.go
  pkg/provider/http/http.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kv/consul/consul.go
  pkg/provider/kv/etcd/etcd.go
  pkg/provider/kv/redis/redis.go
  pkg/provider/kv/zk/zk.go
  pkg/provider/marathon/marathon.go
  pkg/provider/rancher/rancher.go
  pkg/server/server.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/server/service/loadbalancer/wrr/wrr.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_websocket_test.go
  pkg/tcp/router.go
  pkg/tracing/datadog/datadog.go
  pkg/tracing/elastic/elastic.go
  pkg/tracing/jaeger/jaeger.go
  pkg/types/logs.go
  pkg/types/metrics.go
  pkg/types/tls.go
  pkg/udp/conn_test.go
Labels: size/L

#7480 fix: translate configured server port into correct mapped host port
  pkg/provider/ecs/config.go
  pkg/provider/ecs/config_test.go
Labels: area/provider/ecs, kind/bug/fix, size/M, status/3-needs-merge

#7541 Fix docs for TLS
  docs/content/https/tls.md
Labels: area/documentation, kind/bug/fix, size/L, status/3-needs-merge

#7506 Forwardauth headers
  docs/content/middlewares/forwardauth.md
Labels: area/documentation, kind/enhancement, size/L, status/3-needs-merge

#7370 Improve service name lookup on TCP routers
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
Labels: area/tcp, kind/bug/fix, size/S, status/3-needs-merge

#7548 /bin/bash replaced with /usr/bin/env bash to match other scripts
  script/crossbinary-default
  script/update-generated-crd-code.sh
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#7514 fix: consulcatalog to update before the first interval
  pkg/provider/consulcatalog/consul_catalog.go
Labels: area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#7320 added support for tcp proxyProtocol v1&v2 to backend
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/routing/providers/consul-catalog.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/ecs.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kv.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/services/index.md
  go.mod
  go.sum
  integration/proxy_protocol_test.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/config/label/label_test.go
  pkg/provider/kubernetes/crd/fixtures/tcp/with_proxyprotocol.yml
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/service/tcp/service.go
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
Labels: area/server, kind/enhancement, size/S, status/3-needs-merge

#7558 Fix consul catalog panic when health and services are not in sync
  pkg/provider/consulcatalog/consul_catalog.go
Labels: area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#7561 Fix missing allow-empty tag on ECS and Consul Catalog providers
  docs/content/providers/ecs.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/config/static/static_config.go
  pkg/provider/ecs/ecs.go
Labels: area/provider/consulcatalog, area/provider/ecs, kind/bug/fix, size/S, status/3-needs-merge

#7565 Fix grammar in kubernetes ingress controller documentation
  docs/content/providers/kubernetes-ingress.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7569 Update Yaegi to v0.9.7
  go.mod
  go.sum
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7570 Prepare release v2.3.3
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#7521 Apply labelSelector as a TweakListOptions for Kubernetes informers
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  integration/fixtures/k8s/03-ingress.yml
  integration/fixtures/k8s/03-ingressroute.yml
  integration/fixtures/k8s/03-tlsoption.yml
  integration/fixtures/k8s/03-tlsstore.yml
  integration/fixtures/k8s/06-ingressroute-traefikservices.yml
  integration/fixtures/k8s_crd_label_selector.toml
  integration/fixtures/k8s_ingress_label_selector.toml
  integration/k8s_test.go
  integration/testdata/rawdata-crd-label-selector.json
  integration/testdata/rawdata-ingress-label-selector.json
  pkg/provider/kubernetes/crd/client.go
  pkg/provider/kubernetes/crd/client_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, size/L, status/3-needs-merge

#7574 Merge current v2.3 branch into master
  CHANGELOG.md
  docs/content/https/tls.md
  docs/content/middlewares/forwardauth.md
  docs/content/providers/ecs.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  go.mod
  go.sum
  integration/fixtures/k8s/03-ingress.yml
  integration/fixtures/k8s/03-ingressroute.yml
  integration/fixtures/k8s/03-tlsoption.yml
  integration/fixtures/k8s/03-tlsstore.yml
  integration/fixtures/k8s/06-ingressroute-traefikservices.yml
  integration/fixtures/k8s_crd_label_selector.toml
  integration/fixtures/k8s_ingress_label_selector.toml
  integration/k8s_test.go
  integration/testdata/rawdata-crd-label-selector.json
  integration/testdata/rawdata-ingress-label-selector.json
  pkg/config/static/static_config.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/ecs/config.go
  pkg/provider/ecs/config_test.go
  pkg/provider/ecs/ecs.go
  pkg/provider/kubernetes/crd/client.go
  pkg/provider/kubernetes/crd/client_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
  script/crossbinary-default
  script/gcg/traefik-bugfix.toml
  script/update-generated-crd-code.sh
Labels: size/L

#7577 Update go-acme/lego to v4.1.2
  go.mod
  go.sum
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7583 fix: invalid slice parsing.
  go.mod
  go.sum
Labels: area/provider, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7573 Do not evaluate templated URL in redirectRegex middleware
  pkg/middlewares/redirect/redirect.go
  pkg/middlewares/redirect/redirect_regex_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7586 Fix clusters option in ECS provider documentation
  docs/content/providers/ecs.md
Labels: area/documentation, area/provider/ecs, size/S, status/3-needs-merge

#7588 Prepare release v2.3.4
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7596 Fix typos in migration guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7602 Display Proxy Protocol version for backend services in web dashboard.
  webui/src/components/_commons/PanelServiceDetails.vue
Labels: area/webui, kind/enhancement, size/S, status/3-needs-merge
