Repository traefik/traefik, pull requests merged in 2020-09, with the labels that each got.

#7219 Add example for the IngressClass usage
  docs/content/providers/kubernetes-ingress.md
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/enhancement, size/S, status/3-needs-merge

#7233 Add missing IPStrategy struct tag for YAML
  docs/content/reference/dynamic-configuration/file.yaml
  pkg/config/dynamic/middlewares.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7230 Headers response modifier is directly applied by headers middleware
  integration/fixtures/headers/secure_multiple.toml
  integration/headers_test.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
  pkg/middlewares/headers/header.go
  pkg/middlewares/headers/header_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/headers_test.go
  pkg/middlewares/headers/responsewriter.go
  pkg/middlewares/headers/secure.go
  pkg/middlewares/headers/secure_test.go
  pkg/responsemodifiers/headers.go
  pkg/responsemodifiers/log.go
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
  pkg/server/middleware/middlewares.go
  pkg/server/router/router.go
  pkg/server/router/router_test.go
  pkg/server/routerfactory.go
  pkg/server/service/internalhandler.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/server/service/service.go
  pkg/server/service/service_test.go
Labels: area/middleware, kind/bug/fix, size/L, status/3-needs-merge

#7237 doc: specify HostSNI rule removal only for HTTP routers
  docs/content/migration/v2.md
Labels: area/documentation, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7238 Update go-acme/lego to v4.0.1
  docs/content/https/acme.md
  docs/content/https/ref-acme.toml
  docs/content/https/ref-acme.txt
  docs/content/https/ref-acme.yaml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  pkg/config/static/static_config.go
  pkg/provider/acme/account.go
  pkg/provider/acme/challenge_http.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/tls/tlsmanager.go
Labels: area/acme, bot/light-review, kind/bug/fix, size/M, status/3-needs-merge

#7247 Prepare release 2.2.9
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7248 Prepare release v2.2.10
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7249 Merge current v2.2 branch into v2.3
  CHANGELOG.md
  docs/content/https/acme.md
  docs/content/https/ref-acme.toml
  docs/content/https/ref-acme.txt
  docs/content/https/ref-acme.yaml
  docs/content/migration/v2.md
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  pkg/config/dynamic/middlewares.go
  pkg/config/static/static_config.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
  pkg/middlewares/headers/header.go
  pkg/middlewares/headers/header_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/headers_test.go
  pkg/middlewares/headers/responsewriter.go
  pkg/middlewares/headers/secure.go
  pkg/middlewares/headers/secure_test.go
  pkg/provider/acme/account.go
  pkg/provider/acme/challenge_http.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/responsemodifiers/headers.go
  pkg/responsemodifiers/log.go
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
  pkg/server/middleware/middlewares.go
  pkg/server/router/router.go
  pkg/server/router/router_test.go
  pkg/server/routerfactory.go
  pkg/server/service/internalhandler.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/server/service/service.go
  pkg/server/service/service_test.go
  pkg/tls/tlsmanager.go
Labels: size/L

#7252 fix: header middleware response writer.
  pkg/middlewares/headers/responsewriter.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7246 feat: allows to change the Pilot URL in the web UI in dev mode
  Makefile
  webui/Dockerfile
Labels: area/infrastructure, area/webui, kind/enhancement, size/S, status/2-needs-review, status/3-needs-merge

#7255 Improve plugins builder.
  pkg/plugins/builder.go
  pkg/server/middleware/middlewares.go
  pkg/server/middleware/plugins.go
  pkg/server/routerfactory.go
Labels: area/plugins, kind/enhancement, size/S, status/3-needs-merge

#7256 Prepare release v2.2.11
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7257 Merge current v2.2 branch into v2.3
  CHANGELOG.md
  docs/content/routing/services/index.md
  pkg/middlewares/headers/responsewriter.go
Labels: size/S

#7260 Prepare release v2.3.0-rc5
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7261 fixed typo in buffering.md docs
  docs/content/middlewares/buffering.md
Labels: area/documentation, area/middleware, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7262 doc: fix typo in health check options
  docs/content/routing/services/index.md
Labels: area/documentation, area/middleware, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7263 Merge current v2.3 branch into master
  CHANGELOG.md
  Makefile
  docs/content/https/acme.md
  docs/content/https/ref-acme.toml
  docs/content/https/ref-acme.txt
  docs/content/https/ref-acme.yaml
  docs/content/https/tls.md
  docs/content/migration/v1-to-v2.md
  docs/content/migration/v2.md
  docs/content/observability/access-logs.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/services/index.md
  go.mod
  go.sum
  pkg/config/dynamic/middlewares.go
  pkg/config/static/static_config.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
  pkg/middlewares/headers/header.go
  pkg/middlewares/headers/header_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/headers_test.go
  pkg/middlewares/headers/responsewriter.go
  pkg/middlewares/headers/secure.go
  pkg/middlewares/headers/secure_test.go
  pkg/plugins/builder.go
  pkg/provider/acme/account.go
  pkg/provider/acme/challenge_http.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/responsemodifiers/headers.go
  pkg/responsemodifiers/log.go
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
  pkg/server/middleware/middlewares.go
  pkg/server/middleware/plugins.go
  pkg/server/router/router.go
  pkg/server/router/router_test.go
  pkg/server/routerfactory.go
  pkg/server/service/internalhandler.go
  pkg/server/service/proxy.go
  pkg/server/service/proxy_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/server/service/service.go
  pkg/server/service/service_test.go
  pkg/tls/tlsmanager.go
  webui/Dockerfile
Labels: size/L

#7264 Change wording
  docs/content/middlewares/circuitbreaker.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7269 Improve documentation for usage of Kubernetes Ingress
  docs/content/https/tls.md
  docs/content/middlewares/overview.md
Labels: area/documentation, area/provider/k8s, size/S, status/3-needs-merge

#7272 Avoid Traefik Pilot iframe code in Traefik webui regarding notifications
  webui/package-lock.json
  webui/package.json
  webui/src/components/_commons/NavBar.vue
  webui/src/components/platform/PlatformAuthState.vue
  webui/src/components/platform/PlatformNotification.vue
  webui/src/components/platform/PlatformPanel.vue
  webui/src/pages/dashboard/Index.vue
  webui/src/store/platform/index.js
Labels: area/pilot, area/webui, kind/bug/fix, size/M, status/3-needs-merge

#7288 Merge current v2.2 branch into v2.3
  docs/content/contributing/data-collection.md
  docs/content/https/tls.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/overview.md
  docs/content/routing/services/index.md
Labels: area/middleware, size/S

#7287 Moves pilot outside the experimental section.
  cmd/traefik/plugins.go
  cmd/traefik/traefik.go
  pkg/config/static/experimental.go
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
Labels: area/pilot, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7286 chore: update linter.
  build.Dockerfile
  integration/docker_test.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
  pkg/provider/marathon/config.go
  pkg/tls/certificate_store_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/2-needs-review, status/3-needs-merge

#6951 feat: update more than one LoadBalancer ip
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/client_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/ingress, bot/need-human-merge, kind/enhancement, size/S, status/3-needs-merge

#7289 fix: uint64 alignment in go-kit.
  go.mod
  go.sum
  integration/resources/compose/k8s.yml
Labels: area/middleware/metrics, bot/light-review, kind/bug/fix, size/M, status/3-needs-merge

#7290 Add the ingressclass resource in the ingress RBAC documentation
  docs/content/routing/providers/kubernetes-ingress.md
Labels: area/documentation, area/provider/k8s, bot/light-review, size/S, status/3-needs-merge

#7296 Prepare release v2.3.0-rc6
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7304 fix: start of Traefik Pilot
  cmd/traefik/plugins.go
  netlify.toml
Labels: area/pilot, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7309 fix: pilot metrics unit for req duration.
  pkg/metrics/pilot.go
Labels: area/pilot, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7311 Prepare release v2.3.0-rc7
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7315 Fix typo "CA's" instead of "CA:s"
  docs/basics.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7174 Do not SetError on tracing event when whitelist allowed request
  middlewares/ip_whitelister.go
Labels: area/middleware, area/middleware/tracing, kind/bug/fix, size/S, status/3-needs-merge

#7325 chore: apply new documentation style.
  .github/CODEOWNERS
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  cmd/traefik/traefik.go
  contrib/systemd/traefik.service
  docs/CNAME
  docs/configuration/backends/docker.md
  docs/index.md
  examples/quickstart/README.md
  mkdocs.yml
  script/docs-verify-docker-image/validate.sh
  webui/src/app/components/header/header.component.html
Labels: area/documentation, area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7328 Fix documentation deployment.
  .travis.yml
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7327 chore: apply new documentation style.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CONTRIBUTING.md
  README.md
  cmd/traefik/traefik.go
  contrib/systemd/traefik.service
  docs/content/CNAME
  docs/content/assets/img/traefik.icon.png
  docs/content/assets/img/traefik.logo.horizontal.png
  docs/content/assets/img/traefik.logo.png
  docs/content/assets/img/traefikproxy-icon-color.png
  docs/content/assets/img/traefikproxy-vertical-logo-color.svg
  docs/content/assets/styles/header.css
  docs/content/assets/styles/product-switcher.css
  docs/content/contributing/advocating.md
  docs/content/contributing/documentation.md
  docs/content/contributing/submitting-issues.md
  docs/content/getting-started/install-traefik.md
  docs/content/glossary.md
  docs/content/index.md
  docs/content/migration/v1-to-v2.md
  docs/content/plugins/overview.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/overview.md
  docs/content/reference/dynamic-configuration/file.yaml
  docs/mkdocs.yml
  docs/scripts/verify.sh
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo-long.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
  webui/src/components/_commons/NavBar.vue
Labels: area/documentation, area/infrastructure, bot/light-review, kind/enhancement, size/L, status/3-needs-merge

#7319 Fix syntax in yaml config examples
  docs/content/providers/kubernetes-crd.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7329 Fix incorrect syntax in yaml config examples
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/docker.md
  docs/content/routing/services/index.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7331 Fix yaml documentation
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/docker.md
  docs/content/routing/services/index.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7332 Fix consul catalog router tag example
  docs/content/providers/consul-catalog.md
Labels: area/documentation, area/provider/consul, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7333 fix: precheck function.
  pkg/provider/acme/provider.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#7334 Prepare release v2.3.0
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7335 Merge current v2.3 branch into master
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cmd/traefik/plugins.go
  cmd/traefik/traefik.go
  contrib/systemd/traefik.service
  docs/content/CNAME
  docs/content/assets/img/traefik.icon.png
  docs/content/assets/img/traefik.logo.horizontal.png
  docs/content/assets/img/traefik.logo.png
  docs/content/assets/img/traefikproxy-icon-color.png
  docs/content/assets/img/traefikproxy-vertical-logo-color.svg
  docs/content/assets/styles/header.css
  docs/content/assets/styles/product-switcher.css
  docs/content/contributing/advocating.md
  docs/content/contributing/documentation.md
  docs/content/contributing/submitting-issues.md
  docs/content/getting-started/install-traefik.md
  docs/content/glossary.md
  docs/content/index.md
  docs/content/migration/v1-to-v2.md
  docs/content/plugins/overview.md
  docs/content/providers/consul-catalog.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/overview.md
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/routing/providers/docker.md
  docs/content/routing/services/index.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo-long.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
  pkg/metrics/pilot.go
  pkg/provider/acme/provider.go
  webui/src/components/_commons/NavBar.vue
Labels: size/L

#7339 Removes invalid items in the changelog.
  CHANGELOG.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7344 restore traefik logo
  docs/content/assets/img/traefik.logo.png
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7346 Merge current v2.3 branch into master
  CHANGELOG.md
  docs/content/assets/img/traefik.logo.png
Labels: size/S

#7348 chore: Added configuration files for generating the changelog of a release.
  script/gcg/readme.md
  script/gcg/traefik-bugfix.toml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
  script/gcg/traefik-rc-first.toml
  script/gcg/traefik-rc-new.toml
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/M, status/3-needs-merge

#7345 Fix default value of docker client timeout
  docs/content/providers/docker.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/config/static/static_config.go
  pkg/provider/docker/docker.go
Labels: area/provider/docker, kind/bug/fix, size/S, status/3-needs-merge

#7352 Update of the helm repo localisation
  docs/content/getting-started/install-traefik.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#6461 Re-add server up metrics
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
  pkg/server/service/service.go
Labels: area/middleware/metrics, kind/enhancement, size/S, status/3-needs-merge

#7364 Fix blank webui on some browsers
  webui/package-lock.json
  webui/package.json
  webui/src/components/_commons/NavBar.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7369 Prepare release v2.3.1
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7355 acme: Fix race condition in LocalStore during saving.
  pkg/provider/acme/local_store.go
  pkg/provider/acme/local_store_test.go
Labels: area/acme, kind/bug/fix, size/M, status/3-needs-merge
