Repository traefik/traefik, pull requests merged in 2020-08, with the labels that each got.

#7131 doc: replace underscore by hyphen for k8s metadata names.
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7134 kubernetes-crd: fix whitespace in configuration examples
  docs/content/routing/providers/kubernetes-crd.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7125 chore(webui): upgrade nodejs to Node current LTS
  webui/Dockerfile
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7145 Improve region resolution for ECS provider
  docs/content/providers/ecs.md
  pkg/provider/ecs/ecs.go
Labels: area/provider/ecs, kind/bug/fix, size/S, status/3-needs-merge

#7155 Add mixtus for documentation
  .travis.yml
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7156 Add mixtus for documentation
  .travis.yml
Labels: area/documentation, area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7139 Pilot metrics provider
  cmd/traefik/traefik.go
  pkg/metrics/pilot.go
  pkg/metrics/pilot_test.go
  pkg/pilot/pilot.go
  pkg/pilot/pilot_test.go
Labels: area/middleware/metrics, area/pilot, kind/enhancement, size/L, status/3-needs-merge

#7160 Merge current v2.2 branch into v2.3
  .travis.yml
  docs/content/assets/img/traefik.logo.horizontal.png
  docs/content/assets/styles/content.css
  docs/content/assets/styles/extra.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/content/migration/v1-to-v2.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
  docs/theme/main.html
  docs/theme/partials/containous-header.html
  docs/theme/partials/product-switcher.html
  webui/Dockerfile
Labels: size/L

#6664 Allows multi-level KV prefixes
  pkg/config/kv/kv_node.go
  pkg/config/kv/kv_test.go
Labels: area/provider/kv, kind/enhancement, size/S, status/3-needs-merge

#7172 doc: fix dead link.
  docs/content/providers/docker.md
Labels: area/documentation, area/provider/docker, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7175 Merge current v2.2 branch into v2.3
  docs/content/providers/docker.md
Labels: size/S

#7181 doc: fix typo in migration guide
  docs/content/migration/v1-to-v2.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7169 Update to go1.15
  .semaphoreci/setup.sh
  build.Dockerfile
  docs/content/migration/v2.md
  exp.Dockerfile
  go.mod
  go.sum
  integration/fixtures/https/generate_cert.sh
  integration/fixtures/https/snitest.com.cert
  integration/fixtures/https/snitest.com.key
  integration/fixtures/https/snitest.org.cert
  integration/fixtures/https/snitest.org.key
  integration/fixtures/https/uppercase_wildcard.www.snitest.com.cert
  integration/fixtures/https/uppercase_wildcard.www.snitest.com.key
  integration/fixtures/https/wildcard.snitest.com.cert
  integration/fixtures/https/wildcard.snitest.com.key
  integration/fixtures/https/wildcard.www.snitest.com.cert
  integration/fixtures/https/wildcard.www.snitest.com.key
  integration/fixtures/https/www.snitest.com.cert
  integration/fixtures/https/www.snitest.com.key
  pkg/metrics/statsd_test.go
  pkg/middlewares/auth/forward_test.go
  pkg/server/server_entrypoint_tcp.go
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#7198 Update jaeger-client-go dependency to v2.25.0
  docs/content/observability/tracing/jaeger.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  pkg/tracing/jaeger/jaeger.go
Labels: area/middleware/tracing, bot/light-review, size/S, status/3-needs-merge

#7199 docs: add missing apigroup to Kubernetes RBAC
  docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7201 Prepare release v2.3.0-rc4
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7200 Add ability to dismiss pilot notification
  webui/src/components/platform/PlatformNotification.vue
  webui/src/store/platform/index.js
Labels: area/pilot, area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7178 doc: added tz section to access log
  docs/content/observability/access-logs.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#7206 doc: Minor language improvement in TLS documentation
  docs/content/https/tls.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#6414 Fix & improve Grafana dashboards
  contrib/grafana/traefik-kubernetes.json
  contrib/grafana/traefik.json
Labels: area/infrastructure, area/middleware/metrics, size/L, status/3-needs-merge

#7214 Reorder migrations for v2 minor upgrades
  docs/content/migration/v2.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7218 Merge current v2.2 branch into v2.3
  docs/content/https/tls.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
Labels: size/S

#7094 Support configuring a HTTP client timeout in the Docker provider
  docs/content/providers/docker.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/anonymize/anonymize_config_test.go
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/static/static_config.go
  pkg/provider/docker/docker.go
Labels: area/logs, area/middleware, area/provider/docker, kind/enhancement, size/L, status/3-needs-merge
