Repository traefik/traefik, pull requests merged in 2020-10, with the labels that each got.

#7375 fix: udp json struct tag
  pkg/config/runtime/runtime.go
Labels: area/udp, kind/bug/fix, size/S, status/3-needs-merge

#7390 Fix broken logo
  README.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7226 Filter ForwardAuth request headers
  docs/content/middlewares/forwardauth.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/marathon-labels.json
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/config/label/label_test.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/auth/forward_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/provider/kv/kv_test.go
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: area/authentication, area/middleware, kind/enhancement, size/S, status/3-needs-merge

#7394 Fix containous links in readme
  CODE_OF_CONDUCT.md
  README.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7398 fix: versions in the PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/documentation, area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7397 doc: add YAML sample.
  docs/content/getting-started/install-traefik.md
  traefik.sample.yml
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#7399 fix: pilot static configuration documentation
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7387 fix: use provider keytype instead of account keytype.
  docs/content/https/acme.md
  pkg/provider/acme/provider.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#7400 fix: restrict protocol for TLS Challenge.
  pkg/tls/tlsmanager.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#7401 Merge current v2.3 branch into master
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  docs/content/getting-started/install-traefik.md
  docs/content/https/acme.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/config/runtime/runtime.go
  pkg/provider/acme/local_store.go
  pkg/provider/acme/local_store_test.go
  pkg/provider/acme/provider.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_serverstransport.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
  pkg/tls/tlsmanager.go
  script/gcg/readme.md
  script/gcg/traefik-bugfix.toml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
  script/gcg/traefik-rc-first.toml
  script/gcg/traefik-rc-new.toml
  traefik.sample.yml
  webui/package-lock.json
  webui/package.json
  webui/src/components/_commons/NavBar.vue
Labels: size/M

#7402 Bump k8s client to v0.19.2
  go.mod
  go.sum
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/register.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/ingress/client.go
Labels: area/provider/k8s, kind/enhancement, size/M, status/3-needs-merge

#7403 fix: flaky integration tests
  integration/access_log_test.go
  integration/acme_test.go
  integration/consul_catalog_test.go
  integration/consul_test.go
  integration/docker_compose_test.go
  integration/docker_test.go
  integration/error_pages_test.go
  integration/etcd_test.go
  integration/file_test.go
  integration/grpc_test.go
  integration/headers_test.go
  integration/healthcheck_test.go
  integration/hostresolver_test.go
  integration/http_test.go
  integration/https_test.go
  integration/integration_test.go
  integration/k8s_test.go
  integration/keepalive_test.go
  integration/log_rotation_test.go
  integration/marathon15_test.go
  integration/marathon_test.go
  integration/proxy_protocol_test.go
  integration/ratelimit_test.go
  integration/redis_test.go
  integration/rest_test.go
  integration/retry_test.go
  integration/simple_test.go
  integration/tcp_test.go
  integration/timeout_test.go
  integration/tls_client_headers_test.go
  integration/tracing_test.go
  integration/udp_test.go
  integration/websocket_test.go
  integration/zk_test.go
Labels: area/infrastructure, kind/bug/fix, size/M, status/3-needs-merge

#7405 Merge current v2.3 branch into master
  integration/access_log_test.go
  integration/acme_test.go
  integration/consul_catalog_test.go
  integration/consul_test.go
  integration/docker_compose_test.go
  integration/docker_test.go
  integration/error_pages_test.go
  integration/etcd_test.go
  integration/file_test.go
  integration/grpc_test.go
  integration/headers_test.go
  integration/healthcheck_test.go
  integration/hostresolver_test.go
  integration/http_test.go
  integration/https_test.go
  integration/integration_test.go
  integration/k8s_test.go
  integration/keepalive_test.go
  integration/log_rotation_test.go
  integration/marathon15_test.go
  integration/marathon_test.go
  integration/proxy_protocol_test.go
  integration/ratelimit_test.go
  integration/redis_test.go
  integration/rest_test.go
  integration/retry_test.go
  integration/simple_test.go
  integration/tcp_test.go
  integration/timeout_test.go
  integration/tls_client_headers_test.go
  integration/tracing_test.go
  integration/udp_test.go
  integration/websocket_test.go
  integration/zk_test.go
Labels: size/M

#7415 fix: kv doc reference
  docs/content/reference/dynamic-configuration/kv-ref.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7422 Adding details about the default TLS options to the documentation
  docs/content/https/tls.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#7423 Moving Provider Namespace documentation topic to Configuration Discovery section
  docs/content/middlewares/overview.md
  docs/content/providers/overview.md
Labels: area/documentation, area/middleware, kind/enhancement, size/M, status/3-needs-merge

#7426 fix: update Yaegi to v0.9.4
  go.mod
  go.sum
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7427 Revise Traefik Pilot documentation section
  docs/content/assets/styles/product-switcher.css
  docs/content/plugins/index.md
  docs/content/plugins/overview.md
  docs/content/plugins/using-plugins.md
  docs/mkdocs.yml
  docs/theme/partials/product-switcher.html
Labels: area/documentation, area/plugins, bot/light-review, size/M, status/3-needs-merge

#7429 fix: Consul Catalog address documentation.
  docs/content/providers/consul-catalog.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/provider/consulcatalog/consul_catalog.go
Labels: area/documentation, area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#7434 Prepare release v2.3.2
  .gitignore
  CHANGELOG.md
  pkg/middlewares/accesslog/logger_formatters_test.go
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7424 Fix ingress documentation
  docs/content/routing/entrypoints.md
  docs/content/routing/providers/kubernetes-ingress.md
Labels: area/documentation, area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/M, status/3-needs-merge

#7441 fix typo in providers overview documentation
  docs/content/providers/overview.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7444 Resolve broken URLs causing make docs to fail
  docs/content/contributing/maintainers.md
  docs/content/providers/docker.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7447 Clarify time-based field units
  docs/content/observability/access-logs.md
Labels: area/documentation, area/logs, kind/enhancement, size/S, status/3-needs-merge

#7435 add links to contributors guide
  docs/content/contributing/maintainers.md
  docs/content/contributing/submitting-pull-requests.md
Labels: area/documentation, size/M, status/3-needs-merge

#7436 Use timezone without daylight saving time for logger formatter tests
  pkg/middlewares/accesslog/logger_formatters_test.go
Labels: area/infrastructure, area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7450 Add missed tls config for yaml example
  docs/content/routing/overview.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7451 fix: update Yaegi to v0.9.4
  go.mod
  go.sum
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7453 Merge current v2.3 branch into master
  .gitignore
  CHANGELOG.md
  docs/content/assets/styles/product-switcher.css
  docs/content/contributing/maintainers.md
  docs/content/contributing/submitting-pull-requests.md
  docs/content/https/tls.md
  docs/content/middlewares/overview.md
  docs/content/observability/access-logs.md
  docs/content/plugins/index.md
  docs/content/plugins/overview.md
  docs/content/plugins/using-plugins.md
  docs/content/providers/consul-catalog.md
  docs/content/providers/docker.md
  docs/content/providers/overview.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/routing/entrypoints.md
  docs/content/routing/overview.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/mkdocs.yml
  docs/theme/partials/product-switcher.html
  go.mod
  go.sum
  pkg/middlewares/accesslog/logger_formatters_test.go
  pkg/provider/consulcatalog/consul_catalog.go
  script/gcg/traefik-bugfix.toml
Labels: size/L

#7464 Propose kevinpollet to Maintainers
  docs/content/contributing/maintainers.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7469 fix documentation
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
Labels: area/documentation, area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#7477 fix: exclude protected link from doc verify
  docs/scripts/verify.sh
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7472 Merge current v2.3 branch into master
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/scripts/verify.sh
Labels: area/provider/k8s, size/S

#7410 Ignore errors when setting keepalive period is not supported by the system
  pkg/server/server_entrypoint_tcp.go
Labels: area/tcp, kind/bug/fix, size/S, status/3-needs-merge

#6881 Allow to use regular expressions for `AccessControlAllowOriginList`
  docs/content/middlewares/headers.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  pkg/config/dynamic/middlewares.go
  pkg/config/label/label_test.go
  pkg/middlewares/headers/header.go
  pkg/middlewares/headers/header_test.go
  pkg/middlewares/headers/headers.go
  pkg/provider/kv/kv_test.go
Labels: area/middleware, kind/enhancement, size/S, status/3-needs-merge

#7449 Middlewares: add forwardAuth.authResponseHeadersRegex
  docs/content/middlewares/forwardauth.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/dynamic/middlewares.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/auth/forward_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
Labels: area/authentication, area/middleware, kind/enhancement, size/M, status/3-needs-merge

#7458 acme: new HTTP and TLS challenges implementations.
  cmd/traefik/traefik.go
  pkg/provider/acme/challenge_http.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/local_store.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/store.go
  pkg/provider/traefik/internal.go
  pkg/server/aggregator.go
  pkg/server/aggregator_test.go
  pkg/server/routerfactory_test.go
  pkg/server/service/internalhandler.go
  pkg/server/service/managerfactory.go
  pkg/tls/tlsmanager.go
Labels: area/acme, kind/enhancement, size/L, status/3-needs-merge

#7482 Improve anonymize configuration
  pkg/anonymize/anonymize.go
  pkg/anonymize/anonymize_config_test.go
  pkg/anonymize/anonymize_doOnJSON_test.go
  pkg/anonymize/anonymize_doOnStruct_test.go
  pkg/anonymize/testdata/anonymized-static-config.json
  pkg/anonymize/testdata/example.json
  pkg/anonymize/testdata/expected.json
  pkg/config/static/entrypoints.go
  pkg/config/static/experimental.go
  pkg/config/static/static_config.go
  pkg/ping/ping.go
  pkg/plugins/types.go
  pkg/provider/acme/provider.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/http/http.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kv/consul/consul.go
  pkg/provider/kv/etcd/etcd.go
  pkg/provider/kv/redis/redis.go
  pkg/provider/kv/zk/zk.go
  pkg/provider/marathon/marathon.go
  pkg/provider/rancher/rancher.go
  pkg/tracing/datadog/datadog.go
  pkg/tracing/elastic/elastic.go
  pkg/tracing/jaeger/jaeger.go
  pkg/types/logs.go
  pkg/types/metrics.go
  pkg/types/tls.go
Labels: kind/enhancement, size/L, status/3-needs-merge

#7483 Enable stats collection when pilot is enabled
  docs/content/contributing/data-collection.md
  pkg/config/static/static_config.go
Labels: area/pilot, kind/enhancement, size/S, status/3-needs-merge

#7392 Set kubernetes client User-Agent to something meaningful
  pkg/provider/kubernetes/crd/client.go
  pkg/provider/kubernetes/ingress/client.go
Labels: area/provider/k8s, area/provider/k8s/ingress, size/S, status/3-needs-merge
