Repository traefik/traefik, pull requests merged in 2020-07, with the labels that each got.

#6604 Allow multiple secure middlewares to operate independently
  integration/fixtures/headers/secure_multiple.toml
  integration/headers_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/headers_test.go
  pkg/responsemodifiers/headers.go
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
Labels: area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#6631 Backport "Same Configuration Check" from master
  server/server_configuration.go
  server/server_configuration_test.go
Labels: kind/bug/fix, size/S, status/3-needs-merge

#6977 Minor fix to Go templating documentation
  docs/content/providers/file.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#6952 Fix log field names in documentation
  docs/content/observability/access-logs.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#6967 Update basicauth.md
  docs/content/middlewares/basicauth.md
Labels: area/documentation, area/middleware, kind/enhancement, size/S, status/3-needs-merge

#6938 Fix sticky cookie ingress annotation doc
  docs/content/routing/providers/kubernetes-ingress.md
  pkg/provider/kubernetes/ingress/annotations_test.go
Labels: area/documentation, area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#6964 Fix statement about lego _FILE env var
  docs/content/https/acme.md
Labels: area/acme, area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#6696 Add custom ping http code when Traefik is terminating
  docs/content/operations/ping.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  integration/fixtures/custom_ping_termination_status_code.toml
  integration/simple_test.go
  pkg/ping/ping.go
Labels: area/api, kind/enhancement, size/M, status/3-needs-merge

#6983 fix certResolver typo
  docs/content/https/include-acme-multiple-domains-from-rule-example.md
  docs/content/https/include-acme-single-domain-example.md
Labels: area/acme, area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#6775 Remove checkStringQuoteValidity in loadIngressRouteConf
  pkg/provider/kubernetes/crd/fixtures/tcp/with_bad_host_rule.yml
  pkg/provider/kubernetes/crd/fixtures/with_bad_host_rule.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-bad-host-syntax_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-a-bad-path-syntax_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-only-a-bad-host-syntax_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-only-a-bad-path-syntax_ingress.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#6747 Add missing accessControlAllowOrigin list to middleware view
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#6979 Fix race condition issues with provided dynamic configuration
  pkg/server/configurationwatcher.go
  pkg/server/configurationwatcher_test.go
Labels: area/provider, kind/bug/fix, size/M, status/3-needs-merge

#6988 Update go-acme/lego to v3.8.0
  docs/content/https/acme.md
  go.mod
  go.sum
Labels: area/acme, bot/light-review, kind/bug/fix, status/3-needs-merge

#6946 Add iOS specific icons
  webui/src/index.template.html
Labels: area/webui, kind/enhancement, size/S, status/3-needs-merge

#6990 Change doc analytics.
  docs/mkdocs.yml
  docs/theme/main.html
Labels: area/documentation, area/infrastructure, bot/light-review, kind/enhancement, status/3-needs-merge

#6867 added required quotes to domains config
  docs/content/https/include-acme-multiple-domains-example.md
Labels: area/acme, kind/bug/fix, size/S, status/2-needs-review, status/3-needs-merge

#6874 Update Dashboard examples and move it after 'Router Rule' section
  docs/content/operations/dashboard.md
  docs/content/operations/include-dashboard-examples.md
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#7008 Disable domain fronting
  cmd/traefik/traefik.go
  docs/content/https/tls.md
  docs/content/migration/v2.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/routers/index.md
  integration/fixtures/grpc/config.toml
  integration/fixtures/grpc/config_h2c_termination.toml
  integration/fixtures/grpc/config_insecure.toml
  integration/fixtures/grpc/config_retry.toml
  integration/grpc_test.go
  pkg/config/static/static_config.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/server/router/router_test.go
  pkg/tcp/router.go
  traefik.sample.toml
Labels: area/rules, area/server, area/tls, kind/bug/fix, size/L, status/3-needs-merge

#6939 Fix triggering multiple concurrent requests to ACME
  pkg/provider/acme/provider.go
Labels: area/acme, kind/bug/fix, size/M, status/3-needs-merge

#7011 Prepare release v2.2.2
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7016 Fix panic when using chain middleware.
  pkg/responsemodifiers/response_modifier.go
  pkg/responsemodifiers/response_modifier_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7019 Prepare release v2.2.3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7027 Change the default value of insecureSNI
  docs/content/https/tls.md
  docs/content/migration/v2.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/config/static/static_config.go
Labels: area/tls, kind/bug/fix, size/M, status/3-needs-merge

#7028 Prepare release v2.2.4
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7037 Fix default value for InsecureSNI when global is not set
  cmd/configuration.go
  pkg/config/static/static_config.go
Labels: area/tls, kind/bug/fix, status/3-needs-merge

#7034 fix k8s crd to read contentType middleware into dynamic config
  pkg/provider/kubernetes/crd/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#7039 Revert domain fronting fix
  cmd/configuration.go
  cmd/traefik/traefik.go
  docs/content/https/tls.md
  docs/content/migration/v2.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/routers/index.md
  integration/fixtures/grpc/config.toml
  integration/fixtures/grpc/config_h2c_termination.toml
  integration/fixtures/grpc/config_insecure.toml
  integration/fixtures/grpc/config_retry.toml
  integration/grpc_test.go
  pkg/config/static/static_config.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/server/router/router_test.go
  pkg/tcp/router.go
  traefik.sample.toml
Labels: area/rules, area/server, area/tls, kind/bug/fix, size/L, status/3-needs-merge

#7042 Prepare release v2.2.5
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7049 fix: documentation references.
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/config/static/entrypoints.go
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7052 Merge current v2.2 branch into master
  CHANGELOG.md
  cmd/traefik/traefik.go
  docs/content/https/tls.md
  docs/content/migration/v2.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/routers/index.md
  integration/fixtures/grpc/config.toml
  integration/fixtures/grpc/config_h2c_termination.toml
  integration/fixtures/grpc/config_insecure.toml
  integration/fixtures/grpc/config_retry.toml
  integration/grpc_test.go
  pkg/config/static/entrypoints.go
  pkg/config/static/static_config.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/server/router/router_test.go
  pkg/tcp/router.go
  traefik.sample.toml
Labels: size/L

#7054 Prepare release v1.7.25
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#6749 Add AWS ECS provider
  docs/content/providers/ecs.md
  docs/content/reference/dynamic-configuration/ecs.md
  docs/content/reference/dynamic-configuration/ecs.yml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/providers/ecs.md
  docs/mkdocs.yml
  go.mod
  pkg/config/static/static_config.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/ecs/builder_test.go
  pkg/provider/ecs/config.go
  pkg/provider/ecs/config_test.go
  pkg/provider/ecs/ecs.go
  pkg/provider/ecs/ecs_test.go
  pkg/provider/ecs/label.go
  webui/src/statics/providers/ecs.svg
Labels: area/provider/ecs, kind/enhancement, size/L, status/3-needs-merge

#6976 Add HTTP Provider
  docs/content/providers/http.md
  docs/content/providers/overview.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/mkdocs.yml
  integration/fixtures/http/simple.toml
  integration/http_test.go
  integration/integration_test.go
  pkg/config/static/static_config.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/http/http.go
  pkg/provider/http/http_test.go
  webui/src/statics/providers/http.svg
Labels: area/provider, kind/enhancement, size/L, status/3-needs-merge

#6831 Add new ingressClass support to ingress provider
  docs/content/providers/kubernetes-ingress.md
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingressClass_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingressClass_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingressClass_ingressclass.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingressClass_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-missing-ingressClass_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-missing-ingressClass_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-missing-ingressClass_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/provider/kubernetes/k8s/parser.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/enhancement, size/L, status/3-needs-merge

#7055 Prepare release v2.3.0-rc1
  .semaphoreci/vars
  .travis.yml
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/migration/v2.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#6483 Add example for entrypoint on one ip address
  docs/content/routing/entrypoints.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#7047 Get Entrypoints Port Address without protocol for redirect
  pkg/provider/traefik/fixtures/redirection_with_protocol.json
  pkg/provider/traefik/internal.go
  pkg/provider/traefik/internal_test.go
Labels: area/provider, kind/bug/fix, size/S, status/3-needs-merge

#6900 fix: access logs header names filtering is case insensitive
  integration/helloworld/helloworld.pb.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
Labels: area/logs, kind/bug/fix, size/M, status/3-needs-merge

#7058 file parser: skip nil value.
  pkg/config/file/raw_node.go
  pkg/config/file/raw_node_test.go
Labels: area/provider, kind/bug/fix, size/S, status/3-needs-merge

#7064 Fix domain fronting
  docs/content/routing/routers/index.md
  integration/acme_test.go
  integration/fixtures/https/https_domain_fronting.toml
  integration/headers_test.go
  integration/https_test.go
  pkg/server/router/tcp/router.go
Labels: area/tls, kind/bug/fix, size/M, status/3-needs-merge

#7066 Prepare release v2.2.6
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7072 prefer NoError/Error over Nil/NotNil
  pkg/healthcheck/healthcheck_test.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/server/middleware/middlewares_test.go
  pkg/server/service/tcp/service_test.go
  pkg/server/service/udp/service_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7071 fix: drop host port to compare with SNI.
  integration/https_test.go
  pkg/server/router/tcp/router.go
  pkg/tcp/router.go
Labels: area/server, area/tls, kind/bug/fix, size/S, status/2-needs-review, status/3-needs-merge

#7079 Prepare release 2.2.7
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7065 Use semantic versioning to enable ingress class support
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#7083 Add migration documentation for IngressClass
  docs/content/migration/v2.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  pkg/tls/certificate_store.go
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#7086 Merge current v2.2 branch into v2.3
  CHANGELOG.md
  docs/content/https/acme.md
  docs/content/routing/entrypoints.md
  docs/content/routing/routers/index.md
  integration/acme_test.go
  integration/fixtures/https/https_domain_fronting.toml
  integration/headers_test.go
  integration/https_test.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/provider/traefik/fixtures/redirection_with_protocol.json
  pkg/provider/traefik/internal.go
  pkg/provider/traefik/internal_test.go
  pkg/server/router/tcp/router.go
  pkg/tcp/router.go
Labels: size/L

#7090 Change apiVersion to apps/v1 in examples/k8s/cheese-deployments.yaml
  examples/k8s/cheese-deployments.yaml
Labels: area/documentation, area/provider/k8s, area/provider/k8s/ingress, kind/enhancement, size/S, status/3-needs-merge

#7101 spelling(docs/content/routing/providers/docker.md)
  docs/content/https/acme.md
  docs/content/routing/providers/docker.md
Labels: area/documentation, area/provider/docker, kind/bug/fix, size/S, status/3-needs-merge

#7109 fix: clean X-Forwarded-Prefix header for the dashboard.
  pkg/api/dashboard.go
  pkg/api/dashboard_test.go
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7108 fix: clean X-Forwarded-Prefix header for the dashboard.
  api/dashboard.go
  api/dashboard_test.go
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7107 Fix documenation for ECS
  docs/content/providers/ecs.md
  integration/helloworld/helloworld.pb.go
Labels: area/documentation, area/provider/ecs, kind/bug/fix, size/S, status/3-needs-merge

#7068 doc: add name of used key for kubernetes client auth
  docs/content/https/tls.md
Labels: area/documentation, area/provider/k8s, kind/enhancement, size/S, status/3-needs-merge

#7114 Prepare release v1.7.26
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7115 Prepare release v2.2.8
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7087 Support Kubernetes Ingress pathType
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/kubernetes-ingress.md
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/L, status/3-needs-merge

#7116 Merge current v2.2 branch into v2.3
  CHANGELOG.md
  docs/content/https/tls.md
  docs/content/routing/providers/docker.md
  pkg/api/dashboard.go
  pkg/api/dashboard_test.go
Labels: size/M

#7117 Prepare release v2.3.0-rc3
  CHANGELOG.md
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7122 Merge current v2.3 branch into master
  .goreleaser.yml
  CHANGELOG.md
  docs/content/https/acme.md
  docs/content/https/tls.md
  docs/content/migration/v2.md
  docs/content/plugins/overview.md
  docs/content/plugins/using-plugins.md
  docs/content/providers/ecs.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  docs/content/routing/entrypoints.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/routing/routers/index.md
  integration/acme_test.go
  integration/fixtures/https/https_domain_fronting.toml
  integration/headers_test.go
  integration/helloworld/helloworld.pb.go
  integration/https_test.go
  pkg/api/dashboard.go
  pkg/api/dashboard_test.go
  pkg/config/file/raw_node.go
  pkg/config/file/raw_node_test.go
  pkg/healthcheck/healthcheck_test.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-empty-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-exact-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-implementationSpecific-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-ingress-annotation_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-no-pathType_service.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/v18-Ingress-with-prefix-pathType_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/provider/traefik/fixtures/redirection_with_protocol.json
  pkg/provider/traefik/internal.go
  pkg/provider/traefik/internal_test.go
  pkg/server/middleware/middlewares_test.go
  pkg/server/router/tcp/router.go
  pkg/server/service/tcp/service_test.go
  pkg/server/service/udp/service_test.go
  pkg/tcp/router.go
  pkg/tls/certificate_store.go
Labels: size/L

#7110 doc: add security policies.
  README.md
  SECURITY.md
Labels: area/documentation, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7124 Harmonize docs
  docs/content/assets/img/traefik.logo.horizontal.png
  docs/content/assets/styles/content.css
  docs/content/assets/styles/extra.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/mkdocs.yml
  docs/scripts/verify.sh
  docs/theme/main.html
  docs/theme/partials/containous-header.html
  docs/theme/partials/product-switcher.html
Labels: area/documentation, kind/enhancement, size/L, status/3-needs-merge
