Repository traefik/traefik, pull requests merged in 2021-08, with the labels that each got.

#8325 Merge back v2.4 into v2.5
  CHANGELOG.md
  pkg/middlewares/auth/forward.go
  pkg/middlewares/connectionheader/connectionheader.go
  pkg/middlewares/connectionheader/connectionheader_test.go
  pkg/middlewares/headers/headers.go
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, size/M

#8326 Prepare release v2.5.0-rc4
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8329 fix: change machine type for release
  .semaphore/semaphore.yml
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#8322 Avoid unauthorized midlleware cross namespace reference
  pkg/provider/kubernetes/crd/fixtures/with_middleware_cross_namespace.yml
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/provider/k8s/crd, area/provider/k8s

#8335 Remove unwanted trailing slash in key
  pkg/config/kv/kv_node.go
  pkg/config/kv/kv_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/provider/kv

#8333 Merge current v2.4 into v2.5
  .semaphore/semaphore.yml
  pkg/config/kv/kv_node.go
  pkg/config/kv/kv_test.go
  pkg/provider/kubernetes/crd/fixtures/with_middleware_cross_namespace.yml
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
Labels: size/S

#8348 redirect: fix comparison when explicit port request and implicit redirect port
  pkg/middlewares/redirect/redirect.go
  pkg/middlewares/redirect/redirect_regex.go
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/redirect/redirect_scheme_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#8355 Update Go version
  .github/workflows/build.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  build.Dockerfile
  docs/content/migration/v2.md
  exp.Dockerfile
  go.mod
  go.sum
  integration/retry_test.go
  pkg/ip/checker_test.go
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S

#8356 Prepare release v2.5.0-rc6
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#8357 fix: an example code error in doc
  docs/content/routing/providers/kv.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/provider/kv, bot/light-review

#8358 Update mkdocs dependency version
  docs/requirements.txt
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8360 Prepare release v2.4.14
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#8361 Merge current v2.4 into v2.5
  CHANGELOG.md
  docs/content/routing/providers/kv.md
  docs/requirements.txt
  pkg/middlewares/redirect/redirect.go
  pkg/middlewares/redirect/redirect_regex.go
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/redirect/redirect_scheme_test.go
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, size/M

#8339 Fix dashboard title for TCP middlewares
  webui/src/pages/_commons/RouterDetail.vue
Labels: status/3-needs-merge, area/webui, kind/bug/fix, size/S

#8362 Update Go version to v1.17
  .github/workflows/build.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  build.Dockerfile
  exp.Dockerfile
  go.mod
  go.sum
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#8364 Prepare release v2.5.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/providers/kubernetes-ingress.md
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: area/documentation, status/3-needs-merge, area/infrastructure, size/M, bot/light-review, area/provider/k8s

#8370 Fix Kubernetes Gateway API documentation links
  docs/content/providers/kubernetes-gateway.md
  docs/content/routing/providers/kubernetes-gateway.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/provider/k8s, area/provider/k8s/gatewayapi

#8372 Merge current v2.4 into v2.5
  docs/content/providers/kubernetes-gateway.md
  docs/content/routing/providers/kubernetes-gateway.md
  pkg/provider/kubernetes/gateway/kubernetes.go
Labels: area/infrastructure, size/S

#8350 Adds ContentType to middleware's overview table
  docs/content/middlewares/http/overview.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#8369 Adds MiddlewareTCP CRD documentation
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/routing/providers/kubernetes-crd.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/provider/k8s

#8374 Conditional CloseNotify in header middleware
  pkg/middlewares/headers/responsewriter.go
  pkg/middlewares/tracing/status_code.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware, area/http3

#8383 Makes ALPN protocols configurable
  docs/content/https/tls.md
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kubernetes-crd-resource.yml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  docs/content/routing/providers/kubernetes-crd.md
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/provider/kv/kv_test.go
  pkg/server/aggregator_test.go
  pkg/server/configurationwatcher_test.go
  pkg/tls/tls.go
  pkg/tls/tlsmanager.go
  pkg/tls/zz_generated.deepcopy.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/tls, bot/light-review, area/tcp, area/provider/k8s/crd, area/provider/k8s

#8385 Prepare release v2.5.1
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/2-needs-review, area/infrastructure, size/S, bot/light-review

#8402 Bumps alpine docker images to v1.14.1
  docs/check.Dockerfile
  docs/docs.Dockerfile
  exp.Dockerfile
Labels: status/3-needs-merge, area/provider/docker, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8408 Fix alpine docker image to version 3.14
  docs/check.Dockerfile
  docs/content/routing/providers/kubernetes-gateway.md
  docs/docs.Dockerfile
  exp.Dockerfile
Labels: status/3-needs-merge, area/provider/docker, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8409 Build experimental images
  .github/workflows/experimental.yaml
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8410 Fix experimental images workflow
  .github/workflows/experimental.yaml
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8395 Fix http scheme urls in documentation
  SECURITY.md
  docs/content/contributing/documentation.md
  docs/content/getting-started/quick-start.md
  docs/content/https/acme.md
  docs/content/providers/consul-catalog.md
  docs/content/providers/docker.md
  docs/content/providers/ecs.md
  docs/content/providers/file.md
  docs/content/providers/marathon.md
  docs/content/providers/rancher.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review
