Repository traefik/traefik, pull requests merged in 2021-12, with the labels that each got.

#8592 Support consul enterprise namespaces in consul catalog provider
  docs/content/providers/consul-catalog.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/consulcatalog/consul_catalog.go
Labels: kind/enhancement, status/3-needs-merge, area/provider/consul, size/S, area/provider/consulcatalog

#8607 Update go-acme/lego to v4.5.3
  go.mod
  go.sum
Labels: status/3-needs-merge, area/acme, kind/bug/fix, size/S, bot/light-review

#8619 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S, bot/light-review

#8624 require that secret is a valid PEM
  provider/kubernetes/fixtures/tLSSecretLoad_ingresses.yml
  provider/kubernetes/fixtures/tLSSecretLoad_secrets.yml
  provider/kubernetes/kubernetes.go
  provider/kubernetes/kubernetes_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/M, bot/light-review, area/provider/k8s

#8625 Prepare release v2.5.5
  .semaphore/semaphore.yml
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8626 Prepare release v1.7.34
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8596 fix: process all X-Forwarded-For headers in the request
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/forwardedheaders/forwarded_header_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#8635 chore: update golang.org/x/net dependency version
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/server

#8636 Correct documentation in middleware overview
  docs/content/middlewares/http/overview.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#8637 Fix passTLSClientCert CRD example name
  docs/content/middlewares/http/passtlsclientcert.md
Labels: area/documentation, status/3-needs-merge, size/S, area/middleware, bot/light-review

#8645 Merge back v2.5 into master
  .semaphore/semaphore.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  docs/content/middlewares/http/basicauth.md
  docs/content/middlewares/http/overview.md
  docs/content/middlewares/http/passtlsclientcert.md
  go.mod
  go.sum
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/forwardedheaders/forwarded_header_test.go
  pkg/plugins/builder.go
  pkg/plugins/providers.go
  script/gcg/traefik-bugfix.toml
Labels: size/M

#8646 Prepare release v2.6.0-rc1
  .semaphore/semaphore.yml
  CHANGELOG.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/providers/docker.md
  docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-rc-first.toml
Labels: area/documentation, status/3-needs-merge, size/M, bot/light-review

#8649 Add missing API endpoints documentation
  docs/content/operations/api.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, area/api, size/S

#8650 Update Yaegi to v0.11.2
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/plugins

#8652 fix: update goreleaser install link to use gist
  .semaphore/semaphore.yml
  build.Dockerfile
Labels: kind/bug/fix, area/infrastructure, size/S

#8651 Merge current v2.5 into v2.6
  .semaphore/semaphore.yml
  build.Dockerfile
  docs/content/operations/api.md
  go.mod
  go.sum
Labels: size/S

#8653 Prepare release v2.5.6
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8656 Update golangci-lint install script
  build.Dockerfile
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8665 Fix broken jaeger documentation link
  docs/content/observability/tracing/jaeger.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/middleware/tracing

#8664 Merge current v2.5 into v2.6
  CHANGELOG.md
  build.Dockerfile
  docs/content/observability/tracing/jaeger.md
  script/gcg/traefik-bugfix.toml
Labels: size/S

#8667 Remove go-bindata from semaphore
  .semaphore/semaphore.yml
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8666 Merge current v2.6 into master
  .semaphore/semaphore.yml
  CHANGELOG.md
  build.Dockerfile
  docs/content/observability/tracing/jaeger.md
  docs/content/operations/api.md
  go.mod
  go.sum
  script/gcg/traefik-bugfix.toml
Labels: size/S
