Repository traefik/traefik, pull requests merged in 2021-07, with the labels that each got.

#8258 accesslog: multiple times the same header name.
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
Labels: area/logs, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#8262 Fix: Add dedicated integration tests targets for CI
  Makefile
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8260 Disable Cross-Namespace by default for IngressRoute provider
  Makefile
  docs/content/migration/v2.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/bug/fix, size/S, status/3-needs-merge

#8238 Add *headers.responseModifier CloseNotify()
  pkg/middlewares/headers/responsewriter.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#8261 Disable ExternalName Services by default on Kubernetes providers
  docs/content/migration/v2.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  integration/fixtures/k8s_crd.toml
  pkg/provider/kubernetes/crd/fixtures/udp/services.yml
  pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_service.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/kubernetes_udp.go
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_service.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, size/L, status/3-needs-merge

#8243 Detect certificates content modifications
  docs/content/getting-started/faq.md
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/provider/file/fixtures/toml/tls_file_key.cert
  pkg/server/configurationwatcher.go
Labels: area/tls, kind/bug/fix, size/M, status/3-needs-merge

#8252 Ignore http 1.0 request host missing errors
  pkg/rules/rules.go
Labels: area/logs, kind/bug/fix, size/S, status/3-needs-merge

#8266 fix doc verify
  docs/scripts/verify.sh
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/2-needs-review

#8263 Merge current v2.4 into v2.5
  Makefile
  docs/content/getting-started/faq.md
  docs/content/migration/v2.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  integration/fixtures/k8s_crd.toml
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/middlewares/headers/responsewriter.go
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/provider/file/fixtures/toml/tls_file_key.cert
  pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_service.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/kubernetes_udp.go
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-IPv6-endpoints-externalname-enabled_service.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-service-with-externalName-enabled_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/rules/rules.go
  pkg/server/configurationwatcher.go
Labels: size/S

#7407 Add Support for Consul Connect
  docs/content/providers/consul-catalog.md
  docs/content/reference/dynamic-configuration/consul-catalog.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/routing/providers/consul-catalog.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/services/index.md
  go.mod
  go.sum
  integration/consul_catalog_test.go
  integration/fixtures/consul_catalog/connect.toml
  integration/fixtures/consul_catalog/connect_by_default.toml
  integration/fixtures/consul_catalog/connect_not_aware.toml
  integration/fixtures/k8s/01-traefik-crd.yml
  integration/resources/compose/consul_catalog.yml
  pkg/config/dynamic/http_config.go
  pkg/config/label/label_test.go
  pkg/provider/configuration.go
  pkg/provider/consulcatalog/config.go
  pkg/provider/consulcatalog/config_test.go
  pkg/provider/consulcatalog/connect_tls.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/consulcatalog/label.go
  pkg/provider/docker/config_test.go
  pkg/provider/ecs/config_test.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/gateway/kubernetes_test.go
  pkg/provider/marathon/config_test.go
  pkg/provider/rancher/config_test.go
  pkg/server/service/roundtripper.go
  pkg/tls/certificate.go
Labels: area/provider/consulcatalog, kind/enhancement, size/L, status/2-needs-review, status/3-needs-merge

#8269 Fix migration guide
  docs/content/migration/v2.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8268 Update code generator for plugin's dyn conf
  cmd/internal/gen/centrifuge.go
  go.mod
  go.sum
Labels: area/infrastructure, area/plugins, kind/enhancement, size/S, status/3-needs-merge

#8270 Prepare release v2.4.11
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8253 Update Gateway API version to v0.3.0
  docs/content/providers/kubernetes-gateway.md
  docs/content/reference/dynamic-configuration/networking.x-k8s.io_gatewayclasses.yaml
  docs/content/reference/dynamic-configuration/networking.x-k8s.io_gateways.yaml
  docs/content/reference/dynamic-configuration/networking.x-k8s.io_httproutes.yaml
  docs/content/reference/dynamic-configuration/networking.x-k8s.io_tcproutes.yaml
  docs/content/reference/dynamic-configuration/networking.x-k8s.io_tlsroutes.yaml
  go.mod
  go.sum
  integration/fixtures/k8s/01-gateway-api.yml
  pkg/provider/kubernetes/gateway/kubernetes.go
  pkg/provider/kubernetes/gateway/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/gatewayapi, kind/bug/fix, size/L, status/3-needs-merge

#8274 check if defaultcertificate is defined in store
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/provider/file/fixtures/yaml/simple_empty_store.yml
Labels: area/tls, kind/bug/fix, size/S, status/3-needs-merge

#8245 Library change for compress middleware to increase performance
  go.mod
  go.sum
  pkg/middlewares/compress/compress.go
  pkg/middlewares/compress/compress_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#8280 Fix KV reference documentation
  docs/content/reference/dynamic-configuration/kv-ref.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8281 Merge back v2.4 into v2.5
  CHANGELOG.md
  docs/scripts/verify.sh
  pkg/provider/file/file.go
  pkg/provider/file/file_test.go
  pkg/provider/file/fixtures/yaml/simple_empty_store.yml
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, size/S

#8282 Downgrade yaegi to v0.9.19
  go.mod
  go.sum
  pkg/plugins/providers.go
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8185 Don't remove ingress config on API call failure
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/client_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#8284 Fix dashboard to display middleware details
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: area/webui, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8285 Update yaegi to v0.9.21
  go.mod
  go.sum
  pkg/plugins/providers.go
Labels: area/plugins, kind/bug/fix, size/S, status/3-needs-merge

#8287 Merge back v2.4 into v2.5
  pkg/provider/kubernetes/ingress/client.go
  pkg/provider/kubernetes/ingress/client_mock_test.go
  pkg/provider/kubernetes/ingress/kubernetes.go
Labels: area/infrastructure, size/S

#8288 Prepare release v2.5.0-rc3
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8290 feat: Add new CI system
  .github/workflows/build.yaml
  .github/workflows/check_doc.yml
  .github/workflows/documentation.yml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  .semaphoreci/cleanup.sh
  .semaphoreci/golang.sh
  .semaphoreci/job1.sh
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  .travis.yml
  .travis/traefiker_rsa.enc
  Makefile
  script/code-gen.sh
  script/codegen.Dockerfile
  script/deploy.sh
  script/update-generated-crd-code.sh
Labels: area/infrastructure, kind/enhancement, size/L, status/3-needs-merge

#8296 Merge back v2.4 into v2.5
  .github/workflows/build.yaml
  .github/workflows/check_doc.yml
  .github/workflows/documentation.yml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  .semaphoreci/cleanup.sh
  .semaphoreci/golang.sh
  .semaphoreci/job1.sh
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  .travis.yml
  .travis/traefiker_rsa.enc
  Makefile
  script/code-gen.sh
  script/codegen.Dockerfile
  script/deploy.sh
  script/update-generated-crd-code.sh
Labels: area/infrastructure, size/L

#8298 Merge back v2.5 into master
  .github/workflows/build.yaml
  .github/workflows/check_doc.yml
  .github/workflows/documentation.yml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  .semaphoreci/cleanup.sh
  .semaphoreci/golang.sh
  .semaphoreci/job1.sh
  .semaphoreci/job2.sh
  .semaphoreci/setup.sh
  .semaphoreci/vars
  .travis.yml
  .travis/traefiker_rsa.enc
  CHANGELOG.md
  Makefile
  script/code-gen.sh
  script/codegen.Dockerfile
  script/deploy.sh
  script/gcg/traefik-rc-new.toml
  script/update-generated-crd-code.sh
Labels: area/infrastructure, size/L

#8254 ratelimiter: use correct ttlSeconds value, and always call Set
  pkg/middlewares/ratelimiter/rate_limiter.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#8307 Prepare release v2.4.12
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8309 fix: restore cache only once
  .semaphore/semaphore.yml
  integration/resources/compose/k8s.yml
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8315 fix: upgrade k3s version
  integration/resources/compose/k8s.yml
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8314 Merge back v2.4 into v2.5
  .semaphore/semaphore.yml
  CHANGELOG.md
  integration/resources/compose/k8s.yml
  pkg/middlewares/ratelimiter/rate_limiter.go
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, size/S, status/2-needs-review

#8316 Merge back v2.5 into master
  .semaphore/semaphore.yml
  CHANGELOG.md
  integration/resources/compose/k8s.yml
  pkg/middlewares/ratelimiter/rate_limiter.go
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, size/S

#7958 Add organizationalUnit to passtlscert middleware
  docs/content/middlewares/http/passtlsclientcert.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/anonymize/anonymize_config_test.go
  pkg/anonymize/testdata/anonymized-dynamic-config.json
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/config/label/label_test.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert.go
  pkg/middlewares/passtlsclientcert/pass_tls_client_cert_test.go
  pkg/provider/kv/kv_test.go
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: area/middleware, kind/enhancement, size/M, status/3-needs-merge

#8319 fix: remove hop-by-hop headers define in connection header beore some middleware
  pkg/middlewares/auth/forward.go
  pkg/middlewares/connectionheader/connectionheader.go
  pkg/middlewares/connectionheader/connectionheader_test.go
  pkg/middlewares/headers/headers.go
Labels: area/authentication, area/middleware, kind/bug/fix, size/M, status/3-needs-merge

#8313 Kubernetes: detect changes for resources other than endpoints
  pkg/provider/kubernetes/k8s/event_handler.go
  pkg/provider/kubernetes/k8s/event_handler_test.go
Labels: area/provider/k8s, kind/bug/fix, size/S, status/3-needs-merge

#8321 Prepare release v2.4.13
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/infrastructure, bot/light-review, size/S, status/3-needs-merge
