Repository traefik/traefik, pull requests merged in 2021-02, with the labels that each got.

#7839 Fix servers transport not found
  pkg/provider/aggregator/aggregator.go
  pkg/provider/aggregator/aggregator_test.go
Labels: area/provider, kind/bug/fix, size/S, status/3-needs-merge

#7822 Fix missing serverstransport documentation
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/kubernetes-crd-resource.yml
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/services/index.md
Labels: area/documentation, area/provider/docker, kind/bug/fix, size/S, status/3-needs-merge

#7824 fix: reduce pressure of pilot services when errors occurs
  pkg/pilot/pilot.go
Labels: area/pilot, kind/bug/fix, size/S, status/2-needs-review, status/3-needs-merge

#7840 Fix aggregator test comment
  pkg/provider/aggregator/aggregator_test.go
Labels: area/provider, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7841 Prepare Release v2.4.1
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7847 fix: infinite loop in forwarded header middleware.
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/forwardedheaders/forwarded_header_test.go
Labels: area/middleware, bot/light-review, kind/bug/fix, size/M, status/3-needs-merge

#7849 Fix the static configuration generation for environment variables
  docs/content/reference/static-configuration/env-ref.md
  internal/gendoc.go
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7851 Fix the redirect entrypoint default priority
  pkg/config/static/entrypoints.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#7852 Prepare release v2.4.2
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7860 Fix the static reference documentation for the internal redirection router.
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7858 Add HEAD as available option for Method
  docs/content/routing/routers/index.md
Labels: area/documentation, area/middleware, kind/enhancement, size/S, status/3-needs-merge

#7865 Fixed typo in consul catalog tests.
  integration/consul_catalog_test.go
Labels: area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#7808 Middleware documentation fixes
  docs/content/middlewares/addprefix.md
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/chain.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/contenttype.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/overview.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/middlewares/redirectregex.md
  docs/content/middlewares/redirectscheme.md
  docs/content/middlewares/replacepath.md
  docs/content/middlewares/replacepathregex.md
  docs/content/middlewares/retry.md
  docs/content/middlewares/stripprefix.md
  docs/content/middlewares/stripprefixregex.md
  docs/content/providers/docker.md
Labels: area/documentation, area/middleware, kind/bug/fix, size/L, status/3-needs-merge

#7879 Fix TLS challenge timeout and validation error
  cmd/traefik/traefik.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/provider.go
Labels: area/acme, kind/bug/fix, size/S, status/3-needs-merge

#7823 Provider documentation fixes
  docs/content/providers/consul-catalog.md
  docs/content/providers/consul.md
  docs/content/providers/docker.md
  docs/content/providers/ecs.md
  docs/content/providers/etcd.md
  docs/content/providers/file.md
  docs/content/providers/http.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-gateway.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/marathon.md
  docs/content/providers/overview.md
  docs/content/providers/rancher.md
  docs/content/providers/redis.md
  docs/content/providers/zookeeper.md
Labels: area/documentation, area/provider, kind/bug/fix, size/L, status/3-needs-merge

#7888 Apply content type exclusion on response
  docs/content/middlewares/compress.md
  go.mod
  go.sum
  pkg/middlewares/compress/compress.go
  pkg/middlewares/compress/compress_test.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7891 Add seo support
  .github/workflows/documentation.yml
  docs/content/providers/kubernetes-gateway.md
  docs/content/routing/providers/kubernetes-gateway.md
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7894 Add missing doc about servers transport.
  docs/content/routing/providers/consul-catalog.md
  docs/content/routing/providers/ecs.md
  docs/content/routing/providers/kv.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/services/index.md
Labels: area/documentation, area/provider, size/S, status/3-needs-merge

#7898 Prepare release v2.4.3
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7901 Merge current v2.4 into master
  .github/workflows/documentation.yml
  CHANGELOG.md
  cmd/traefik/traefik.go
  docs/content/middlewares/addprefix.md
  docs/content/middlewares/basicauth.md
  docs/content/middlewares/buffering.md
  docs/content/middlewares/chain.md
  docs/content/middlewares/circuitbreaker.md
  docs/content/middlewares/compress.md
  docs/content/middlewares/contenttype.md
  docs/content/middlewares/digestauth.md
  docs/content/middlewares/errorpages.md
  docs/content/middlewares/forwardauth.md
  docs/content/middlewares/headers.md
  docs/content/middlewares/inflightreq.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/middlewares/overview.md
  docs/content/middlewares/passtlsclientcert.md
  docs/content/middlewares/ratelimit.md
  docs/content/middlewares/redirectregex.md
  docs/content/middlewares/redirectscheme.md
  docs/content/middlewares/replacepath.md
  docs/content/middlewares/replacepathregex.md
  docs/content/middlewares/retry.md
  docs/content/middlewares/stripprefix.md
  docs/content/middlewares/stripprefixregex.md
  docs/content/providers/consul-catalog.md
  docs/content/providers/consul.md
  docs/content/providers/docker.md
  docs/content/providers/ecs.md
  docs/content/providers/etcd.md
  docs/content/providers/file.md
  docs/content/providers/http.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-gateway.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/marathon.md
  docs/content/providers/overview.md
  docs/content/providers/rancher.md
  docs/content/providers/redis.md
  docs/content/providers/zookeeper.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/routing/providers/consul-catalog.md
  docs/content/routing/providers/ecs.md
  docs/content/routing/providers/kubernetes-gateway.md
  docs/content/routing/providers/kv.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
  go.mod
  go.sum
  integration/consul_catalog_test.go
  pkg/middlewares/compress/compress.go
  pkg/middlewares/compress/compress_test.go
  pkg/provider/acme/challenge_tls.go
  pkg/provider/acme/provider.go
  script/gcg/traefik-bugfix.toml
Labels: size/L

#7904 Only allow iframes to be loaded from our domain
  pkg/api/dashboard.go
  pkg/api/dashboard_test.go
  pkg/server/service/managerfactory.go
Labels: area/webui, kind/bug/fix, size/S, status/3-needs-merge

#7909 Prepare release v2.4.4
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/2-needs-review, status/3-needs-merge

#7910 Prepare release v2.4.5
  .goreleaser.yml
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7914 Fix Kubernetes Gateway API documentation links
  docs/content/providers/kubernetes-gateway.md
  docs/content/routing/providers/kubernetes-gateway.md
Labels: area/documentation, area/provider/k8s/serviceapi, kind/bug/fix, size/S, status/3-needs-merge

#7913 Fix reflink typo in file provider documentation
  docs/content/providers/file.md
Labels: area/documentation, area/provider/file, kind/bug/fix, size/S, status/3-needs-merge

#7921 Merge current v2.4 into master
  .goreleaser.yml
  CHANGELOG.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-gateway.md
  docs/content/routing/providers/kubernetes-gateway.md
  pkg/api/dashboard.go
  pkg/api/dashboard_test.go
  pkg/server/service/managerfactory.go
  script/gcg/traefik-bugfix.toml
Labels: size/M

#7922 Fix typo in routing/services/index.md
  docs/content/routing/services/index.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7928 Update Yaegi to v0.9.13
  go.mod
  go.sum
Labels: area/plugins, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7925 fix: wait for file and internal before applying configurations
  cmd/traefik/traefik.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/aggregator/aggregator_test.go
  pkg/server/configurationwatcher.go
  pkg/server/configurationwatcher_test.go
Labels: area/provider, kind/bug/fix, size/S, status/3-needs-merge

#7933 Fixing doc for default value of checknewversion
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  internal/gendoc.go
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7899 Address all shellcheck warnings
  script/deploy.sh
Labels: area/infrastructure, size/S, status/3-needs-merge
