Repository traefik/traefik, pull requests merged in 2021-01, with the labels that each got.

#7714 Add ECS to supported providers list
  docs/content/providers/overview.md
Labels: area/documentation, area/provider, kind/bug/fix, size/S, status/3-needs-merge

#7718 docs: fix language "if challenge is not known"
  docs/user-guide/cluster-docker-consul.md
Labels: area/acme, area/documentation, kind/bug/fix, status/3-needs-merge

#7711 Fix wildcard hostname issue
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_service.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#7721 Use Datadog tracer environment variables to setup default config
  pkg/tracing/datadog/datadog.go
Labels: area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#7726 Do a Docker login on Travis
  .travis.yml
Labels: area/infrastructure, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7727 Merge current v2.3 branch into v2.4
  docs/content/providers/overview.md
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_service.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: size/M

#7728 Merge current v2.4 branch into master
  .golangci.toml
  CHANGELOG.md
  build.Dockerfile
  docs/content/middlewares/forwardauth.md
  docs/content/providers/docker.md
  docs/content/providers/overview.md
  pkg/metrics/pilot_test.go
  pkg/metrics/prometheus_test.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/provider/file/file_test.go
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-host_service.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_endpoint.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/Ingress-with-conflicting-routers-on-path_service.yml
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes_test.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/server/router/router_test.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/server_entrypoint_udp_test.go
  pkg/server/service/proxy_websocket_test.go
  pkg/tcp/proxy_test.go
  pkg/udp/conn_test.go
  pkg/udp/proxy_test.go
  script/gcg/traefik-bugfix.toml
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: size/L

#7724 Add HTTP3 support (experimental)
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/entrypoints.md
  go.mod
  go.sum
  pkg/config/static/entrypoints.go
  pkg/config/static/experimental.go
  pkg/config/static/static_config.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/server_entrypoint_tcp_http3.go
  pkg/tcp/router.go
Labels: area/http3, kind/enhancement, size/L, status/3-needs-merge

#6982 Feature: add udp timeout configuration
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/entrypoints.md
  docs/content/routing/routers/index.md
  pkg/config/static/entrypoints.go
  pkg/config/static/static_config.go
  pkg/server/server_entrypoint_udp.go
  pkg/server/server_entrypoint_udp_test.go
  pkg/udp/conn.go
  pkg/udp/conn_test.go
  pkg/udp/proxy_test.go
Labels: area/udp, kind/enhancement, status/3-needs-merge

#7667 Fix stickiness support in Service Fabric.
  Gopkg.lock
  Gopkg.toml
  docs/configuration/backends/servicefabric.md
  integration/resources/compose/proxy-protocol.yml
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_config.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_labelfuncs.go
  vendor/github.com/containous/traefik-extra-service-fabric/servicefabric_tmpl.go
  vendor/github.com/containous/traefik-extra-service-fabric/types.go
Labels: area/provider/servicefabric, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7647 Compile kubernetes ingress annotation regex only once
  pkg/provider/kubernetes/ingress/annotations.go
Labels: area/provider/k8s, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#7734 Update copyright year for 2021
  LICENSE.md
  docs/mkdocs.yml
  integration/fixtures/tlsclientheaders/readme.md
  integration/fixtures/tlsclientheaders/root.pem
  integration/fixtures/tlsclientheaders/server.key
  integration/fixtures/tlsclientheaders/server.pem
  integration/tls_client_headers_test.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/clientset.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/clientset_generated.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefikservice.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/generated_expansion.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/factory.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/generic.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/expansion_generated.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/tls/zz_generated.deepcopy.go
  pkg/types/zz_generated.deepcopy.go
Labels: area/documentation, bot/light-review, kind/enhancement, size/L, status/3-needs-merge

#7737 Discrepancy in Traefik log levels
  pkg/middlewares/customerrors/custom_errors.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7742 Merge current v2.3 branch into v2.4
  .travis.yml
  LICENSE.md
  docs/mkdocs.yml
  integration/fixtures/tlsclientheaders/readme.md
  integration/fixtures/tlsclientheaders/root.pem
  integration/fixtures/tlsclientheaders/server.key
  integration/fixtures/tlsclientheaders/server.pem
  integration/tls_client_headers_test.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/middlewares/customerrors/custom_errors.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/clientset.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/clientset_generated.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefikservice.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/generated_expansion.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/factory.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/generic.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/expansion_generated.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/provider/kubernetes/ingress/annotations.go
  pkg/tls/zz_generated.deepcopy.go
  pkg/types/zz_generated.deepcopy.go
Labels: size/L

#7743 Prepare release v2.3.7
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7744 Merge current v2.3 branch into v2.4
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: size/S

#7747 Prepare release v2.4.0-rc2
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7750 New Traefik Labs doc theme
  docs/content/assets/styles/atom-one-light.css
  docs/content/assets/styles/content.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/docs.Dockerfile
  docs/mkdocs.yml
  docs/requirements.txt
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo-long.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
Labels: area/documentation, area/infrastructure, kind/enhancement, size/L, status/3-needs-merge

#7751 Fix tlsclientheaders integration test
  .travis/traefiker_rsa.enc
  integration/fixtures/tlsclientheaders/readme.md
  integration/fixtures/tlsclientheaders/root.pem
  integration/fixtures/tlsclientheaders/server.key
  integration/fixtures/tlsclientheaders/server.pem
  integration/tls_client_headers_test.go
Labels: area/infrastructure, kind/bug/fix, size/S, status/3-needs-merge

#7753 Update copyright year for 2021
  LICENSE.md
  mkdocs.yml
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#7754 Update copyright year for 2021
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_serverstransport.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#7755 Prepare release v1.7.27
  CHANGELOG.md
  script/gcg/readme.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7756 Prepare release v1.7.28
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7760 Merge current v2.3 branch into v2.4
  docs/content/assets/styles/atom-one-light.css
  docs/content/assets/styles/content.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/docs.Dockerfile
  docs/mkdocs.yml
  docs/requirements.txt
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo-long.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
Labels: size/L

#7761 Merge current v2.4 into master
  docs/content/assets/styles/atom-one-light.css
  docs/content/assets/styles/content.css
  docs/content/assets/styles/footer.css
  docs/content/assets/styles/header.css
  docs/content/assets/styles/menu.css
  docs/content/assets/styles/product-switcher.css
  docs/content/assets/styles/root.css
  docs/docs.Dockerfile
  docs/mkdocs.yml
  docs/requirements.txt
  docs/theme/assets/images/traefik-enterprise-logo.svg
  docs/theme/assets/images/traefik-labs.svg
  docs/theme/assets/images/traefik-mesh-logo.svg
  docs/theme/assets/images/traefik-pilot-logo.svg
  docs/theme/assets/images/traefik-proxy-logo-long.svg
  docs/theme/assets/images/traefik-proxy-logo.svg
  docs/theme/main.html
  docs/theme/partials/company-header.html
  docs/theme/partials/product-switcher.html
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_serverstransport.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
Labels: size/L

#7764 Use GitHub Action to publish documentation.
  .github/workflows/documentation.yml
  .travis.yml
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#7765 Merge current v2.3 branch into v2.4
  .github/workflows/documentation.yml
  .travis.yml
Labels: size/S

#7766 Merge current v2.4 into master
  .github/workflows/documentation.yml
  .travis.yml
Labels: size/S

#7668 Add named port support to Kubernetes IngressRoute CRDs
  docs/content/routing/providers/kubernetes-crd.md
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/kubernetes_udp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/enhancement, size/M, status/3-needs-merge

#7773 Improve kubernetes external name service support for UDP
  docs/content/routing/providers/kubernetes-crd.md
  integration/fixtures/k8s/05-ingressrouteudp.yml
  integration/testdata/rawdata-crd.json
  pkg/provider/kubernetes/crd/fixtures/udp/services.yml
  pkg/provider/kubernetes/crd/fixtures/udp/with_externalname.yml
  pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_with_port.yml
  pkg/provider/kubernetes/crd/fixtures/udp/with_externalname_without_ports.yml
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/kubernetes_udp.go
Labels: area/provider/k8s, area/provider/k8s/crd, kind/enhancement, size/L, status/3-needs-merge

#7478 Add TLS version and cipher to the accessLog
  docs/content/observability/access-logs.md
  pkg/middlewares/accesslog/logdata.go
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/accesslog/logger_test.go
  pkg/middlewares/metrics/metrics.go
  pkg/tls/version.go
Labels: area/logs, area/middleware, size/S, status/3-needs-merge

#7780 Prepare release v2.4.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#7779 Mutualize TLS version and cipher code
  pkg/middlewares/accesslog/logger.go
  pkg/middlewares/metrics/metrics.go
  pkg/tls/cipher.go
  pkg/tls/version.go
Labels: area/tls, kind/enhancement, status/3-needs-merge

#7781 Merge current v2.4 into master
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: size/S

#7746 Update sprig to v3.2.0
  go.mod
  go.sum
  pkg/provider/configuration.go
  pkg/provider/file/file.go
Labels: area/provider/file, kind/enhancement, size/S, status/3-needs-merge

#7783 perf: improve forwarded header and recovery middlewares
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/recovery/recovery.go
  pkg/middlewares/recovery/recovery_test.go
  pkg/server/router/router.go
Labels: area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7433 Forward Proxy-Authorization header to authentication server
  pkg/middlewares/auth/forward.go
  pkg/middlewares/auth/forward_test.go
Labels: area/authentication, area/middleware, kind/bug/fix, size/S, status/3-needs-merge

#7787 fix: YAML syntax in providers docs
  docs/check.Dockerfile
  docs/content/providers/kubernetes-gateway.md
  docs/docs.Dockerfile
Labels: area/documentation, area/provider/k8s, bot/light-review, size/S, status/3-needs-merge

#7793 Update go-acme/lego to v4.2.0
  docs/content/https/acme.md
  go.mod
  go.sum
Labels: area/acme, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#7782 Fix plugin type on middleware endpoint response
  pkg/api/handler.go
  pkg/api/handler_test.go
Labels: area/api, area/plugins, kind/bug/fix, size/M, status/3-needs-merge

#7795 Merge current v2.4 into master
  docs/check.Dockerfile
  docs/content/https/acme.md
  docs/content/providers/kubernetes-gateway.md
  docs/docs.Dockerfile
  go.mod
  go.sum
  pkg/api/handler.go
  pkg/api/handler_test.go
  pkg/middlewares/auth/forward.go
  pkg/middlewares/auth/forward_test.go
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/recovery/recovery.go
  pkg/middlewares/recovery/recovery_test.go
  pkg/server/router/router.go
Labels: size/M

#7797 Fix typo in server transports documentation
  docs/content/routing/services/index.md
Labels: area/documentation, area/service, kind/bug/fix, size/S, status/3-needs-merge

#7811 chore: update linter.
  .golangci.toml
  build.Dockerfile
  pkg/metrics/prometheus.go
  pkg/middlewares/compress/compress_test.go
  pkg/middlewares/customerrors/custom_errors_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7810 Fix refresh interval option description in consulcatalog provider
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/provider/consulcatalog/consul_catalog.go
Labels: area/documentation, area/provider/consulcatalog, kind/bug/fix, size/S, status/3-needs-merge

#7805 Fix HTTP challenge router unexpected delayed creation
  integration/resources/compose/tlsclientheaders.yml
  integration/tls_client_headers_test.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/aggregator/aggregator_test.go
Labels: area/acme, area/provider, kind/bug/fix, size/M, status/3-needs-merge
