Repository traefik/traefik, pull requests merged in 2021-06, with the labels that each got.

#8107 Upgrade Node version to LTS on webui folder
  webui/Dockerfile
Labels: area/infrastructure, area/webui, kind/enhancement, size/S, status/3-needs-merge

#8072 doc: clarify usage for ratelimit's excludedIPs
  docs/content/middlewares/ratelimit.md
  pkg/config/dynamic/middlewares.go
  pkg/ip/strategy.go
  pkg/ip/strategy_test.go
Labels: area/documentation, area/middleware, size/S, status/3-needs-merge

#8169 Add routing IP rule matcher
  docs/content/routing/routers/index.md
  pkg/ip/checker.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
Labels: area/rules, kind/enhancement, size/M, status/3-needs-merge

#8176 Elaborate on possible use of status codes with the errors middleware
  docs/content/contributing/documentation.md
  docs/content/middlewares/errorpages.md
Labels: area/documentation, area/middleware, size/S, status/3-needs-merge

#8170 Explains Traefik HTTP response status codes
  docs/content/getting-started/faq.md
  docs/mkdocs.yml
Labels: area/documentation, kind/enhancement, size/M, status/3-needs-merge

#8180 Adding formatting to the document.
  docs/content/contributing/maintainers-guidelines.md
Labels: area/documentation, kind/bug/fix, size/S, status/3-needs-merge

#7833 tls Manager: do not build a default certificate for ACME challenges store
  pkg/provider/acme/provider.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/server/aggregator.go
  pkg/server/router/tcp/router.go
  pkg/tls/certificate_store.go
  pkg/tls/tlsmanager.go
Labels: area/tls, kind/enhancement, size/S, status/2-needs-review, status/3-needs-merge

#8184 Fixed BIND_DIR quoting
  Makefile
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#7789 Improve CA certificate loading from kubernetes secret
  docs/content/https/tls.md
  docs/content/middlewares/http/forwardauth.md
  docs/content/routing/providers/kubernetes-crd.md
  pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_options.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
Labels: area/provider/k8s, area/provider/k8s/crd, area/tls, size/S, status/3-needs-merge

#8187 Update Elastic APM from 1.7.0 to 1.11.0
  go.mod
  go.sum
Labels: area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#8198 Override jaeger configuration with env variables
  docs/content/observability/tracing/jaeger.md
  go.mod
  go.sum
  pkg/tracing/jaeger/jaeger.go
Labels: area/middleware/tracing, kind/enhancement, size/S, status/3-needs-merge

#8192 gateway-api: fix the "values" field in the example of httproute
  docs/content/routing/providers/kubernetes-gateway.md
Labels: area/documentation, area/provider/k8s, area/provider/k8s/gatewayapi, bot/light-review, size/S, status/3-needs-merge

#8190 Create buffered signals channel
  cmd/context.go
  cmd/traefik/traefik.go
Labels: area/server, bot/need-human-merge, kind/bug/fix, size/S, status/3-needs-merge

#8194 Use a dynamic buffer to handle client Hello SNI detection
  pkg/tcp/router.go
Labels: area/tls, bot/need-human-merge, kind/bug/fix, size/S, status/3-needs-merge

#8202 Update documentation references
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/config/static/static_config.go
Labels: area/documentation, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#8200 add `permissionsPolicy` and deprecate `featurePolicy`
  .golangci.toml
  docs/content/middlewares/http/headers.md
  go.mod
  go.sum
  integration/fixtures/headers/secure.toml
  integration/headers_test.go
  pkg/anonymize/anonymize_config_test.go
  pkg/anonymize/testdata/anonymized-dynamic-config.json
  pkg/config/dynamic/middlewares.go
  pkg/config/label/label_test.go
  pkg/middlewares/headers/headers.go
  pkg/middlewares/headers/secure.go
  pkg/middlewares/headers/secure_test.go
  pkg/provider/kv/kv_test.go
Labels: area/middleware, kind/enhancement, size/S, status/3-needs-merge

#8203 Use github action to check and verify doc
  .github/workflows/check_doc.yml
  .travis.yml
  docs/check.Dockerfile
Labels: area/infrastructure, area/provider/docker, kind/enhancement, size/S, status/3-needs-merge

#8205 Prepare release v2.4.9
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8206 chore: upgrade linter
  .golangci.toml
  build.Dockerfile
  pkg/middlewares/tracing/mock_tracing_test.go
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/S, status/3-needs-merge

#8209 Remove microbadger (Shutdown)
  README.md
Labels: area/documentation, area/infrastructure, bot/light-review, size/S, status/3-needs-merge

#8216 fix maintainers-guidelines page title
  docs/content/contributing/maintainers-guidelines.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8215 Typos in contributing section
  docs/content/contributing/maintainers-guidelines.md
  docs/content/contributing/maintainers.md
Labels: area/documentation, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8219 Convert issue templates to issue forms.
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area/infrastructure, bot/light-review, kind/enhancement, size/M, status/3-needs-merge

#8221 Merge current v2.4 into master
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  docs/content/contributing/maintainers-guidelines.md
  docs/content/contributing/maintainers.md
Labels: area/infrastructure, size/M

#8212 docs: fix invalid subdomain
  docs/content/middlewares/headers.md
  docs/content/middlewares/ipwhitelist.md
  docs/content/migration/v1-to-v2.md
  docs/content/migration/v2.md
  docs/content/routing/providers/kubernetes-crd.md
Labels: area/documentation, area/middleware, area/provider/k8s, bot/light-review, kind/bug/fix, size/S, status/3-needs-merge

#8226 Fix: malformed Kubernetes resource names and references in tests
  pkg/provider/kubernetes/crd/fixtures/tcp/with_bad_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options_and_specific_namespace.yml
  pkg/provider/kubernetes/crd/fixtures/with_bad_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_default_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_default_tls_options_default_namespace.yml
  pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_options_and_specific_namespace.yml
  pkg/provider/kubernetes/ingress/fixtures/TLS-support_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/TLS-support_secret.yml
Labels: area/provider/k8s, area/provider/k8s/crd, area/provider/k8s/ingress, kind/bug/fix, size/S, status/3-needs-merge

#8225 Add the list of available provider names
  docs/content/providers/overview.md
Labels: area/documentation, kind/enhancement, size/S, status/3-needs-merge

#8224 Local private plugins.
  .gitignore
  cmd/traefik/plugins.go
  cmd/traefik/traefik.go
  go.mod
  go.sum
  pkg/anonymize/anonymize_config_test.go
  pkg/anonymize/testdata/anonymized-static-config.json
  pkg/config/static/experimental.go
  pkg/plugins/builder.go
  pkg/plugins/plugins.go
  pkg/plugins/types.go
Labels: area/plugins, kind/enhancement, size/M, status/3-needs-merge

#8057 healthcheck: add support at the load-balancers of services level
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/routing/services/index.md
  integration/fixtures/healthcheck/propagate.toml
  integration/fixtures/healthcheck/propagate_no_healthcheck.toml
  integration/fixtures/healthcheck/reload_with_healthcheck.toml
  integration/fixtures/healthcheck/reload_without_healthcheck.toml
  integration/healthcheck_test.go
  integration/resources/compose/healthcheck.yml
  pkg/anonymize/anonymize_config_test.go
  pkg/config/dynamic/http_config.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/config/label/label_test.go
  pkg/config/runtime/runtime_test.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
  pkg/middlewares/emptybackendhandler/empty_backend_handler.go
  pkg/middlewares/emptybackendhandler/empty_backend_handler_test.go
  pkg/provider/kv/kv_test.go
  pkg/server/router/router_test.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/server/service/loadbalancer/mirror/mirror_test.go
  pkg/server/service/loadbalancer/wrr/wrr.go
  pkg/server/service/loadbalancer/wrr/wrr_test.go
  pkg/server/service/service.go
  pkg/server/service/service_test.go
Labels: area/healthcheck, kind/enhancement, size/L, status/3-needs-merge

#8232 Merge current v2.4 into master
  docs/content/middlewares/http/headers.md
  docs/content/middlewares/http/ipwhitelist.md
  docs/content/migration/v1-to-v2.md
  docs/content/migration/v2.md
  docs/content/providers/overview.md
  docs/content/routing/providers/kubernetes-crd.md
  pkg/provider/kubernetes/crd/fixtures/tcp/with_bad_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/with_tls_options_and_specific_namespace.yml
  pkg/provider/kubernetes/crd/fixtures/with_bad_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_default_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_default_tls_options_default_namespace.yml
  pkg/provider/kubernetes/crd/fixtures/with_servers_transport.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_options.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_options_and_specific_namespace.yml
  pkg/provider/kubernetes/ingress/fixtures/TLS-support_ingress.yml
  pkg/provider/kubernetes/ingress/fixtures/TLS-support_secret.yml
Labels: size/M

#8233 Prepare release v2.5.0-rc1
  .semaphoreci/vars
  .travis.yml
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/providers/docker.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-rc-first.toml
Labels: area/documentation, area/infrastructure, bot/light-review, size/M, status/3-needs-merge

#8236 Update generated and reference doc for plugins
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
Labels: area/documentation, bot/light-review, size/S, status/3-needs-merge

#8241 Merge back v2.5 into master
  CHANGELOG.md
  Makefile
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
Labels: size/S
