Repository traefik/traefik, pull requests merged in 2022-07, with the labels that each got.

#9161 Upgrade valkeyrie to v0.4.1
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/provider/kv, bot/light-review

#9152 Add callout for anyone using Traefik to manage commercial applications
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/https/acme.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/routing/entrypoints.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#9159 Support forwarded websocket protocol in RedirectScheme
  docs/content/middlewares/http/redirectscheme.md
  pkg/middlewares/forwardedheaders/forwarded_header.go
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/redirect/redirect_scheme_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#8913 Support ALPN for TCP + TLS routers
  docs/content/routing/routers/index.md
  pkg/muxer/tcp/mux.go
  pkg/muxer/tcp/mux_test.go
  pkg/server/router/tcp/router.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/rules, area/tcp

#9168 Improve performances when Prometheus metrics are enabled
  go.mod
  go.sum
  pkg/metrics/prometheus.go
  pkg/metrics/prometheus_test.go
  pkg/middlewares/metrics/metrics.go
Labels: status/3-needs-merge, kind/bug/fix, size/L, area/middleware, area/middleware/metrics

#9178 Prepare release v2.8.1
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9180 Refactor certificate domains matching func
  pkg/tls/certificate_store.go
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S

#9179 Update the PR guidelines in Contributing docs
  docs/content/contributing/submitting-pull-requests.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/L

#9197 Fix service up gauge for Prometheus metrics
  pkg/metrics/prometheus.go
  pkg/metrics/prometheus_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware/metrics

#9192 Update CONTRIBUTING.md to contain all information in one place
  CONTRIBUTING.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#9199 Lint markdown files
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  docs/readme.md
  integration/resources/tls/README.md
Labels: kind/enhancement, status/3-needs-merge, size/S, bot/light-review

#9190 Add support for reaching containers using host networking on Podman
  docs/content/providers/docker.md
  pkg/provider/docker/config.go
Labels: kind/enhancement, status/3-needs-merge, area/provider/docker, size/S

#9203 Update Thank You page with proper branding and grammar fixes
  docs/content/contributing/thank-you.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review
