Repository traefik/traefik, pull requests merged in 2022-05, with the labels that each got.

#8978 fix: prevent failure of collected data
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/hydration_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/L

#8981 Fix clean-webui target
  Makefile
  webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8982 Prepare release v2.6.5
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8983 Prepare Release v2.6.6
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/2-needs-review, size/S, bot/light-review

#8984 Merge current v2.6 into v2.7
  CHANGELOG.md
  Makefile
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/hydration_test.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/provider/ecs/ecs.go
  script/gcg/traefik-bugfix.toml
  webui/dev/scripts/transfer.js
  webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
Labels: size/L

#9000 Update jaeger-client-go to v2.30.0
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/middleware/tracing

#9001 Upgrade to oxy v1.4.0
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/L, bot/light-review

#8956 Support URL replacement in errors middleware
  docs/content/middlewares/http/errorpages.md
  pkg/middlewares/customerrors/custom_errors.go
  pkg/middlewares/customerrors/custom_errors_test.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/middleware

#9005 Upgrade to oxy v1.4.1
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#9011 Fix typo in maintainers guidelines
  docs/content/contributing/maintainers-guidelines.md
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9014 Fix log statement for ExternalName misconfig
  docs/scripts/verify.sh
  pkg/provider/kubernetes/crd/kubernetes.go
Labels: status/3-needs-merge, kind/bug/fix, area/logs, size/S, area/provider/k8s/crd

#9020 Update linter
  .github/workflows/validate.yaml
  .golangci.toml
  .semaphore/semaphore.yml
  build.Dockerfile
  integration/https_test.go
  integration/timeout_test.go
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#9023 feat: use dedicated entrypoint for the tunnels
  cmd/traefik/traefik.go
  docs/content/migration/v2.md
  docs/content/plugins/index.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/traefik-hub/index.md
  docs/mkdocs.yml
  pkg/config/static/hub.go
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
  pkg/config/static/static_config_test.go
  pkg/provider/hub/hub.go
  webui/Dockerfile
  webui/quasar.conf.js
  webui/src/App.vue
  webui/src/_helpers/APP.js
  webui/src/components/_commons/NavBar.vue
  webui/src/components/platform/PlatformAuthState.vue
  webui/src/components/platform/PlatformPanel.vue
Labels: status/3-needs-merge, area/webui, kind/bug/fix, size/L, area/hub

#9028 docs: fix default priority of the entrypoint redirection
  docs/content/routing/entrypoints.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#9031 fix: skip Provide when TLS is nil
  pkg/provider/hub/hub.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/hub

#9021 Fix initial tcp lookup when address is not available
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/tcp, area/service

#8976 Support certificates configuration in TLSStore CRD
  docs/content/https/tls.md
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  docs/content/routing/providers/kubernetes-crd.md
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/provider/kubernetes/crd/fixtures/with_tls_store_certificates.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
Labels: kind/enhancement, status/3-needs-merge, size/M, area/tls, area/provider/k8s/crd, area/provider/k8s

#9019 Fix panic when getting certificates with non-existing store
  pkg/tls/tlsmanager.go
  pkg/tls/tlsmanager_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/tls

#9038 Updated browserXssFilter key to camel case
  docs/content/middlewares/http/headers.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/middleware, bot/light-review

#9039 Update Yaegi to v0.12.0
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/plugins

#9045 Merge back v2.6 into v2.7
  .github/workflows/validate.yaml
  .golangci.toml
  .semaphore/semaphore.yml
  CHANGELOG.md
  build.Dockerfile
  docs/content/contributing/maintainers-guidelines.md
  docs/content/middlewares/http/headers.md
  docs/content/routing/entrypoints.md
  docs/scripts/verify.sh
  go.mod
  go.sum
  integration/https_test.go
  integration/timeout_test.go
  pkg/provider/hub/handler.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
  pkg/tls/tlsmanager.go
  pkg/tls/tlsmanager_test.go
  script/gcg/traefik-bugfix.toml
Labels: size/L

#9032 Add destination address to debug log
  pkg/tcp/proxy.go
  pkg/udp/proxy.go
Labels: kind/enhancement, status/3-needs-merge, area/logs, size/S

#9052 Merge current v2.7 into master
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/validate.yaml
  .golangci.toml
  .semaphore/semaphore.yml
  CHANGELOG.md
  Makefile
  build.Dockerfile
  cmd/traefik/traefik.go
  docs/content/contributing/maintainers-guidelines.md
  docs/content/getting-started/install-traefik.md
  docs/content/middlewares/http/headers.md
  docs/content/migration/v1-to-v2.md
  docs/content/migration/v2.md
  docs/content/plugins/index.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/routing/entrypoints.md
  docs/content/traefik-hub/index.md
  docs/mkdocs.yml
  docs/scripts/verify.sh
  go.mod
  go.sum
  integration/https_test.go
  integration/timeout_test.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/hydration_test.go
  pkg/config/static/hub.go
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
  pkg/config/static/static_config_test.go
  pkg/muxer/tcp/mux.go
  pkg/muxer/tcp/mux_test.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/provider/ecs/ecs.go
  pkg/provider/hub/handler.go
  pkg/provider/hub/hub.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/server/router/tcp/router.go
  pkg/server/router/tcp/router_test.go
  pkg/tcp/proxy.go
  pkg/tcp/proxy_test.go
  pkg/tls/tlsmanager.go
  pkg/tls/tlsmanager_test.go
  script/gcg/traefik-bugfix.toml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
  webui/Dockerfile
  webui/dev/scripts/transfer.js
  webui/quasar.conf.js
  webui/src/App.vue
  webui/src/_helpers/APP.js
  webui/src/components/_commons/NavBar.vue
  webui/src/components/platform/PlatformAuthState.vue
  webui/src/components/platform/PlatformPanel.vue
  webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md
Labels: size/L
