Repository traefik/traefik, pull requests merged in 2022-09, with the labels that each got.

#9287 fix: allow starting Traefik even if plugin services have an issue
  cmd/traefik/traefik.go
  pkg/plugins/client.go
  pkg/server/middleware/middlewares.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/plugins

#9295 Add missing networking apiGroup in Kubernetes RBACs examples and references
  docs/content/getting-started/quick-start-with-kubernetes.md
  docs/content/migration/v2.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  docs/content/routing/providers/kubernetes-ingress.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/provider/k8s

#9300 Update deprecation notes about Pilot
  docs/content/deprecation/features.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#9301 Prepare release v2.8.4
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#9306 doc: add healthcheck timeout seconds to value
  docs/content/routing/providers/docker.md
Labels: area/documentation, status/3-needs-merge, area/provider/docker, kind/bug/fix, size/S, bot/light-review

#8951 Change default TLS options for more security
  docs/content/deprecation/features.md
  pkg/server/aggregator_test.go
  pkg/server/configurationwatcher_test.go
  pkg/tls/tlsmanager.go
  pkg/tls/tlsmanager_test.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/tls

#9314 Update deprecation notes about Pilot
  docs/content/deprecation/features.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, bot/light-review

#9313 fix: IPv6 addr in square brackets
  pkg/middlewares/requestdecorator/request_decorator.go
  pkg/middlewares/requestdecorator/request_decorator_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/L, area/server

#9312 Display default TLS options in the dashboard
  pkg/api/handler_http.go
  pkg/api/handler_http_test.go
  pkg/api/testdata/router-baz-custom-tls-options.json
  pkg/api/testdata/router-baz-default-tls-options.json
Labels: status/3-needs-merge, area/webui, area/api, kind/bug/fix, size/S

#9268 Added resources for businesses
  docs/content/getting-started/concepts.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/https/acme.md
  docs/content/https/overview.md
  docs/content/https/tls.md
  docs/content/includes/.markdownlint.json
  docs/content/includes/traefik-for-business-applications.md
  docs/content/middlewares/http/headers.md
  docs/content/middlewares/http/overview.md
  docs/content/middlewares/overview.md
  docs/content/operations/dashboard.md
  docs/content/providers/docker.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/overview.md
  docs/content/routing/entrypoints.md
  docs/content/routing/overview.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
  docs/content/user-guides/docker-compose/basic-example/index.md
  docs/mkdocs.yml
Labels: area/documentation, status/3-needs-merge, size/L

#9266 Add Datadog GlobalTags support
  docs/content/observability/tracing/datadog.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/tracing/datadog/datadog.go
Labels: kind/enhancement, status/3-needs-merge, area/middleware/tracing

#9316 Update valkeyrie to v1.0.0
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  integration/consul_test.go
  integration/etcd_test.go
  integration/redis_test.go
  integration/zk_test.go
  pkg/provider/kv/consul/consul.go
  pkg/provider/kv/etcd/etcd.go
  pkg/provider/kv/kv.go
  pkg/provider/kv/redis/redis.go
  pkg/provider/kv/zk/zk.go
  pkg/redactor/redactor_config_test.go
  pkg/redactor/testdata/anonymized-static-config.json
  pkg/types/tls.go
Labels: kind/enhancement, status/3-needs-merge, area/provider/consul, area/provider/etcd, area/provider/zk, size/M, area/provider/kv, area/provider/redis

#9327 Update Yaegi to v0.14.2
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/plugins

#9328 Prepare release v2.8.5
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/2-needs-review, size/S, bot/light-review

#9329 Merge v2.8.5 into master
  CHANGELOG.md
  cmd/traefik/traefik.go
  docs/content/deprecation/features.md
  docs/content/getting-started/concepts.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start-with-kubernetes.md
  docs/content/getting-started/quick-start.md
  docs/content/https/acme.md
  docs/content/https/overview.md
  docs/content/https/tls.md
  docs/content/includes/.markdownlint.json
  docs/content/includes/traefik-for-business-applications.md
  docs/content/middlewares/http/headers.md
  docs/content/middlewares/http/overview.md
  docs/content/middlewares/overview.md
  docs/content/migration/v2.md
  docs/content/operations/dashboard.md
  docs/content/providers/docker.md
  docs/content/providers/file.md
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/providers/overview.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  docs/content/routing/entrypoints.md
  docs/content/routing/overview.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
  docs/content/user-guides/docker-compose/basic-example/index.md
  docs/mkdocs.yml
  go.mod
  go.sum
  pkg/api/handler_http.go
  pkg/api/handler_http_test.go
  pkg/api/testdata/router-baz-custom-tls-options.json
  pkg/api/testdata/router-baz-default-tls-options.json
  pkg/middlewares/requestdecorator/request_decorator.go
  pkg/middlewares/requestdecorator/request_decorator_test.go
  pkg/plugins/client.go
  pkg/server/middleware/middlewares.go
  script/gcg/traefik-bugfix.toml
Labels: size/L

#9189 ACME Default Certificate
  docs/content/https/tls.md
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  integration/acme_test.go
  integration/fixtures/acme/acme_store_domains.toml
  integration/fixtures/k8s/01-traefik-crd.yml
  integration/https_test.go
  pkg/provider/acme/provider.go
  pkg/provider/acme/provider_test.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/tls/certificate.go
  pkg/tls/certificate_store.go
  pkg/tls/tls.go
  pkg/tls/tlsmanager.go
  pkg/tls/zz_generated.deepcopy.go
Labels: kind/enhancement, status/3-needs-merge, area/acme, size/L, area/tls

#9330 Remove Pilot support
  SECURITY.md
  cmd/traefik/plugins.go
  cmd/traefik/traefik.go
  docs/content/deprecation/features.md
  docs/content/middlewares/http/overview.md
  docs/content/migration/v2.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  internal/gendoc.go
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
  pkg/metrics/pilot.go
  pkg/metrics/pilot_test.go
  pkg/pilot/pilot.go
  pkg/pilot/pilot_test.go
  pkg/plugins/client.go
  pkg/redactor/redactor_config_test.go
  pkg/redactor/testdata/anonymized-dynamic-config.json
  pkg/redactor/testdata/anonymized-static-config.json
  pkg/redactor/testdata/secured-dynamic-config.json
  pkg/version/version.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/middleware, area/pilot

#9007 Quiet down TCP RST packet error on read operation
  pkg/tcp/proxy.go
  pkg/tcp/proxy_unix.go
  pkg/tcp/proxy_windows.go
Labels: kind/enhancement, status/3-needs-merge, area/logs, size/S, area/tcp

#9333 fix: shellcheck
  script/binary
  script/code-gen.sh
  script/make.sh
  script/test-integration
  script/test-unit
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#9324 Add support for ECS Anywhere
  docs/content/providers/ecs.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/ecs/config.go
  pkg/provider/ecs/ecs.go
  pkg/redactor/redactor_config_test.go
  pkg/redactor/testdata/anonymized-static-config.json
Labels: kind/enhancement, status/3-needs-merge, area/provider/ecs, size/M

#9334 Prepare release v2.9.0-rc1
  .semaphore/semaphore.yml
  CHANGELOG.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start-with-kubernetes.md
  docs/content/getting-started/quick-start.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/index.md
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/tcp_middlewares.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/service.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  script/gcg/traefik-rc-first.toml
Labels: area/documentation, status/2-needs-review, area/infrastructure, size/L, bot/light-review

#9338 plugins: allow empty config
  pkg/plugins/middlewares.go
  pkg/server/middleware/plugins.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/plugins

#9340 Add documentation for json schema usage to validate config in the FAQ
  docs/content/getting-started/faq.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#9322 Add a note on case insensitive regex matching
  docs/content/routing/routers/index.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S, bot/light-review

#9343 Merge current v2.8 into v2.9
  docs/content/getting-started/faq.md
  docs/content/routing/routers/index.md
  pkg/plugins/middlewares.go
  pkg/server/middleware/plugins.go
Labels: size/S

#9344 Prepare release v2.9.0-rc3
  .semaphore/semaphore.yml
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9349 docs: fix link to RouteNamespaces
  docs/content/migration/v2.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#9350 Merge current v2.8 branch into v2.9
  docs/content/migration/v2.md
Labels: size/S

#9332 Support multiple namespaces in the Nomad Provider
  .golangci.toml
  docs/content/deprecation/features.md
  docs/content/migration/v2.md
  docs/content/providers/nomad.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/config/static/static_config.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/nomad/config_test.go
  pkg/provider/nomad/nomad.go
  pkg/provider/nomad/nomad_test.go
  webui/src/components/_commons/PanelMiddlewares.vue
  webui/src/components/_commons/PanelMirroringServices.vue
  webui/src/components/_commons/PanelRouterDetails.vue
  webui/src/components/_commons/PanelServiceDetails.vue
  webui/src/components/_commons/PanelWeightedServices.vue
  webui/src/components/_commons/ProviderIcon.vue
  webui/src/components/dashboard/PanelProvider.vue
Labels: kind/enhancement, status/3-needs-merge, size/M, area/provider/nomad

#9354 Add documentation for ECS constraints option
  docs/content/providers/ecs.md
  docs/content/providers/overview.md
Labels: area/documentation, status/3-needs-merge, area/provider/ecs, size/S, bot/light-review

#8027 Add option to keep only healthy ECS tasks
  docs/content/providers/ecs.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/ecs/ecs.go
Labels: status/2-needs-review, status/3-needs-merge, area/provider/ecs, size/S

#8583 Support gRPC healthcheck
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/routing/services/index.md
  pkg/config/dynamic/fixtures/sample.toml
  pkg/config/dynamic/http_config.go
  pkg/config/label/label_test.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
  pkg/healthcheck/mock_test.go
  pkg/provider/kv/kv_test.go
  pkg/server/service/service.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/healthcheck

#9357 fix: UDP loadbalancer tags not being used with Consul Catalog
  pkg/provider/consulcatalog/config.go
  pkg/provider/consulcatalog/config_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/provider/consulcatalog

#9358 providers: simplify AddServer algorithms
  pkg/provider/docker/config.go
  pkg/provider/ecs/config.go
  pkg/provider/nomad/config.go
  pkg/provider/rancher/config.go
Labels: status/3-needs-merge, area/provider/docker, area/provider/rancher, area/provider/ecs, kind/bug/fix, size/M, area/provider

#9367 Merge current v2.8 into v2.9
  docs/content/providers/ecs.md
  docs/content/providers/overview.md
  pkg/provider/consulcatalog/config.go
  pkg/provider/consulcatalog/config_test.go
  pkg/provider/docker/config.go
  pkg/provider/ecs/config.go
  pkg/provider/nomad/config.go
  pkg/provider/rancher/config.go
  pkg/server/service/proxy.go
Labels: size/L

#9365 fix: acme panic
  pkg/provider/acme/provider.go
Labels: status/3-needs-merge, area/acme, kind/bug/fix, size/S

#9366 Rework metrics overview page
  docs/content/observability/metrics/overview.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/L

#9369 fix: query parameter matching with equal
  pkg/muxer/http/mux.go
  pkg/muxer/http/mux_test.go
Labels: status/3-needs-merge, kind/bug/fix, area/rules, bot/light-review

#9370 Prepare release v2.8.6
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/2-needs-review, size/S, bot/light-review

#9372 Prepare release v2.9.0-rc4
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/2-needs-review, size/S, bot/light-review

#9373 Prepare release v2.8.7
  .goreleaser.yml
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/2-needs-review, size/S, bot/light-review

#9380 Improve documentation for publishedService and IP options
  docs/content/providers/kubernetes-ingress.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S, area/provider/k8s

#9398 Update golang.org/x/net to latest version
  go.mod
  go.sum
  integration/helloworld/helloworld.pb.go
  pkg/server/server_signals_windows.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/server

#9391 Fix watch option description for Docker provider
  docs/content/providers/docker.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  pkg/provider/docker/docker.go
Labels: status/3-needs-merge, area/provider/docker, kind/bug/fix, size/S, bot/light-review

#9392 Fix autoDiscoverClusters option documentation for ECS provider
  docs/content/providers/ecs.md
Labels: area/documentation, status/3-needs-merge, area/provider/ecs, kind/bug/fix, size/S, bot/light-review

#9399 Prepare release v2.8.8
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, size/S

#9400 Merge current v2.8 into v2.9
  CHANGELOG.md
  docs/content/providers/docker.md
  docs/content/providers/ecs.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  go.mod
  go.sum
  integration/helloworld/helloworld.pb.go
  pkg/provider/docker/docker.go
  script/gcg/traefik-bugfix.toml
Labels: size/S

#9402 Prepare release v2.9.0-rc5
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9237 Add Tailscale certificate resolver
  cmd/traefik/traefik.go
  docs/content/https/tailscale.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/mkdocs.yml
  go.mod
  go.sum
  pkg/config/static/static_config.go
  pkg/provider/tailscale/provider.go
  pkg/provider/tailscale/provider_test.go
  pkg/tls/certificate.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/tls
