Repository traefik/traefik, pull requests merged in 2022-06, with the labels that each got.

#9058 Update Gateway API links
  docs/content/routing/providers/kubernetes-gateway.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/provider/k8s, area/provider/k8s/gatewayapi

#9060 Merge current v2.7 into master
  docs/content/middlewares/http/stripprefix.md
  docs/content/routing/providers/kubernetes-gateway.md
Labels: size/S

#9056 Update the link for contributor swag
  docs/content/contributing/advocating.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S

#9065 Update go-acme/lego to v4.7.0
  docs/content/https/acme.md
  go.mod
  go.sum
Labels: status/3-needs-merge, area/acme, kind/bug/fix, size/S, bot/light-review

#9076 docs: fix rule expression render
  docs/content/routing/routers/index.md
Labels: area/documentation, status/3-needs-merge, size/S, area/rules, bot/light-review

#9084 fix: invalid placeholder in log message
  pkg/server/router/tcp/router.go
Labels: status/3-needs-merge, kind/bug/fix, area/logs, size/S, bot/light-review

#9055 feat: Reach the catalog of plugins from the Traefik dashboard
  webui/src/components/_commons/NavBar.vue
Labels: kind/enhancement, status/3-needs-merge, area/webui, size/S, area/plugins

#9035 Update the contributing docs for clarity and to encourage community activity
  docs/content/contributing/submitting-issues.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#9090 Hub documentation
  docs/content/traefik-hub/index.md
  docs/mkdocs.yml
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/L, area/hub

#9097 Prepare release v2.8.0-rc1
  .semaphore/semaphore.yml
  CHANGELOG.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/providers/docker.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-rc-first.toml
Labels: area/documentation, status/3-needs-merge, size/M, bot/light-review

#9105 Update DataDog tracing dependency to v1.38.1
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/L, bot/light-review, area/middleware/tracing

#9104 Add log when missing path in health check
  docs/content/routing/services/index.md
  pkg/server/service/service.go
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/healthcheck, area/service

#9103 Load plugin configuration field value from Kubernetes Secret
  pkg/provider/kubernetes/crd/fixtures/with_plugin_deep_read_secret.yml
  pkg/provider/kubernetes/crd/fixtures/with_plugin_read_array_of_map_contain_secret.yml
  pkg/provider/kubernetes/crd/fixtures/with_plugin_read_array_of_secret.yml
  pkg/provider/kubernetes/crd/fixtures/with_plugin_read_not_exist_secret.yml
  pkg/provider/kubernetes/crd/fixtures/with_plugin_read_secret.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/provider/k8s/crd, area/plugins

#9115 docs: add missing info.serialNumber option to PassTLSClientCert middleware
  docs/content/middlewares/http/passtlsclientcert.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#9118 Update yaegi to v0.13.0
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/plugins

#8632 Do not make multiple requests to the same URL for balancer healthcheck
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/healthcheck

#9107 Allow multiple listeners on same port in Gateway API provider
  pkg/provider/kubernetes/gateway/fixtures/mixed/with_multiple_listeners_using_same_hostname_port_protocol.yml
  pkg/provider/kubernetes/gateway/kubernetes.go
  pkg/provider/kubernetes/gateway/kubernetes_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/L, area/provider/k8s/gatewayapi

#9121 RedirectScheme redirects based on X-Forwarded-Proto header
  docs/content/middlewares/http/redirectscheme.md
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/redirect/redirect_scheme_test.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware

#9116 Start polling HTTP provider at the beginning
  pkg/provider/http/http.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/provider/http

#9130 Update to improve info section relevance
  docs/content/https/acme.md
  docs/content/index.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#9132 Prepare release v2.7.2
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9133 Merge current v2.7 into v2.8
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/https/acme.md
  docs/content/index.md
  docs/content/middlewares/http/passtlsclientcert.md
  docs/content/middlewares/http/redirectscheme.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/reference/dynamic-configuration/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/routers/index.md
  docs/content/routing/services/index.md
  docs/content/user-guides/crd-acme/05-tlsoption.yml
  docs/content/user-guides/crd-acme/index.md
  go.mod
  go.sum
  integration/fixtures/k8s/01-traefik-crd.yml
  integration/fixtures/simple_muxer.toml
  integration/simple_test.go
  pkg/config/dynamic/http_config.go
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/tcp_middlewares.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
  pkg/middlewares/redirect/redirect_scheme.go
  pkg/middlewares/redirect/redirect_scheme_test.go
  pkg/muxer/http/mux_test.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/objectreference.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/service.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/provider/kubernetes/gateway/fixtures/mixed/with_multiple_listeners_using_same_hostname_port_protocol.yml
  pkg/provider/kubernetes/gateway/kubernetes.go
  pkg/provider/kubernetes/gateway/kubernetes_test.go
  pkg/redactor/testdata/anonymized-dynamic-config.json
  pkg/redactor/testdata/secured-dynamic-config.json
  pkg/server/server_entrypoint_tcp.go
  pkg/server/service/proxy.go
  pkg/server/service/service.go
  script/code-gen.sh
  script/gcg/traefik-bugfix.toml
Labels: size/L

#9134 Prepare release v2.8.0-rc2
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#9137 Ensure that the Datadog client is cleanly stopped
  pkg/metrics/datadog.go
Labels: status/3-needs-merge, kind/bug/fix, size/S

#9140 Move consulcatalog provider to only use health apis
  pkg/provider/consulcatalog/consul_catalog.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/provider/consulcatalog

#9143 Prepare release v2.8.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  docs/content/user-guides/crd-acme/index.md
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/tcp_middlewares.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/service.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: area/documentation, status/3-needs-merge, size/L, bot/light-review

#9146 Merge current v2.8 into master
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/middlewares/http/overview.md
  docs/content/providers/kubernetes-crd.md
  docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  docs/content/user-guides/crd-acme/index.md
  integration/fixtures/k8s/01-traefik-crd.yml
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/dynamic/tcp_middlewares.go
  pkg/metrics/datadog.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/service.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/tlsstore.go
  pkg/types/domains.go
  script/gcg/traefik-bugfix.toml
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: size/L

#9149 Update deprecation notices
  docs/content/deprecation/features.md
  docs/content/deprecation/releases.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#9150 Remove `-a` when building binary
  script/binary
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S
