Repository traefik/traefik, pull requests merged in 2022-03, with the labels that each got.

#8742 Add simpler and faster debug Makefile target
  .github/workflows/build.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  Makefile
  build.Dockerfile
  debug.Dockerfile
  docs/content/contributing/building-testing.md
  exp.Dockerfile
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S

#8783 Replace npm with yarn to install/run the webui
  Makefile
  exp.Dockerfile
  webui/Dockerfile
  webui/package-lock.json
  webui/package.json
  webui/readme.md
  webui/yarn.lock
Labels: kind/enhancement, status/3-needs-merge, area/webui, area/infrastructure, size/S

#8756 Enhance doc on static vs dynamic configuration
  docs/content/getting-started/configuration-overview.md
  docs/content/https/tls.md
  docs/content/routing/providers/kubernetes-crd.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#8817 Fix HostRegexp examples
  docs/content/routing/routers/index.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#8819 Adjust rule length in routers documentation
  docs/content/routing/routers/index.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#8814 Add a target that is a real resource to generate-webui
  Makefile
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S

#8802 Allow empty services in Kubernetes CRD
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/kubernetes/crd/fixtures/services.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/services.yml
  pkg/provider/kubernetes/crd/fixtures/tcp/with_empty_services.yml
  pkg/provider/kubernetes/crd/fixtures/udp/services.yml
  pkg/provider/kubernetes/crd/fixtures/udp/with_empty_services.yml
  pkg/provider/kubernetes/crd/fixtures/with_empty_services.yml
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/crd/kubernetes_http.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/kubernetes_test.go
  pkg/provider/kubernetes/crd/kubernetes_udp.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/provider/k8s/crd, area/provider/k8s

#8823 doc: fix, docker uses Label(), not Tag()
  docs/content/providers/docker.md
Labels: area/documentation, status/3-needs-merge, area/provider/docker, kind/bug/fix, size/S, bot/light-review

#8821 Add a link to service on router detail view
  webui/src/pages/_commons/RouterDetail.vue
Labels: kind/enhancement, status/3-needs-merge, area/webui, size/S

#8832 Merge current v2.6 into master
  .github/workflows/build.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  Makefile
  build.Dockerfile
  debug.Dockerfile
  docs/content/contributing/building-testing.md
  docs/content/getting-started/configuration-overview.md
  docs/content/https/tls.md
  docs/content/providers/docker.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/routers/index.md
  exp.Dockerfile
Labels: size/M

#8836 Clarify concepts documentation page
  docs/content/getting-started/concepts.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S

#8840 Fix routing overview examples
  docs/content/routing/overview.md
Labels: area/documentation, kind/bug/fix, size/S

#8829 Add a deprecation notices section
  README.md
  docs/content/deprecation/releases.md
  docs/mkdocs.yml
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S

#8825 Add Failover service
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/routing/services/index.md
  pkg/config/dynamic/http_config.go
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/provider/kv/kv_test.go
  pkg/server/service/loadbalancer/failover/failover.go
  pkg/server/service/loadbalancer/failover/failover_test.go
  pkg/server/service/loadbalancer/wrr/wrr.go
  pkg/server/service/service.go
  webui/src/components/_commons/PanelServiceDetails.vue
Labels: kind/enhancement, status/3-needs-merge, size/M, area/healthcheck

#8182 Add muxer for TCP Routers
  .golangci.toml
  docs/content/reference/dynamic-configuration/docker-labels.yml
  docs/content/reference/dynamic-configuration/file.toml
  docs/content/reference/dynamic-configuration/file.yaml
  docs/content/reference/dynamic-configuration/kv-ref.md
  docs/content/reference/dynamic-configuration/marathon-labels.json
  docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  docs/content/routing/providers/consul-catalog.md
  docs/content/routing/providers/docker.md
  docs/content/routing/providers/ecs.md
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kv.md
  docs/content/routing/providers/marathon.md
  docs/content/routing/providers/rancher.md
  docs/content/routing/routers/index.md
  integration/fixtures/k8s/01-traefik-crd.yml
  integration/simple_test.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/label/label_test.go
  pkg/muxer/http/mux.go
  pkg/muxer/http/mux_test.go
  pkg/muxer/tcp/mux.go
  pkg/muxer/tcp/mux_test.go
  pkg/provider/acme/provider.go
  pkg/provider/kubernetes/crd/kubernetes_tcp.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/ingressroutetcp.go
  pkg/rules/parser.go
  pkg/rules/parser_test.go
  pkg/server/router/router.go
  pkg/server/router/tcp/manager.go
  pkg/server/router/tcp/manager_test.go
  pkg/server/router/tcp/router.go
  pkg/server/routerfactory.go
  pkg/server/server_entrypoint_tcp.go
  pkg/server/server_entrypoint_tcp_http3.go
  pkg/server/server_entrypoint_tcp_http3_test.go
  pkg/server/server_entrypoint_tcp_test.go
  pkg/server/service/loadbalancer/mirror/mirror.go
  pkg/tcp/router.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/tcp

#8848 Add Traefik Hub access and remove Pilot access
  Makefile
  cmd/traefik/traefik.go
  docs/content/migration/v2.md
  docs/content/plugins/index.md
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
  webui/Dockerfile
  webui/quasar.conf.js
  webui/src/App.vue
  webui/src/_helpers/APP.js
  webui/src/components/_commons/NavBar.vue
  webui/src/components/platform/PlatformAuthState.vue
  webui/src/components/platform/PlatformPanel.vue
Labels: kind/enhancement, status/3-needs-merge, area/webui, size/L, area/pilot

#8849 Add HostSNIRegexp rule matcher for TCP
  docs/content/routing/routers/index.md
  pkg/muxer/tcp/mux.go
  pkg/muxer/tcp/mux_test.go
Labels: kind/enhancement, status/3-needs-merge, size/L, area/rules, area/tcp

#8855 Fix fenced code block typo in Buffering middleware page
  docs/content/middlewares/http/buffering.md
Labels: area/documentation, status/3-needs-merge, size/S, area/middleware, bot/light-review

#8851 chore: update linter
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  build.Dockerfile
  pkg/provider/docker/docker.go
  pkg/server/routerfactory.go
  pkg/server/server.go
Labels: kind/enhancement, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#8863 Add default certificate definition example for Kubernetes
  docs/content/https/tls.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/tls, bot/light-review, area/provider/k8s/crd, area/provider/k8s

#8865 Merge current v2.6 into master
  .github/workflows/validate.yaml
  .semaphore/semaphore.yml
  README.md
  build.Dockerfile
  docs/content/deprecation/releases.md
  docs/content/getting-started/concepts.md
  docs/content/https/tls.md
  docs/content/middlewares/http/buffering.md
  docs/content/providers/consul.md
  docs/content/providers/redis.md
  docs/content/providers/zookeeper.md
  docs/content/routing/overview.md
  docs/mkdocs.yml
  go.mod
  go.sum
  integration/simple_test.go
  pkg/config/dynamic/http_config.go
  pkg/config/dynamic/middlewares.go
  pkg/config/dynamic/tcp_config.go
  pkg/config/kv/kv.go
  pkg/config/kv/kv_test.go
  pkg/config/static/entrypoints.go
  pkg/provider/docker/docker.go
  pkg/server/routerfactory.go
  pkg/server/server.go
Labels: size/M

#8859 Fix certificates resolver typo
  docs/content/https/acme.md
Labels: area/documentation, status/3-needs-merge, area/acme, size/S

#8864 Update entrypoint.md to add consistent CLI syntax
  docs/content/routing/entrypoints.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S, bot/light-review

#8869 Plugins and token
  cmd/traefik/plugins.go
Labels: kind/enhancement, status/3-needs-merge, size/S, bot/light-review, area/plugins

#8868 Add a Feature Deprecation page
  docs/content/deprecation/features.md
  docs/content/migration/v2.md
  docs/mkdocs.yml
Labels: kind/enhancement, area/documentation, status/3-needs-merge, size/S, bot/light-review

#8876 Prepare release v2.6.2
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, area/infrastructure, size/S, bot/light-review

#8877 Merge current v2.6 into master
  CHANGELOG.md
  docs/content/https/acme.md
  docs/content/routing/entrypoints.md
  script/gcg/traefik-bugfix.toml
Labels: status/3-needs-merge, size/S, bot/light-review, bot/merge-method-ff

#8837 Add Traefik Hub Integration (Experimental Feature)
  cmd/traefik/traefik.go
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  docs/content/traefik-hub/index.md
  docs/mkdocs.yml
  docs/requirements.txt
  pkg/api/handler_overview.go
  pkg/api/handler_overview_test.go
  pkg/api/testdata/overview-dynamic.json
  pkg/api/testdata/overview-empty.json
  pkg/api/testdata/overview-features.json
  pkg/api/testdata/overview-providers.json
  pkg/config/static/experimental.go
  pkg/config/static/static_config.go
  pkg/provider/hub/handler.go
  pkg/provider/hub/handler_test.go
  pkg/provider/hub/hub.go
  webui/src/statics/providers/hub.svg
Labels: kind/enhancement, status/3-needs-merge, size/L, area/hub

#8879 Prepare release v2.7.0-rc1
  .semaphore/semaphore.yml
  CHANGELOG.md
  docs/content/getting-started/configuration-overview.md
  docs/content/getting-started/install-traefik.md
  docs/content/getting-started/quick-start.md
  docs/content/migration/v1-to-v2.md
  docs/content/observability/access-logs.md
  docs/content/providers/docker.md
  docs/content/reference/dynamic-configuration/kubernetes-gateway-traefik-lb-svc.yml
  docs/content/routing/providers/kubernetes-crd.md
  docs/content/routing/providers/kubernetes-ingress.md
  docs/content/user-guides/crd-acme/03-deployments.yml
  docs/content/user-guides/crd-acme/k3s.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-dns/docker-compose_secrets.yml
  docs/content/user-guides/docker-compose/acme-http/docker-compose.yml
  docs/content/user-guides/docker-compose/acme-tls/docker-compose.yml
  docs/content/user-guides/docker-compose/basic-example/docker-compose.yml
  script/gcg/traefik-rc-first.toml
Labels: area/documentation, status/3-needs-merge, size/M, bot/light-review

#8880 Fixing dependency to build doc
  docs/requirements.txt
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure

#8883 Fix hub tls documentation
  docs/content/traefik-hub/index.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review

#8886 Fix slice parsing for plugins
  pkg/plugins/middlewares.go
  pkg/plugins/plugins.go
  pkg/plugins/plugins_test.go
  pkg/plugins/providers.go
Labels: status/3-needs-merge, kind/bug/fix, size/M, area/plugins

#8874 Upgrade quic-go to v0.26.0
  go.mod
  go.sum
  pkg/config/static/entrypoints.go
  pkg/server/server_entrypoint_tcp_http3.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/http3

#8894 fix: CI release
  .goreleaser.yml
  .semaphore/semaphore.yml
Labels: status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S

#8893 Return TLS unrecognized_name error when no certificate is available
  pkg/tls/tlsmanager.go
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/tls

#8899 Merge current v2.6 into v2.7
  .goreleaser.yml
  .semaphore/semaphore.yml
  CHANGELOG.md
  docs/requirements.txt
  pkg/plugins/middlewares.go
  pkg/plugins/plugins.go
  pkg/plugins/plugins_test.go
  pkg/plugins/providers.go
  pkg/tls/tlsmanager.go
  script/gcg/traefik-bugfix.toml
Labels: size/M

#8900 Prepare release v2.7.0-rc2
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review
