Repository traefik/traefik, pull requests merged in 2022-01, with the labels that each got.

#8679 Update copyright for 2022
  LICENSE.md
  docs/mkdocs.yml
  pkg/config/dynamic/zz_generated.deepcopy.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/clientset.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/clientset_generated.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/fake/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/scheme/register.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/doc.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_middlewaretcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_serverstransport.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/fake/fake_traefikservice.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/generated_expansion.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefik_client.go
  pkg/provider/kubernetes/crd/generated/clientset/versioned/typed/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/factory.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/generic.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/interface.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/informers/externalversions/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/expansion_generated.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroute.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressroutetcp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/ingressrouteudp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/middleware.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/middlewaretcp.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/serverstransport.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsoption.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/tlsstore.go
  pkg/provider/kubernetes/crd/generated/listers/traefik/v1alpha1/traefikservice.go
  pkg/provider/kubernetes/crd/traefik/v1alpha1/zz_generated.deepcopy.go
  pkg/tls/zz_generated.deepcopy.go
  pkg/types/zz_generated.deepcopy.go
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/L

#8680 Update copyright for 2022
  LICENSE.md
  mkdocs.yml
Labels: area/documentation, kind/bug/fix, size/S

#8676 Remove typo in Kubernetes providers labelSelector examples
  docs/content/providers/kubernetes-crd.md
  docs/content/providers/kubernetes-ingress.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/provider/k8s

#8686 Improve regexp matcher documentation
  docs/content/routing/routers/index.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S

#8687 Upgrade Instana tracer dependency
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, area/middleware/tracing

#8692 Support Consul KV Enterprise namespaces
  docs/content/providers/consul.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  go.mod
  go.sum
  integration/consul_test.go
  integration/etcd_test.go
  integration/redis_test.go
  integration/try/condition.go
  integration/zk_test.go
  pkg/config/kv/kv.go
  pkg/config/kv/kv_node.go
  pkg/config/kv/kv_node_test.go
  pkg/provider/kv/consul/consul.go
  pkg/provider/kv/etcd/etcd.go
  pkg/provider/kv/kv.go
  pkg/provider/kv/kv_mock_test.go
  pkg/provider/kv/kv_test.go
  pkg/provider/kv/redis/redis.go
  pkg/provider/kv/storewrapper.go
  pkg/provider/kv/zk/zk.go
Labels: status/3-needs-merge, area/provider/consul, kind/bug/fix, size/M, area/provider/kv

#8693 Prepare release v2.6.0-rc2
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8697 Fix middleware regexp's display
  webui/src/components/_commons/PanelMiddlewares.vue
Labels: status/3-needs-merge, area/webui, kind/bug/fix, size/S, area/middleware

#8702 fix: middleware plugins memory leak
  pkg/plugins/builder.go
  pkg/plugins/middlewares.go
  pkg/plugins/providers.go
Labels: status/3-needs-merge, kind/bug/fix, size/M, area/plugins

#8706 Mitigate memory leak
  go.mod
  go.sum
Labels: status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/server

#8713 Exclude www.cloudxns.net from documentation verification
  docs/scripts/verify.sh
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, area/infrastructure, size/S, bot/light-review

#8712 Support token authentication for Consul KV
  docs/content/providers/consul.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  pkg/provider/kv/kv.go
Labels: status/3-needs-merge, area/provider/consul, kind/bug/fix, size/S

#8715 Fix HTTP provider endpoint config example
  docs/content/providers/http.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, bot/light-review, area/provider/http

#8716 Update go-acme/lego to v4.6.0
  docs/content/https/acme.md
  go.mod
  go.sum
Labels: status/3-needs-merge, area/acme, kind/bug/fix, size/S, bot/light-review

#8717 Merge current v2.5 into v2.6
  docs/content/https/acme.md
  docs/content/providers/http.md
  go.mod
  go.sum
Labels: size/S

#8718 Adjust log level from info to debug
  pkg/server/configurationwatcher.go
Labels: status/3-needs-merge, kind/bug/fix, area/logs, size/S

#8719 Prepare release v2.5.7
  CHANGELOG.md
  script/gcg/traefik-bugfix.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8720 Merge current v2.5 into v2.6
  CHANGELOG.md
  pkg/server/configurationwatcher.go
  script/gcg/traefik-bugfix.toml
Labels: size/S

#8721 Prepare release v2.6.0-rc3
  CHANGELOG.md
  script/gcg/traefik-rc-new.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8722 Fix typo in metrics overview page
  docs/content/observability/metrics/overview.md
Labels: area/documentation, status/3-needs-merge, kind/bug/fix, size/S, area/middleware/metrics

#8699 Redact credentials before logging
  docs/scripts/verify.sh
  pkg/anonymize/anonymize_doOnStruct_test.go
  pkg/collector/collector.go
  pkg/config/dynamic/middlewares.go
  pkg/config/static/pilot.go
  pkg/config/static/static_config.go
  pkg/pilot/pilot.go
  pkg/ping/ping.go
  pkg/provider/acme/provider.go
  pkg/provider/aggregator/aggregator.go
  pkg/provider/consulcatalog/consul_catalog.go
  pkg/provider/ecs/ecs.go
  pkg/provider/kubernetes/crd/kubernetes.go
  pkg/provider/kubernetes/gateway/kubernetes.go
  pkg/provider/kubernetes/ingress/kubernetes.go
  pkg/provider/kv/kv.go
  pkg/provider/marathon/marathon.go
  pkg/redactor/redactor.go
  pkg/redactor/redactor_config_test.go
  pkg/redactor/redactor_doOnJSON_test.go
  pkg/redactor/redactor_doOnStruct_test.go
  pkg/redactor/testdata/anonymized-dynamic-config.json
  pkg/redactor/testdata/anonymized-static-config.json
  pkg/redactor/testdata/example.json
  pkg/redactor/testdata/expected.json
  pkg/redactor/testdata/secured-dynamic-config.json
  pkg/server/configurationwatcher.go
  pkg/tls/certificate.go
  pkg/tracing/elastic/elastic.go
  pkg/tracing/jaeger/jaeger.go
  pkg/types/metrics.go
  pkg/types/tls.go
Labels: kind/bug/fix, size/S

#8727 Merge current v2.5 into v2.6
  docs/content/observability/metrics/overview.md
Labels: size/S

#8730 Prepare release v2.6.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/content/getting-started/install-traefik.md
  docs/content/providers/kubernetes-ingress.md
  docs/scripts/verify.sh
  script/gcg/traefik-final-release-part1.toml
  script/gcg/traefik-final-release-part2.toml
Labels: area/documentation, status/3-needs-merge, size/S, bot/light-review

#8739 Clarify that ACME challenge is mandatory
  docs/content/https/acme.md
Labels: kind/enhancement, area/documentation, status/3-needs-merge, area/acme, size/S, bot/light-review

#8740 Add domain to HTTP challenge errors
  pkg/provider/acme/challenge_http.go
Labels: status/3-needs-merge, area/acme, kind/bug/fix, size/S

#8476 Watch for Consul events to rebuild the dynamic configuration
  docs/content/providers/consul-catalog.md
  docs/content/reference/static-configuration/cli-ref.md
  docs/content/reference/static-configuration/env-ref.md
  docs/content/reference/static-configuration/file.toml
  docs/content/reference/static-configuration/file.yaml
  integration/consul_catalog_test.go
  integration/fixtures/consul_catalog/simple_watch.toml
  pkg/provider/consulcatalog/connect_tls.go
  pkg/provider/consulcatalog/consul_catalog.go
Labels: kind/enhancement, status/3-needs-merge, size/S, area/provider/consulcatalog

#8746 Add Hurricane Electric to acme documentation
  docs/content/https/acme.md
Labels: area/documentation, status/3-needs-merge, area/acme, size/S
